"""S05-T06 — Golden end-to-end integration tests (import → proxy → scene detection → API state).

Proves the full S05 vertical slice on **real synthetic media** (CFR + VFR
fixtures generated by ffmpeg under ``tmp_path``) through the durable job
surface, with forced restart (successor), retry, cancel/replay, checksum/size
containment, stable Scene IDs and no-false-ready evidence — the acceptance
criteria of ``docs/pm/sessions/S05-T06-golden-integration/TASK.md``.

Golden evidence per test:

1. ``test_golden_cfr_full_pipeline_api_state_completed`` — AC1 CFR: managed
   import → canonical timebase + proxy → scene detection → UI/API state
   (``GET /api/jobs/{id}``, the endpoint the S05-T05 Import/Analyze UI polls)
   shows ``completed``; VideoItem probe columns written; canonical scene rows.
2. ``test_golden_vfr_full_pipeline_exact_rational`` — AC1 VFR: a real VFR
   fixture (``r_frame_rate != avg_frame_rate``) through the same pipeline;
   the canonical grid is the exact ``avg_frame_rate`` and every scene row
   recomputes exactly from the persisted rational timebase payload.
3. ``test_golden_forced_restart_successor_single_effect_set`` — AC2/AC5:
   rows committed then permanent failure; successor (same key + generation)
   reuses committed work — identical Scene IDs, one effect set, no duplicate
   rows/files, predecessor row immutable.
4. ``test_golden_crash_window_restart_recovery_same_job`` — AC2 (restart-
   recovery): rows committed, published checkpoint lost (contract §5.4
   replay-safe window) → same-job retry reuses rows by evidence; identical
   ids, revision 1, exactly one FFmpeg detection run.
5. ``test_golden_retry_after_failure_cleans_staging_committed_survive`` —
   AC3: permanent failure cleans the failed attempt's own staging; committed
   source+proxy artifacts survive (sha/size on disk); successor completes
   with one effect set; no orphan rows.
6. ``test_golden_cancel_replay_via_api_cleans_and_no_duplicates`` — AC3:
   cancel through the real HTTP endpoint (``POST /api/jobs/{id}/cancel``)
   drains to terminal ``cancelled`` with zero scene rows and clean staging;
   committed import/proxy artifacts survive; replay (successor) produces
   exactly one effect set.
7. ``test_golden_sha_size_containment_every_committed_artifact`` — AC4:
   SHA-256 + size of every committed artifact match the file on disk; every
   relative path is contained under the managed root; no staging leftovers.
8. ``test_golden_no_false_ready_before_publication_transaction`` — AC6:
   a queued/running job exposes no ready artifact, no final file and no
   VideoItem probe columns; a publication failure leaves the job ``failed``
   with nothing ready — readiness is only observable after the real
   publication transaction commits.
9. ``test_golden_forced_close_fresh_worker_restart_resumes`` — sprint-exit
   restart-recovery: a job left queued by a "killed" worker is completed by a
   brand-new worker over a fresh engine on the same database with exactly one
   effect set (no duplicates).

Every test uses a temporary database + temporary managed root and synthetic
ffmpeg fixtures under ``tmp_path`` only; tests skip gracefully when ffmpeg is
not available (mirroring ``tests/test_video_import.py``).
"""

from __future__ import annotations

import hashlib
import json
import shutil
import subprocess
from collections.abc import Iterator
from datetime import UTC, datetime, timedelta
from pathlib import Path

import pytest
from alembic import command
from alembic.config import Config
from sqlalchemy import select
from sqlalchemy.orm import Session

from app.persistence import (
    JobRepository,
    create_engine_for_path,
    create_session_factory,
)
from app.persistence.models import (
    Artifact,
    ArtifactOwner,
    Job,
    JobStep,
    Project,
    Scene,
    VideoItem,
    Workspace,
)
from app.services import scene_detector, video_import, video_proxy
from app.services.scene_detector import (
    CODE_PUBLICATION_FAILED,
    CODE_SCENE_DETECT_FAILED,
    SceneDetectionProfile,
    SceneDetectorError,
    register_scene_detection_handler,
    scene_ms_range,
    submit_scene_detection,
)
from app.services.timebase import CanonicalTimebase
from app.services.video_import import (
    CODE_PROBE_TIMEOUT,
    JOB_TYPE_ANALYZE_MEDIA,
    VideoImportError,
    submit_import,
)
from app.services.video_proxy import (
    ARTIFACT_PURPOSE_PROXY,
    JOB_TYPE_GENERATE_PROXY,
    register_generate_proxy_handler,
)
from app.workflow.durable_worker import DurableWorker, WorkerConfig

PROJECT_ROOT = Path(__file__).resolve().parent.parent
ALEMBIC_INI = PROJECT_ROOT / "alembic.ini"


# ── Deterministic clock/sleeper (mirror test_video_proxy.py) ────────────────


class FakeClock:
    def __init__(self, start: datetime | None = None) -> None:
        self.now = start or datetime(2026, 8, 5, 12, 0, 0, tzinfo=UTC)

    def __call__(self) -> datetime:
        return self.now

    def advance(self, seconds: float) -> None:
        self.now += timedelta(seconds=seconds)


class FakeSleeper:
    def __init__(self) -> None:
        self.calls: list[float] = []

    def __call__(self, seconds: float) -> None:
        self.calls.append(seconds)


# ── DB fixtures ──────────────────────────────────────────────────────────────


def _alembic_config(database_path: Path) -> Config:
    cfg = Config(str(ALEMBIC_INI))
    cfg.set_main_option("script_location", str(PROJECT_ROOT / "migrations"))
    cfg.set_main_option("sqlalchemy.url", f"sqlite:///{database_path.as_posix()}")
    return cfg


def _upgrade(database_path: Path) -> None:
    command.upgrade(_alembic_config(database_path), "head")


@pytest.fixture()
def db_path(tmp_path: Path) -> Path:
    return tmp_path / "golden.db"


@pytest.fixture()
def session_factory(db_path: Path):
    _upgrade(db_path)
    return create_session_factory(create_engine_for_path(db_path))


@pytest.fixture()
def session(session_factory) -> Iterator[Session]:
    with session_factory() as s:
        yield s


@pytest.fixture()
def ws(session: Session) -> Workspace:
    ws = Workspace(name="Golden Workspace")
    session.add(ws)
    session.commit()
    return ws


@pytest.fixture()
def project(session: Session, ws: Workspace) -> Project:
    project = Project(name="Golden Project", workspace_id=ws.id, status="active")
    session.add(project)
    session.commit()
    return project


@pytest.fixture()
def video_item(session: Session, project: Project) -> VideoItem:
    item = VideoItem(
        project_id=project.id,
        title="Golden Clip",
        position=0,
        status="imported",
        revision=1,
    )
    session.add(item)
    session.commit()
    return item


@pytest.fixture()
def managed_root(tmp_path: Path) -> Path:
    root = tmp_path / "managed"
    root.mkdir(exist_ok=True)
    return root


@pytest.fixture()
def clock() -> FakeClock:
    return FakeClock()


@pytest.fixture()
def sleeper() -> FakeSleeper:
    return FakeSleeper()


@pytest.fixture()
def worker(
    session_factory,
    managed_root: Path,
    clock: FakeClock,
    sleeper: FakeSleeper,
) -> DurableWorker:
    """A worker with fake clock/sleeper and the full S05 handler set:
    GENERATE_PROXY (S05-T03) + the ANALYZE_MEDIA dispatcher (import S05-T02
    + scene_detect S05-T04)."""
    w = DurableWorker(
        session_factory,
        config=WorkerConfig(
            worker_id="golden-worker",
            lease_ttl=60,
            heartbeat_interval=15,
            poll_interval=0.01,
            max_attempts=3,
            staging_root=managed_root,
        ),
        clock=clock,
        sleeper=sleeper,
    )
    register_generate_proxy_handler(w)
    register_scene_detection_handler(w)
    return w


@pytest.fixture()
def api_client(session_factory, managed_root: Path, db_path: Path):
    """A TestClient over the real FastAPI app with deps pointed at the same
    database + managed root — the exact ``GET /api/jobs/{id}`` / ``POST
    /api/jobs/{id}/cancel`` surface the S05-T05 Import/Analyze UI polls.
    Deps globals are saved and restored so other tests are unaffected."""
    from fastapi.testclient import TestClient

    from app.api import deps
    from app.api.app import app
    from app.config import AppConfig
    from app.workflow.job_service import JobService
    from app.workflow.project_workflow import ProjectWorkflowService

    cfg = AppConfig(
        project_root=db_path.parent / "proj",
        models_dir=db_path.parent / "proj" / "models",
        output_dir=db_path.parent / "proj" / "output",
    )
    saved = (
        getattr(deps, "_config", None),
        getattr(deps, "_project_wf", None),
        getattr(deps, "_job_service", None),
        getattr(deps, "_lifecycle_db", None),
    )
    deps._config = cfg
    deps._project_wf = ProjectWorkflowService(cfg)
    deps._job_service = JobService(session_factory, managed_root=managed_root)
    deps._lifecycle_db = db_path
    client = TestClient(app, raise_server_exceptions=True)
    yield client
    (
        deps._config,
        deps._project_wf,
        deps._job_service,
        deps._lifecycle_db,
    ) = saved


# ── Synthetic media fixtures (real ffmpeg → tmp_path) ───────────────────────


def _ffmpeg_available() -> bool:
    try:
        from app.services.ffmpeg_utils import find_ffprobe

        find_ffprobe()
        return shutil.which("ffmpeg") is not None
    except Exception:
        return False


def _make_video(
    path: Path,
    *,
    duration: float = 1.0,
    fps: int = 30,
    color: str = "blue",
) -> Path | None:
    """Create a CFR synthetic MP4/H.264 clip (static color)."""
    ffmpeg = shutil.which("ffmpeg") or "ffmpeg"
    path.parent.mkdir(parents=True, exist_ok=True)
    cmd = [
        ffmpeg,
        "-y",
        "-f",
        "lavfi",
        "-i",
        f"color=c={color}:duration={duration}:size=320x240:rate={fps}",
        "-c:v",
        "libx264",
        "-preset",
        "ultrafast",
        "-crf",
        "28",
        "-pix_fmt",
        "yuv420p",
        str(path),
    ]
    result = subprocess.run(cmd, capture_output=True, text=True, timeout=60)
    if result.returncode != 0:
        return None
    return path


def _make_cut_video(path: Path, *, fps: int = 30, rate: str | None = None) -> Path | None:
    """A 2s/60-frame clip with ONE hard cut at frame ``round(1s * fps)``:
    blue (1s) → red (1s), scene score ~1.0, zero motion noise."""
    ffmpeg = shutil.which("ffmpeg") or "ffmpeg"
    path.parent.mkdir(parents=True, exist_ok=True)
    rate_arg = rate or str(fps)
    cmd = [
        ffmpeg,
        "-y",
        "-f",
        "lavfi",
        "-i",
        f"color=c=blue:duration=1.0:size=320x240:rate={rate_arg}",
        "-f",
        "lavfi",
        "-i",
        f"color=c=red:duration=1.0:size=320x240:rate={rate_arg}",
        "-filter_complex",
        "[0:v][1:v]concat=n=2:v=1:a=0[v]",
        "-map",
        "[v]",
        "-c:v",
        "libx264",
        "-preset",
        "ultrafast",
        "-crf",
        "28",
        "-pix_fmt",
        "yuv420p",
        str(path),
    ]
    result = subprocess.run(cmd, capture_output=True, text=True, timeout=60)
    if result.returncode != 0:
        return None
    return path


def _make_vfr_cut_video(tmp_path: Path, name: str = "vfr.mp4") -> Path | None:
    """A real VFR MP4 with one hard cut: a 30fps blue segment + a 25fps red
    segment concatenated with ``-c copy`` → ``r_frame_rate != avg_frame_rate``
    (genuinely VFR) and a hard color change at the segment boundary."""
    ffmpeg = shutil.which("ffmpeg") or "ffmpeg"
    seg1 = tmp_path / "seg30.mp4"
    seg2 = tmp_path / "seg25.mp4"
    for seg, fps, color in ((seg1, 30, "blue"), (seg2, 25, "red")):
        made = _make_video(seg, duration=1.0, fps=fps, color=color)
        assert made is not None, "ffmpeg failed to create a VFR segment"
    lst = tmp_path / "concat.txt"
    lst.write_text(f"file '{seg1.as_posix()}'\nfile '{seg2.as_posix()}'\n", encoding="utf-8")
    out = tmp_path / name
    result = subprocess.run(
        [
            ffmpeg,
            "-y",
            "-f",
            "concat",
            "-safe",
            "0",
            "-i",
            str(lst),
            "-c",
            "copy",
            "-movflags",
            "+faststart",
            str(out),
        ],
        capture_output=True,
        text=True,
        timeout=60,
    )
    if result.returncode != 0:
        pytest.skip("ffmpeg concat failed to create the VFR fixture")
    probe = video_import.probe_source(out)
    video = probe["video_stream"]
    if video["r_frame_rate"] == video["avg_frame_rate"]:
        pytest.skip("concat output is not genuinely VFR on this ffmpeg build")
    return out


@pytest.fixture()
def cfr_cut_video(tmp_path: Path) -> Path:
    """2s/60-frame 30fps CFR MP4 with exactly one hard cut at frame 30."""
    if not _ffmpeg_available():
        pytest.skip("ffmpeg/ffprobe not available")
    out = _make_cut_video(tmp_path / "cfr_cut.mp4", fps=30)
    assert out is not None, "ffmpeg failed to create the CFR cut fixture"
    return out


@pytest.fixture()
def vfr_cut_video(tmp_path: Path) -> Path:
    """Real VFR MP4 (30fps + 25fps concat) with one hard cut at the boundary."""
    if not _ffmpeg_available():
        pytest.skip("ffmpeg/ffprobe not available")
    out = _make_vfr_cut_video(tmp_path)
    assert out is not None, "ffmpeg failed to create the VFR cut fixture"
    return out


# ── Pipeline helpers ─────────────────────────────────────────────────────────


def _import_source(
    session_factory,
    worker: DurableWorker,
    ws: Workspace,
    video_item: VideoItem,
    source: Path,
    managed_root: Path,
) -> tuple[str, str]:
    """Run the approved S05-T02 import and return (import_job_id,
    source_artifact_id)."""
    result = submit_import(
        session_factory,
        workspace_id=ws.id,
        project_id=video_item.project_id,
        video_item_id=video_item.id,
        source_path=source,
        source_sha256=hashlib.sha256(source.read_bytes()).hexdigest(),
        generation="1",
        managed_root=managed_root,
        title=source.name,
    )
    _run_job(worker)
    assert _job_state(session_factory, result.job_id) == "completed"
    with session_factory() as s:
        art_id = s.scalar(
            select(ArtifactOwner.artifact_id).where(
                ArtifactOwner.owner_type == "video_item",
                ArtifactOwner.owner_id == video_item.id,
                ArtifactOwner.purpose == video_import.ARTIFACT_PURPOSE_SOURCE,
            )
        )
    assert art_id is not None, "import did not link a source artifact"
    return result.job_id, str(art_id)


def _generate_proxy(
    session_factory,
    worker: DurableWorker,
    ws: Workspace,
    video_item: VideoItem,
    source_artifact_id: str,
    managed_root: Path,
) -> tuple[str, str]:
    """Run the approved S05-T03 GENERATE_PROXY and return (proxy_job_id,
    proxy_artifact_id)."""
    result = video_proxy.submit_proxy(
        session_factory,
        workspace_id=ws.id,
        project_id=video_item.project_id,
        video_item_id=video_item.id,
        source_artifact_id=source_artifact_id,
        generation="1",
        managed_root=managed_root,
        title="proxy",
    )
    _run_job(worker)
    assert _job_state(session_factory, result.job_id) == "completed"
    with session_factory() as s:
        art_id = s.scalar(
            select(ArtifactOwner.artifact_id).where(
                ArtifactOwner.owner_type == "video_item",
                ArtifactOwner.owner_id == video_item.id,
                ArtifactOwner.purpose == ARTIFACT_PURPOSE_PROXY,
            )
        )
    assert art_id is not None, "proxy job did not link a proxy artifact"
    return result.job_id, str(art_id)


def _submit_scene_detection(
    session_factory,
    ws: Workspace,
    video_item: VideoItem,
    source_artifact_id: str,
    managed_root: Path,
    *,
    proxy_artifact_id: str | None = None,
    generation: str = "1",
    profile: SceneDetectionProfile | None = None,
):
    return submit_scene_detection(
        session_factory,
        workspace_id=ws.id,
        project_id=video_item.project_id,
        video_item_id=video_item.id,
        source_artifact_id=source_artifact_id,
        proxy_artifact_id=proxy_artifact_id,
        generation=generation,
        managed_root=managed_root,
        title="scene_detect",
        profile=profile,
    )


def _run_job(worker: DurableWorker) -> None:
    worker.run_once()


def _job_state(session_factory, job_id: str) -> str:
    with session_factory() as s:
        return JobRepository(s).get_job(job_id).state


def _job_error(session_factory, job_id: str) -> dict | None:
    with session_factory() as s:
        return JobRepository(s).get_job(job_id).error


def _scene_rows(session_factory, video_item_id: str) -> list[Scene]:
    with session_factory() as s:
        return list(
            s.scalars(
                select(Scene).where(Scene.video_item_id == video_item_id).order_by(Scene.position)
            ).all()
        )


def _staging_files(managed_root: Path) -> list[Path]:
    staging = managed_root / "staging"
    if not staging.is_dir():
        return []
    return [p for p in staging.rglob("*") if p.is_file()]


def _step_checkpoint(session_factory, job_id: str) -> dict:
    with session_factory() as s:
        repo = JobRepository(s)
        step_row = s.get(JobStep, repo.list_steps(job_id)[0].id)
        return json.loads(step_row.checkpoint_json or "{}")


def _artifact_sha_size(path: Path) -> tuple[str, int]:
    return hashlib.sha256(path.read_bytes()).hexdigest(), path.stat().st_size


def _ready_video_artifacts(session_factory, workspace_id: str) -> list[Artifact]:
    with session_factory() as s:
        return list(
            s.scalars(
                select(Artifact)
                .where(
                    Artifact.workspace_id == workspace_id,
                    Artifact.kind == "video",
                    Artifact.state == "ready",
                )
                .order_by(Artifact.relative_path)
            ).all()
        )


def _owner_purposes(session_factory, artifact_id: str) -> set[str]:
    with session_factory() as s:
        return set(
            s.scalars(
                select(ArtifactOwner.purpose).where(ArtifactOwner.artifact_id == artifact_id)
            ).all()
        )


def _api_status(client, job_id: str) -> dict:
    resp = client.get(f"/api/jobs/{job_id}")
    assert resp.status_code == 200, f"GET /api/jobs/{job_id} → {resp.status_code}"
    return resp.json()


# ── AC1: CFR golden path ─────────────────────────────────────────────────────


def test_golden_cfr_full_pipeline_api_state_completed(
    worker, session_factory, ws, video_item, cfr_cut_video, managed_root, api_client
) -> None:
    """CFR golden: import → proxy → scene detection, all jobs `completed`
    through the real job API (the S05-T05 UI surface), VideoItem probe
    columns written, canonical scene rows committed."""
    # 1. Managed import (S05-T02)
    import_job_id, source_artifact_id = _import_source(
        session_factory, worker, ws, video_item, cfr_cut_video, managed_root
    )
    # 2. Canonical timebase + proxy (S05-T03)
    proxy_job_id, proxy_artifact_id = _generate_proxy(
        session_factory, worker, ws, video_item, source_artifact_id, managed_root
    )
    # 3. Scene detection (S05-T04) consuming the proxy
    result = _submit_scene_detection(
        session_factory,
        ws,
        video_item,
        source_artifact_id,
        managed_root,
        proxy_artifact_id=proxy_artifact_id,
    )
    scene_job_id = result.job_id
    _run_job(worker)

    # UI/API state: the exact endpoint the Import/Analyze UI polls.
    import_info = _api_status(api_client, import_job_id)
    proxy_info = _api_status(api_client, proxy_job_id)
    scene_info = _api_status(api_client, scene_job_id)
    assert import_info["status"] == "completed"
    assert import_info["job_type"] == JOB_TYPE_ANALYZE_MEDIA
    assert proxy_info["status"] == "completed"
    assert proxy_info["job_type"] == JOB_TYPE_GENERATE_PROXY
    assert scene_info["status"] == "completed"
    assert scene_info["job_type"] == JOB_TYPE_ANALYZE_MEDIA
    # The scene-detect handler publishes real progress (10 → 60 → 100).
    assert scene_info["progress"] == 100.0

    # VideoItem probe columns persisted by the import publication txn.
    with session_factory() as s:
        item = s.get(VideoItem, video_item.id)
        assert item.duration_ms == 2000
        assert item.width == 320
        assert item.height == 240
        assert (item.fps_num, item.fps_den) == (30, 1)
        assert item.source_artifact_id == source_artifact_id

    # Canonical scene rows (30fps CFR: cut at frame 30 → t=1.000s exactly).
    rows = _scene_rows(session_factory, video_item.id)
    assert len(rows) == 2
    assert [r.position for r in rows] == [0, 1]
    assert [(r.start_frame, r.end_frame) for r in rows] == [(0, 29), (30, 59)]
    assert [(r.start_time_ms, r.end_time_ms) for r in rows] == [(0, 999), (1000, 1999)]
    assert all(r.status == "pending" for r in rows)
    assert all(r.revision == 1 for r in rows)
    assert all(r.legacy_scene_id is None for r in rows)

    # The detection consumed the proxy artifact (golden proxy path).
    cp = _step_checkpoint(session_factory, scene_job_id)
    assert cp["input"]["kind"] == "proxy"
    assert cp["input"]["artifact_id"] == proxy_artifact_id
    assert _staging_files(managed_root) == []


def test_golden_vfr_full_pipeline_exact_rational(
    worker, session_factory, ws, video_item, vfr_cut_video, managed_root, api_client
) -> None:
    """VFR golden: the same pipeline on a real VFR fixture. The import
    classifies VFR; the canonical grid is the exact avg_frame_rate; the
    proxy resamples onto that grid; every scene row recomputes exactly from
    the persisted rational timebase payload."""
    # 1. Import — checkpoint records the real VFR classification.
    import_job_id, source_artifact_id = _import_source(
        session_factory, worker, ws, video_item, vfr_cut_video, managed_root
    )
    import_cp = _step_checkpoint(session_factory, import_job_id)
    src_video = import_cp["probe"]["video_stream"]
    assert src_video["fps_classification"] == "VFR"
    assert src_video["r_frame_rate"] != src_video["avg_frame_rate"]
    avg_num = int(src_video["avg_frame_rate"]["num"])
    avg_den = int(src_video["avg_frame_rate"]["den"])
    assert avg_num > 0 and avg_den > 0

    # 2. Proxy — resampled onto the canonical avg_frame_rate grid.
    proxy_job_id, proxy_artifact_id = _generate_proxy(
        session_factory, worker, ws, video_item, source_artifact_id, managed_root
    )
    proxy_cp = _step_checkpoint(session_factory, proxy_job_id)
    proxy_tb = CanonicalTimebase.from_json(proxy_cp["timebase"])
    assert (proxy_tb.fps_num, proxy_tb.fps_den) == (avg_num, avg_den)

    # 3. Scene detection on the proxy.
    result = _submit_scene_detection(
        session_factory,
        ws,
        video_item,
        source_artifact_id,
        managed_root,
        proxy_artifact_id=proxy_artifact_id,
    )
    scene_job_id = result.job_id
    _run_job(worker)

    # API state completed for all three jobs.
    assert _api_status(api_client, import_job_id)["status"] == "completed"
    assert _api_status(api_client, proxy_job_id)["status"] == "completed"
    assert _api_status(api_client, scene_job_id)["status"] == "completed"
    assert _api_status(api_client, scene_job_id)["progress"] == 100.0

    # Every row recomputes exactly from the persisted rational payload —
    # no float drift on the VFR grid.
    cp = _step_checkpoint(session_factory, scene_job_id)
    timebase = CanonicalTimebase.from_json(cp["detection"]["timebase"])
    assert (timebase.fps_num, timebase.fps_den) == (avg_num, avg_den)
    rows = _scene_rows(session_factory, video_item.id)
    assert len(rows) >= 2, f"VFR cut not detected: {len(rows)} row(s)"
    positions = [r.position for r in rows]
    assert len(set(positions)) == len(positions)
    for row in rows:
        assert 0 <= row.start_frame <= row.end_frame < (timebase.nb_frames or 0)
        start_ms, end_ms = scene_ms_range(timebase, row.start_frame, row.end_frame)
        assert (row.start_time_ms, row.end_time_ms) == (start_ms, end_ms)
    assert _staging_files(managed_root) == []


# ── AC2/AC5: forced restart (successor), stable Scene IDs ───────────────────


def test_golden_forced_restart_successor_single_effect_set(
    worker, session_factory, ws, video_item, cfr_cut_video, managed_root, api_client, monkeypatch
) -> None:
    """Rows committed then permanent failure → a forced restart creates a
    successor (same idempotency key + generation) which reuses the committed
    work: identical Scene IDs, exactly one effect set, no duplicate rows or
    files, predecessor row immutable, staging clean."""
    import_job_id, source_artifact_id = _import_source(
        session_factory, worker, ws, video_item, cfr_cut_video, managed_root
    )
    proxy_job_id, proxy_artifact_id = _generate_proxy(
        session_factory, worker, ws, video_item, source_artifact_id, managed_root
    )
    first = _submit_scene_detection(
        session_factory,
        ws,
        video_item,
        source_artifact_id,
        managed_root,
        proxy_artifact_id=proxy_artifact_id,
    )
    real_commit = scene_detector._commit_scene_rows

    def commit_then_permanent_fail(ctx, det_ev):
        real_commit(ctx, det_ev)  # durable rows committed
        raise SceneDetectorError(
            CODE_PUBLICATION_FAILED, "injected permanent failure after commit"
        )

    monkeypatch.setattr(scene_detector, "_commit_scene_rows", commit_then_permanent_fail)
    _run_job(worker)
    assert _job_state(session_factory, first.job_id) == "failed"
    committed_ids = [r.id for r in _scene_rows(session_factory, video_item.id)]
    assert len(committed_ids) == 2

    monkeypatch.undo()
    with session_factory() as s:
        repo = JobRepository(s)
        pred = repo.get_job(first.job_id)
        pred_revision = pred.revision
        succ = repo.create_successor(
            predecessor_job_id=pred.id,
            input_manifest=pred.input_manifest,
            idempotency_key=pred.idempotency_key,
            input_generation=pred.input_generation,
            steps=scene_detector.scene_detection_steps(),
        )
        s.commit()
        succ_id = succ.id
    _run_job(worker)

    # Successor completed through the API; predecessor row untouched.
    assert _api_status(api_client, succ_id)["status"] == "completed"
    with session_factory() as s:
        pred_after = JobRepository(s).get_job(first.job_id)
        assert pred_after.state == "failed"  # terminal rows are immutable
        assert pred_after.revision == pred_revision
        chain = s.scalars(
            select(Job).where(
                Job.idempotency_key == pred_after.idempotency_key,
                Job.input_generation == pred_after.input_generation,
            )
        ).all()
        assert len(chain) == 2  # predecessor + successor

    # ONE effect set: identical scene ids, revision 1, no duplicates.
    rows = _scene_rows(session_factory, video_item.id)
    assert [r.id for r in rows] == committed_ids
    assert all(r.revision == 1 for r in rows)

    # Exactly one source + one proxy artifact row/file (no duplicates).
    arts = _ready_video_artifacts(session_factory, ws.id)
    assert len(arts) == 2
    for art in arts:
        assert _owner_purposes(session_factory, art.id) in (
            {video_import.ARTIFACT_PURPOSE_SOURCE},
            {ARTIFACT_PURPOSE_PROXY},
        )
    assert _staging_files(managed_root) == []


def test_golden_crash_window_restart_recovery_same_job(
    worker, session_factory, ws, video_item, cfr_cut_video, managed_root, monkeypatch
) -> None:
    """Restart-recovery (contract §5.4 replay-safe window): rows committed but
    the published checkpoint lost (crash between effect commit and checkpoint
    write) → the same job's retry reuses the committed rows by evidence —
    identical Scene IDs, revision 1, exactly one FFmpeg detection run."""
    _, source_artifact_id = _import_source(
        session_factory, worker, ws, video_item, cfr_cut_video, managed_root
    )
    result = _submit_scene_detection(
        session_factory, ws, video_item, source_artifact_id, managed_root
    )
    job_id = result.job_id
    real_detect = scene_detector._run_scene_detect
    real_commit = scene_detector._commit_scene_rows
    detect_calls: list[str] = []
    crashed = False

    def detect_count(ctx, input_path, profile, timebase):
        detect_calls.append("run")
        return real_detect(ctx, input_path, profile, timebase)

    def commit_then_crash_once(ctx, det_ev):
        nonlocal crashed
        rows = real_commit(ctx, det_ev)  # effect committed
        if not crashed:
            crashed = True
            raise VideoImportError(CODE_PROBE_TIMEOUT, "transient crash after commit (injected)")
        return rows

    monkeypatch.setattr(scene_detector, "_run_scene_detect", detect_count)
    monkeypatch.setattr(scene_detector, "_commit_scene_rows", commit_then_crash_once)
    _run_job(worker)

    assert _job_state(session_factory, job_id) == "completed"
    rows = _scene_rows(session_factory, video_item.id)
    assert len(rows) == 2
    assert len(detect_calls) == 1, "detection re-ran after a committed checkpoint"
    assert all(r.revision == 1 for r in rows)
    with session_factory() as s:
        attempts = JobRepository(s).list_attempts(job_id)
        assert len(attempts) >= 2  # crash attempt + recovery attempt recorded
    assert _staging_files(managed_root) == []


# ── AC3: retry / cancel / orphan cleanup ─────────────────────────────────────


def test_golden_retry_after_failure_cleans_staging_committed_survive(
    worker, session_factory, ws, video_item, cfr_cut_video, managed_root, monkeypatch
) -> None:
    """A permanent detection failure cleans the failed attempt's own staging
    and leaves zero rows; the committed source + proxy artifacts survive
    (sha/size on disk); a successor retry completes with exactly one effect
    set and no orphan rows."""
    import_job_id, source_artifact_id = _import_source(
        session_factory, worker, ws, video_item, cfr_cut_video, managed_root
    )
    proxy_job_id, proxy_artifact_id = _generate_proxy(
        session_factory, worker, ws, video_item, source_artifact_id, managed_root
    )
    first = _submit_scene_detection(
        session_factory,
        ws,
        video_item,
        source_artifact_id,
        managed_root,
        proxy_artifact_id=proxy_artifact_id,
    )

    def fail_detect(ctx, input_path, profile, timebase):
        raise SceneDetectorError(CODE_SCENE_DETECT_FAILED, "injected detection failure")

    monkeypatch.setattr(scene_detector, "_run_scene_detect", fail_detect)
    _run_job(worker)
    assert _job_state(session_factory, first.job_id) == "failed"
    error = _job_error(session_factory, first.job_id)
    assert error is not None and error["error_code"] == CODE_SCENE_DETECT_FAILED
    assert _scene_rows(session_factory, video_item.id) == []
    assert _staging_files(managed_root) == []

    # Committed artifacts survive the failure unchanged.
    with session_factory() as s:
        src = s.get(Artifact, source_artifact_id)
        proxy = s.get(Artifact, proxy_artifact_id)
        src_sha, src_size = _artifact_sha_size(managed_root / src.relative_path)
        proxy_sha, proxy_size = _artifact_sha_size(managed_root / proxy.relative_path)
    assert (src.sha256, src.size_bytes) == (src_sha, src_size)
    assert (proxy.sha256, proxy.size_bytes) == (proxy_sha, proxy_size)

    # Retry via successor: exactly one effect set, no orphan rows.
    monkeypatch.undo()
    with session_factory() as s:
        repo = JobRepository(s)
        pred = repo.get_job(first.job_id)
        succ = repo.create_successor(
            predecessor_job_id=pred.id,
            input_manifest=pred.input_manifest,
            idempotency_key=pred.idempotency_key,
            input_generation=pred.input_generation,
            steps=scene_detector.scene_detection_steps(),
        )
        s.commit()
        succ_id = succ.id
    _run_job(worker)
    assert _job_state(session_factory, succ_id) == "completed"
    rows = _scene_rows(session_factory, video_item.id)
    assert len(rows) == 2  # exactly one effect set
    assert _staging_files(managed_root) == []
    assert _job_state(session_factory, import_job_id) == "completed"
    assert _job_state(session_factory, proxy_job_id) == "completed"


def test_golden_cancel_replay_via_api_cleans_and_no_duplicates(
    worker, session_factory, ws, video_item, cfr_cut_video, managed_root, api_client, monkeypatch
) -> None:
    """Cancel through the real HTTP endpoint while the detection is running
    drains to terminal `cancelled` with zero scene rows and clean staging;
    the committed import/proxy artifacts survive; a replay (successor) with
    the same key completes with exactly one effect set."""
    import_job_id, source_artifact_id = _import_source(
        session_factory, worker, ws, video_item, cfr_cut_video, managed_root
    )
    proxy_job_id, proxy_artifact_id = _generate_proxy(
        session_factory, worker, ws, video_item, source_artifact_id, managed_root
    )
    result = _submit_scene_detection(
        session_factory,
        ws,
        video_item,
        source_artifact_id,
        managed_root,
        proxy_artifact_id=proxy_artifact_id,
    )
    job_id = result.job_id
    real_detect = scene_detector._run_scene_detect

    def detect_then_http_cancel(ctx, input_path, profile, timebase):
        # The real HTTP cancel endpoint while the worker holds the claim.
        resp = api_client.post(f"/api/jobs/{job_id}/cancel")
        assert resp.status_code == 200
        assert resp.json()["status"] == "cancel_requested"
        return real_detect(ctx, input_path, profile, timebase)

    monkeypatch.setattr(scene_detector, "_run_scene_detect", detect_then_http_cancel)
    _run_job(worker)

    # Terminal cancelled; zero scene rows; staging clean; no final outputs.
    assert _job_state(session_factory, job_id) == "cancelled"
    assert _api_status(api_client, job_id)["status"] == "cancelled"
    assert _scene_rows(session_factory, video_item.id) == []
    assert _staging_files(managed_root) == []

    # Committed artifacts survive the cancel untouched.
    with session_factory() as s:
        src = s.get(Artifact, source_artifact_id)
        proxy = s.get(Artifact, proxy_artifact_id)
        src_sha, src_size = _artifact_sha_size(managed_root / src.relative_path)
        proxy_sha, proxy_size = _artifact_sha_size(managed_root / proxy.relative_path)
    assert (src.sha256, src.size_bytes) == (src_sha, src_size)
    assert (proxy.sha256, proxy.size_bytes) == (proxy_sha, proxy_size)

    # Replay: the cancelled run may be retried as a successor (same key +
    # generation) → exactly one effect set, no orphan rows.
    monkeypatch.undo()
    with session_factory() as s:
        repo = JobRepository(s)
        pred = repo.get_job(job_id)
        assert pred.state == "cancelled"
        succ = repo.create_successor(
            predecessor_job_id=pred.id,
            input_manifest=pred.input_manifest,
            idempotency_key=pred.idempotency_key,
            input_generation=pred.input_generation,
            steps=scene_detector.scene_detection_steps(),
        )
        s.commit()
        succ_id = succ.id
    _run_job(worker)
    assert _job_state(session_factory, succ_id) == "completed"
    assert _api_status(api_client, succ_id)["status"] == "completed"
    rows = _scene_rows(session_factory, video_item.id)
    assert len(rows) == 2  # one effect set after replay
    with session_factory() as s:
        chain = s.scalars(
            select(Job).where(
                Job.idempotency_key == pred.idempotency_key,
                Job.input_generation == pred.input_generation,
            )
        ).all()
        assert len(chain) == 2  # cancelled predecessor + successor
    assert _staging_files(managed_root) == []


# ── AC4: checksum / size / containment ───────────────────────────────────────


def test_golden_sha_size_containment_every_committed_artifact(
    worker, session_factory, ws, video_item, cfr_cut_video, managed_root
) -> None:
    """Every committed artifact's SHA-256 + size match the file on disk and
    every relative path is contained under the managed root; no staging
    leftovers anywhere."""
    import_job_id, source_artifact_id = _import_source(
        session_factory, worker, ws, video_item, cfr_cut_video, managed_root
    )
    proxy_job_id, proxy_artifact_id = _generate_proxy(
        session_factory, worker, ws, video_item, source_artifact_id, managed_root
    )
    result = _submit_scene_detection(
        session_factory,
        ws,
        video_item,
        source_artifact_id,
        managed_root,
        proxy_artifact_id=proxy_artifact_id,
    )
    _run_job(worker)
    assert _job_state(session_factory, result.job_id) == "completed"

    root = managed_root.resolve()
    arts = _ready_video_artifacts(session_factory, ws.id)
    assert len(arts) == 2  # source + proxy, nothing else
    purposes_seen: set[str] = set()
    for art in arts:
        # SHA-256 + size match the file on disk.
        sha, size = _artifact_sha_size(root / art.relative_path)
        assert art.sha256 == sha
        assert art.size_bytes == size
        # Containment: relative path resolves strictly inside the managed root.
        resolved = (root / art.relative_path).resolve()
        assert resolved.is_relative_to(root), (
            f"artifact escaped the managed root: {art.relative_path}"
        )
        assert art.relative_path.startswith("artifacts/")
        assert not art.relative_path.startswith("/")
        assert ".." not in art.relative_path.split("/")
        purposes_seen.update(_owner_purposes(session_factory, art.id))
    assert purposes_seen == {
        video_import.ARTIFACT_PURPOSE_SOURCE,
        ARTIFACT_PURPOSE_PROXY,
    }
    # No staging files, no stray files outside the managed root structure.
    assert _staging_files(managed_root) == []
    all_files = [p for p in root.rglob("*") if p.is_file()]
    for f in all_files:
        assert f.is_relative_to(root / "artifacts"), f"file outside artifacts/: {f}"


# ── AC6: no false-ready artifact ─────────────────────────────────────────────


def test_golden_no_false_ready_before_publication_transaction(
    worker, session_factory, ws, video_item, cfr_cut_video, managed_root, api_client, monkeypatch
) -> None:
    """Readiness is only observable after the real publication transaction
    commits: a queued job exposes no ready artifact/file/probe columns; a
    publication failure leaves the job `failed` with nothing ready."""
    # ── (a) Queued proxy job: nothing ready yet, API honest. ──
    _, source_artifact_id = _import_source(
        session_factory, worker, ws, video_item, cfr_cut_video, managed_root
    )
    proxy_result = video_proxy.submit_proxy(
        session_factory,
        workspace_id=ws.id,
        project_id=video_item.project_id,
        video_item_id=video_item.id,
        source_artifact_id=source_artifact_id,
        generation="1",
        managed_root=managed_root,
        title="proxy",
    )
    # The worker never ran: the job is durably queued and NOT ready.
    assert _job_state(session_factory, proxy_result.job_id) == "queued"
    assert _api_status(api_client, proxy_result.job_id)["status"] == "queued"
    arts = _ready_video_artifacts(session_factory, ws.id)
    assert [a.id for a in arts] == [source_artifact_id]  # only the import's source
    with session_factory() as s:
        proxy_rows = s.scalars(
            select(Artifact).where(Artifact.relative_path.like("%proxy%"))
        ).all()
    assert proxy_rows == []
    # ── (b) Proxy publication fails → failed, nothing ready, staging clean. ──
    def fail_proxy_publish(*args, **kwargs):
        raise VideoImportError(CODE_PUBLICATION_FAILED, "injected proxy publication failure")

    monkeypatch.setattr(video_proxy, "_publish_effect", fail_proxy_publish)
    _run_job(worker)
    assert _job_state(session_factory, proxy_result.job_id) == "failed"
    assert _api_status(api_client, proxy_result.job_id)["status"] == "failed"
    arts = _ready_video_artifacts(session_factory, ws.id)
    assert [a.id for a in arts] == [source_artifact_id]  # no false-ready proxy
    with session_factory() as s:
        proxy_rows = s.scalars(
            select(Artifact).where(Artifact.relative_path.like("%proxy%"))
        ).all()
    assert proxy_rows == []
    assert _staging_files(managed_root) == []

    # ── (c) Import publication fails → failed; probe columns stay NULL. ──
    monkeypatch.undo()
    # A second VideoItem for a fresh import submit.
    with session_factory() as s:
        item2 = VideoItem(
            project_id=video_item.project_id,
            title="Golden Clip 2",
            position=1,
            status="imported",
            revision=1,
        )
        s.add(item2)
        s.commit()
        item2_id = item2.id
    import_result = submit_import(
        session_factory,
        workspace_id=ws.id,
        project_id=video_item.project_id,
        video_item_id=item2_id,
        source_path=cfr_cut_video,
        source_sha256=hashlib.sha256(cfr_cut_video.read_bytes()).hexdigest(),
        generation="1",
        managed_root=managed_root,
        title=cfr_cut_video.name,
    )

    def fail_import_publish(*args, **kwargs):
        raise VideoImportError(CODE_PUBLICATION_FAILED, "injected import publication failure")

    monkeypatch.setattr(video_import, "_publish_effect", fail_import_publish)
    _run_job(worker)
    assert _job_state(session_factory, import_result.job_id) == "failed"
    assert _api_status(api_client, import_result.job_id)["status"] == "failed"
    with session_factory() as s:
        item2 = s.get(VideoItem, item2_id)
        assert item2.duration_ms is None  # probe columns never written
        assert item2.width is None
        assert item2.height is None
        assert item2.fps_num is None
        assert item2.source_artifact_id is None
        item2_sources = s.scalars(
            select(ArtifactOwner.artifact_id).where(
                ArtifactOwner.owner_type == "video_item",
                ArtifactOwner.owner_id == item2_id,
                ArtifactOwner.purpose == video_import.ARTIFACT_PURPOSE_SOURCE,
            )
        ).all()
    assert item2_sources == []
    arts = _ready_video_artifacts(session_factory, ws.id)
    assert [a.id for a in arts] == [source_artifact_id]
    assert _staging_files(managed_root) == []


# ── Sprint-exit restart-recovery evidence ────────────────────────────────────


def test_golden_forced_close_fresh_worker_restart_resumes(
    worker, session_factory, db_path, ws, video_item, cfr_cut_video, managed_root
) -> None:
    """A job left queued by a 'killed' worker is completed by a brand-new
    worker over a fresh engine on the same database — exactly one effect set
    per logical run, no duplicates after process restart."""
    # Phase 1 ("process 1"): import completes; proxy is submitted and left
    # queued — the worker is dropped without ever claiming it (forced close).
    import_job_id, source_artifact_id = _import_source(
        session_factory, worker, ws, video_item, cfr_cut_video, managed_root
    )
    proxy_result = video_proxy.submit_proxy(
        session_factory,
        workspace_id=ws.id,
        project_id=video_item.project_id,
        video_item_id=video_item.id,
        source_artifact_id=source_artifact_id,
        generation="1",
        managed_root=managed_root,
        title="proxy",
    )
    assert _job_state(session_factory, proxy_result.job_id) == "queued"

    # Phase 2 ("restart"): a fresh engine + brand-new worker on the same DB.
    engine2 = create_engine_for_path(db_path)
    factory2 = create_session_factory(engine2)
    w2 = DurableWorker(
        factory2,
        config=WorkerConfig(
            worker_id="golden-worker-2",
            lease_ttl=60,
            heartbeat_interval=15,
            poll_interval=0.01,
            max_attempts=3,
            staging_root=managed_root,
        ),
        clock=FakeClock(),
        sleeper=FakeSleeper(),
    )
    register_generate_proxy_handler(w2)
    register_scene_detection_handler(w2)

    assert w2.run_once() == 1  # claims the queued proxy job
    assert _job_state(factory2, proxy_result.job_id) == "completed"
    with factory2() as s:
        proxy_art_id = s.scalar(
            select(ArtifactOwner.artifact_id).where(
                ArtifactOwner.owner_type == "video_item",
                ArtifactOwner.owner_id == video_item.id,
                ArtifactOwner.purpose == ARTIFACT_PURPOSE_PROXY,
            )
        )
    assert proxy_art_id is not None

    # Phase 3: scene detection submitted after restart completes on w2.
    scene_result = _submit_scene_detection(
        factory2,
        ws,
        video_item,
        source_artifact_id,
        managed_root,
        proxy_artifact_id=str(proxy_art_id),
    )
    assert w2.run_once() == 1
    assert _job_state(factory2, scene_result.job_id) == "completed"

    # Exactly one effect set for every logical run — no duplicates.
    rows = _scene_rows(factory2, video_item.id)
    assert len(rows) == 2
    arts = _ready_video_artifacts(factory2, ws.id)
    assert len(arts) == 2
    with factory2() as s:
        proxy_attempts = JobRepository(s).list_attempts(proxy_result.job_id)
        scene_attempts = JobRepository(s).list_attempts(scene_result.job_id)
    assert len(proxy_attempts) == 1
    assert len(scene_attempts) == 1
    assert _staging_files(managed_root) == []
