"""MF-END-17 finalize — writes commands.jsonl (append-only, UTC from artifact mtimes) and
evidence_manifest.json (sha256 of every evidence file; the manifest itself is excluded).

Run LAST, after the post-commit final gate.

Usage: python -B tools/w17_finalize.py
"""

from __future__ import annotations

import hashlib
import json
import time
from pathlib import Path

RUN_ROOT = Path(__file__).resolve().parent.parent
RAW = RUN_ROOT / "raw"

MANIFEST_NAME = "evidence_manifest.json"
LEDGER_NAME = "commands.jsonl"


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def utc_of(path: Path) -> str | None:
    if not path.exists():
        return None
    return time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime(path.stat().st_mtime))


ROWS = [
    ("header", None, {"task": "MF-END-17", "note": "append-only evidence ledger; each row's utc is the UTC mtime of the artifact it wrote (measured)"}),
    ("python -B tools/w17_guard.py before", "raw/write_set_guard_before.json", {"note": "4 write-set entries captured; 2 new + 1 patch (preimage 629f7a14, 7360 B) + test new"}),
    ("python -m pytest tests/product_delivery tests/product_p1/public_chain -q -p no:cacheprovider (baseline @base)", "raw/baseline_wave.stdout.txt", {"note": "310 passed, 3 skipped"}),
    ("python -B tools/w17_hash_models.py", "raw/model_full_hashes.json", {"note": "3 full sha256 (~46 GB) + area invariance; ok=true"}),
    ("python -B tools/w17_hash_models.py (area scan)", "raw/model_area_scan.json", {"note": "12/12 files unchanged vs P0; scail/sam family scan = 0 hits"}),
    ("python -B tools/w17_probe_scail.py", "raw/scail_probe.json", {"note": "BLOCKED_NO_WEIGHTS; semantics from installed node source"}),
    ("python -B tools/w17_hf_probe.py", "raw/hf_provenance_probe.json", {"note": "3/3 files @617a7633, apache-2.0, LFS oid == measured sha256"}),
    ("python -B tools/w17_verify.py", "raw/evidence_reverify.json", {"note": "PASS 22/22 MATCH, cross-links equal, graph ok on 2 dumps, 6/6 ports refused"}),
    ("python -B tools/w17_build.py", "raw/build_record.json", {"note": "wrote controlled_shot_v1.json + .manifest.json (CRLF, deterministic)"}),
    ("python -B tools/w17_build.py --verify", "raw/determinism_check.json", {"note": "rebuild byte-identical (MATCH x2)"}),
    ("python -B tools/w17_patch_profiles.py", "raw/profile_patch_record.json", {"note": "bounded preimage 629f7a14 -> 7ff130c5, +968 B, invariants ok"}),
    ("python -m pytest tests/product_delivery/test_mf_end_17.py -q (focused)", "raw/focused.stdout.txt", {"note": "40 passed"}),
    ("ruff check + py_compile + JSON loads (static)", "raw/static.stdout.txt", {"note": "after one E501 fix pass (12 lines) via tools/w17_fix_lint.py"}),
    ("python -B tools/w17_guard.py verify", "raw/write_set_guard_post.json", {"note": "CLEAN, 0 failures, 0 outside allowlist, protected 0 drift"}),
    ("python -m pytest tests/product_delivery tests/product_p1/public_chain -q -p no:cacheprovider (ONE broad wave)", "raw/broad_wave.stdout.txt", {"note": "350 passed, 3 skipped (baseline+40)"}),
    ("python -B tools/w17_final_gate.py pre", "raw/final_gate_pre.json", {"note": "18/18 PASS"}),
    ("git add <4 allowlist paths> && git commit", None, {"note": "commit 29bc006cc541218c09db80fbdf8bb8f7389a392f (parent a2d7cc8); 4 files +1348/-1; no push; pre-existing git repack noise disclosed in REPORT §header"}),
    ("python -B tools/w17_final_gate.py post", "raw/final_gate_post.json", {"note": "18/18 PASS (HEAD^==base, porcelain empty)"}),
    ("python -B tools/w17_final_verification.py", "raw/final_verification.json", {"note": "Step-5 verification of the frozen state: write-set shas vs results.json, commit chain, manifest re-hash (this file is excluded from the manifest and regenerated by re-running the tool)"}),
    ("python -B tools/w17_finalize.py", "commands.jsonl + evidence_manifest.json", {"note": "this ledger + the evidence hash manifest (written last)"}),
]


def main() -> int:
    lines = []
    for cmd, artifact, extra in ROWS:
        row = {"cmd": cmd}
        if artifact:
            row["artifact"] = artifact
        row.update(extra)
        if artifact:
            row["utc"] = utc_of(RUN_ROOT / artifact)
        lines.append(json.dumps(row, ensure_ascii=False))
    (RUN_ROOT / LEDGER_NAME).write_text("\r\n".join(lines) + "\r\n", encoding="utf-8")

    files = []
    excluded = []
    for p in sorted(RUN_ROOT.rglob("*")):
        if not p.is_file():
            continue
        rel = p.relative_to(RUN_ROOT).as_posix()
        if rel == MANIFEST_NAME:
            excluded.append({"path": rel, "why": "the manifest itself (self-exclusion keeps the manifest re-generatable)"})
            continue
        if rel == "raw/final_verification.json":
            excluded.append({"path": rel, "why": "verification output produced by tools/w17_final_verification.py after this manifest; re-run the tool to reproduce"})
            continue
        if "__pycache__" in rel or rel.endswith(".pyc"):
            excluded.append({"path": rel, "why": "tool cache"})
            continue
        files.append({"path": rel, "bytes": p.stat().st_size, "sha256": sha256_file(p),
                      "mtime_utc": utc_of(p)})
    manifest = {
        "artifact": MANIFEST_NAME,
        "task": "MF-END-17",
        "at_utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "root": str(RUN_ROOT),
        "file_count": len(files),
        "total_bytes": sum(f["bytes"] for f in files),
        "excluded": excluded,
        "note": "sha256 of every evidence file; re-hash any listed path and compare to re-derive the freeze",
        "files": files,
    }
    (RUN_ROOT / MANIFEST_NAME).write_text(json.dumps(manifest, indent=1, ensure_ascii=False), encoding="utf-8")
    print(json.dumps({"ledger_rows": len(lines), "files": len(files),
                      "total_bytes": manifest["total_bytes"], "excluded": len(excluded)}))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
