"""Persistence bootstrap for MotionForge 2D (SQLAlchemy 2.x + SQLite)."""

from app.persistence.artifacts import (
    ArtifactWriteError,
    ManagedPathError,
    ManagedRoot,
    RestoreResult,
    TrashManifest,
    TrashMoveResult,
    hash_file,
    is_within,
    normalize_managed_path,
)
from app.persistence.engine import (
    BUSY_TIMEOUT_MS,
    FOREIGN_KEYS_PRAGMA,
    create_engine_for_path,
    create_session_factory,
)
from app.persistence.legacy_import import (
    BACKUP_MANIFEST_NAME,
    BackupEntry,
    BackupManifest,
    ImportResult,
    LegacyImporter,
    LegacyImportError,
    LegacyImportRefused,
    LegacyImportRefusedError,
    backup_manifest_name,
    confirmation_token,
)
from app.persistence.legacy_preview import (
    BLOCKER,
    INFO,
    WARNING,
    LegacyPreview,
    LegacyPreviewer,
    LegacyPreviewError,
    PathCheck,
    PathIssue,
    PreviewIssue,
)
from app.persistence.revision import (
    SCHEMA_REVISION_REFUSED_MESSAGE,
    assert_schema_revision_supported,
    database_schema_revision,
    max_supported_schema_revision,
)

__all__ = [
    "BACKUP_MANIFEST_NAME",
    "BLOCKER",
    "BUSY_TIMEOUT_MS",
    "FOREIGN_KEYS_PRAGMA",
    "INFO",
    "SCHEMA_REVISION_REFUSED_MESSAGE",
    "WARNING",
    "ArtifactWriteError",
    "BackupEntry",
    "BackupManifest",
    "ImportResult",
    "LegacyImportError",
    "LegacyImportRefused",
    "LegacyImportRefusedError",
    "LegacyImporter",
    "LegacyPreview",
    "LegacyPreviewError",
    "LegacyPreviewer",
    "ManagedPathError",
    "ManagedRoot",
    "PathCheck",
    "PathIssue",
    "PreviewIssue",
    "RestoreResult",
    "TrashManifest",
    "TrashMoveResult",
    "assert_schema_revision_supported",
    "backup_manifest_name",
    "confirmation_token",
    "create_engine_for_path",
    "create_session_factory",
    "database_schema_revision",
    "hash_file",
    "is_within",
    "max_supported_schema_revision",
    "normalize_managed_path",
]
