"""Product-P1 public-chain QA suite (S12-LC3-QA lane, preparation wave).

Owner: S12-LC3-QA.  Allowlisted root: ``tests/product_p1/public_chain/**``.

This package answers ONE question for the Manager: *what of the full public
product chain is provably prepared now, what is runnable now against this
tree, and what exactly must wait for the QC/UI freeze.*

Two labels, never mixed:

* ``RUNNABLE_NOW``  — the case executes on THIS tree, today, with no frozen
  candidate pin, no product source change and **no seeded QC/product state**.
* ``PENDING_FROZEN_CANDIDATE`` — the case is written against the contract but
  its execution needs the frozen integrated candidate (QC + UI writers
  terminal).  It is skipped with that exact reason; it never passes by
  default and never stubs the product.

Media discipline (packet §2): fixtures generated by this suite and real
MP4/audio evidence are SEPARATELY LABELLED.  Nothing here is presented as
real product media evidence; the only network exception is the loopback
TestClient + per-test isolated DB from ``tests/conftest.py``.
"""

from __future__ import annotations

__all__ = ["public_chain_cases"]
