"""MF-END-09 — durable reference-asset generation jobs (graph G1 → managed library).

One outcome: an API/UI submit registers ONE durable Job intent; the existing
``DurableWorker`` drives it through the shared ``ComfyShotEngine`` authority
(MF-END-18: epoch/lease/gate/reservation, one POST per attempt) over the
reference-asset image graph (MF-END-08: ``app/media_workflows/reference_asset_v1.json``),
and the generated bytes are saved back into the SAME draft pack version as a
ready managed artifact + ``character_asset`` row through the existing authored
reference-artwork ingest (MF-END-03).  The pack is never published here.

Design facts (all fail-closed, each with a typed refusal code):

* **submit is an intent** — :func:`submit_reference_asset_job` validates the
  live draft version, resolves the source identity reference and the target
  ``<view>@<role>`` key, computes the content key, and inserts a durable Job.
  It performs NO engine work and writes no library bytes.
* **content identity** — the cache key is sha256 over
  ``workspace/character/version/reference key/source sha/style/graph file
  sha/prompt/seed/canvas/...`` (:func:`reference_asset_content_key`).  Missing
  one view therefore produces a key for exactly that view; other views are
  never touched (they are not part of any submitted manifest).
* **durable receipt** — ``<managed_root>/reference_asset_jobs/<key>.json``
  records ``submitted`` BEFORE the engine POST and ``completed`` only after the
  library ingest committed.  A retry that finds a ``completed`` receipt replays
  the staged artifact with **0 engine POST**; a retry that finds a non-terminal
  receipt re-drives the engine with the RECORDED attempt identity (the package's
  durable replay: 0 POST when the attempt is terminal on the server) and
  otherwise refuses typed — a second blind POST is never sent.
* **no fixture fallback** — when the pinned engine dependency or the engine
  itself is unavailable, the run refuses typed (``engine_unavailable``); there
  is no synthetic image, no placeholder row, no "test mode" in the production
  path.  Tests inject a fake HTTP transport at the process boundary only.
* **draft-only writes** — the version is re-checked inside the handler and again
  inside the ingest; a published/archived version refuses every write, and the
  target key must be absent (a present key is somebody else's asset).

Disclosed conventions (open points for the reviewer):

* ``<managed_root>/media_engine/comfy_shot_engine/runtime/input`` is the
  app-side staged-input directory, matching MF-END-08's isolation recipe (own
  base-directory with ``input/output/temp/user`` under the managed root).  The
  server launch itself stays outside this module.
* The engine binding is built from the frozen DTO example
  (:data:`app.schemas.shot_reskin.FROZEN_EXAMPLES`) with explicit overrides
  (identity/source/cast/graph/output contract) because the accepted contract
  shape is video-shot shaped; every overridden field is listed here.
"""

from __future__ import annotations

import contextlib
import hashlib
import json
import os
import uuid
from collections.abc import Callable
from dataclasses import dataclass
from enum import Enum
from pathlib import Path
from typing import Any

from app.persistence.artifacts import ManagedRoot, hash_file
from app.persistence.characters import (
    CharacterRepository,
    PackVersionImmutableError,
    PackVersionNotFoundError,
)
from app.persistence.jobs import TERMINAL_STATES, IdempotencyKeyInUse, JobError, parse_json
from app.persistence.models import Job
from app.schemas import shot_reskin as sr
from app.workflow import character_reference_ingest
from app.workflow.durable_worker import WorkerContext

__all__ = [
    "DEFAULT_SOURCE_REFERENCE_KEY",
    "JOB_TYPE_REFERENCE_ASSET",
    "ReferenceAssetJobError",
    "ReferenceAssetPlan",
    "ReferenceAssetRefusalCode",
    "build_reference_asset_graph",
    "content_key_for",
    "default_comfy_engine",
    "load_graph_documents",
    "read_receipt",
    "reference_asset_content_key",
    "reference_asset_plan",
    "register_reference_asset_handler",
    "resubmit_reference_asset_job",
    "run_reference_asset_job",
    "stage_reference_input",
    "submit_reference_asset_job",
    "validate_reference_asset_outputs",
]

#: Durable job type registered on the existing worker/JobService.
JOB_TYPE_REFERENCE_ASSET = "reference_asset"

#: Receipt schema + states (append-only JSON beside the managed artifacts).
RECEIPT_SCHEMA = "mf.end09.reference_asset.receipt/1"
RECEIPT_DIR = "reference_asset_jobs"
RECEIPT_SUBMITTED = "submitted"
RECEIPT_COMPLETED = "completed"
RECEIPT_FAILED = "failed"
RECEIPT_CANCELLED = "cancelled"

#: Frozen graph (MF-END-08) + its pinned manifest; both are relative to the repo root.
GRAPH_FILE_REL = "app/media_workflows/reference_asset_v1.json"
GRAPH_MANIFEST_REL = "app/media_workflows/reference_asset_v1.manifest.json"
GRAPH_SCHEMA_VERSION = "mf.reference_asset.graph.v1"

#: The SaveImage node whose bytes are the asset (declared terminal output).
SAVE_NODE_ID = "SAVE"

#: Staged-input convention (see module docstring).
ENGINE_STATE_REL = ("media_engine", "comfy_shot_engine")

#: Reference-pack convention: ``front@character`` is the canonical authored
#: identity reference (MF-END-03/04/08); used when the caller omits a source.
DEFAULT_SOURCE_REFERENCE_KEY = "front@character"

#: Distilled FLUX.2 klein profile pinned by the frozen graph document.
CANVAS_WIDTH = 1024
CANVAS_HEIGHT = 1024
REF_LONGER_SIDE = 768
NEUTRAL_RGB_INT = 0x808080
STEPS = 4
CFG = 1
SEED_CEILING = 1 << 63

#: Submit defaults.
DEFAULT_MAX_ATTEMPTS = 1


class ReferenceAssetRefusalCode(str, Enum):
    """Typed refusals; one code per cause, never a generic error."""

    REQUEST_INVALID = "mf_end09_request_invalid"
    VERSION_NOT_FOUND = "mf_end09_version_not_found"
    VERSION_NOT_DRAFT = "mf_end09_version_not_draft"
    TARGET_KEY_PRESENT = "mf_end09_target_key_present"
    TARGET_KEY_INVALID = "mf_end09_target_key_invalid"
    SOURCE_REFERENCE_MISSING = "mf_end09_source_reference_missing"
    SOURCE_HASH_MISMATCH = "mf_end09_source_hash_mismatch"
    REFERENCE_SET_INSUFFICIENT = "mf_end09_reference_set_insufficient"
    VIEW_PROMPT_REFUSED = "mf_end09_view_prompt_refused"
    GRAPH_PIN_MISMATCH = "mf_end09_graph_pin_mismatch"
    CONTENT_KEY_MISMATCH = "mf_end09_content_key_mismatch"
    RECEIPT_IN_DOUBT = "mf_end09_receipt_in_doubt"
    RECEIPT_INCOMPLETE = "mf_end09_receipt_incomplete"
    ARTIFACT_MISSING = "mf_end09_artifact_missing"
    ARTIFACT_HASH_MISMATCH = "mf_end09_artifact_hash_mismatch"
    ENGINE_REFUSED = "mf_end09_engine_refused"
    INGEST_REFUSED = "mf_end09_ingest_refused"
    JOB_NOT_FOUND = "mf_end09_job_not_found"
    JOB_NOT_RETRYABLE = "mf_end09_job_not_retryable"
    IDEMPOTENCY_CONFLICT = "mf_end09_idempotency_conflict"


class ReferenceAssetJobError(Exception):  # noqa: N818 — mirrors the refusal naming family
    """Typed refusal raised by the reference-asset job module."""

    def __init__(
        self,
        code: ReferenceAssetRefusalCode,
        detail: str,
        *,
        details: dict[str, Any] | None = None,
        retryable: bool = False,
    ) -> None:
        super().__init__(f"{code.value}: {detail}")
        self.code = code
        self.detail = detail
        self.details = dict(details or {})
        self.retryable = retryable

    def as_dict(self) -> dict[str, Any]:
        out: dict[str, Any] = {"code": self.code.value, "detail": self.detail}
        if self.details:
            out["details"] = dict(self.details)
        if self.retryable:
            out["retryable"] = True
        return out


# ── small helpers ────────────────────────────────────────────────────────────


def _sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[2]


def _canonical_json(payload: Any) -> bytes:
    return json.dumps(payload, sort_keys=True, separators=(",", ":"), ensure_ascii=True).encode(
        "utf-8"
    )


def _manifest_managed_root(manifest: dict[str, Any]) -> Path:
    raw = str(manifest.get("managed_root") or "").strip()
    if not raw:
        raise ReferenceAssetJobError(
            ReferenceAssetRefusalCode.REQUEST_INVALID, "input_manifest carries no managed_root"
        )
    root = Path(raw)
    if not root.is_absolute():
        raise ReferenceAssetJobError(
            ReferenceAssetRefusalCode.REQUEST_INVALID, "managed_root must be absolute"
        )
    return root


def load_graph_documents() -> tuple[dict[str, Any], dict[str, Any]]:
    """Load the frozen graph document + manifest, pinning the file sha256.

    Returns ``(graph_document, manifest)`` where the graph file sha256 equals
    ``manifest["workflow"]["graph_file_sha256"]`` — any other bytes refuse.
    """
    root = _repo_root()
    graph_path = root / GRAPH_FILE_REL
    manifest_path = root / GRAPH_MANIFEST_REL
    try:
        graph_bytes = graph_path.read_bytes()
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    except (OSError, ValueError) as exc:
        raise ReferenceAssetJobError(
            ReferenceAssetRefusalCode.GRAPH_PIN_MISMATCH,
            f"frozen graph document unreadable: {type(exc).__name__}:{exc}",
            details={"graph_file": GRAPH_FILE_REL},
        ) from exc
    declared = str(((manifest or {}).get("workflow") or {}).get("graph_file_sha256") or "")
    actual = _sha256_bytes(graph_bytes)
    if not declared or declared != actual:
        raise ReferenceAssetJobError(
            ReferenceAssetRefusalCode.GRAPH_PIN_MISMATCH,
            "graph file sha256 differs from the frozen manifest pin",
            details={"declared": declared, "actual": actual},
        )
    try:
        document = json.loads(graph_bytes.decode("utf-8"))
    except ValueError as exc:
        raise ReferenceAssetJobError(
            ReferenceAssetRefusalCode.GRAPH_PIN_MISMATCH, f"graph document is not JSON: {exc}"
        ) from exc
    if str(document.get("schema_version")) != GRAPH_SCHEMA_VERSION:
        raise ReferenceAssetJobError(
            ReferenceAssetRefusalCode.GRAPH_PIN_MISMATCH,
            "graph document declares an unknown schema_version",
            details={"schema_version": document.get("schema_version")},
        )
    if not isinstance(document.get("graph"), dict) or not document["graph"]:
        raise ReferenceAssetJobError(
            ReferenceAssetRefusalCode.GRAPH_PIN_MISMATCH,
            "graph document carries no API-format graph object",
        )
    return document, manifest


def parse_target_key(reference_key: str) -> tuple[str, str]:
    """Validate ``<view>@<role>`` with the FROZEN MF-END-03 grammar."""
    try:
        view, role = character_reference_ingest.validate_reference_key(reference_key)
    except Exception as exc:
        raise ReferenceAssetJobError(
            ReferenceAssetRefusalCode.TARGET_KEY_INVALID,
            f"reference key refused: {exc}",
            details={"reference_key": reference_key},
        ) from exc
    return view, role


def _seed_for(version_id: str, reference_key: str, source_sha256: str) -> int:
    digest = hashlib.sha256(f"{version_id}:{reference_key}:{source_sha256}".encode())
    return int(digest.hexdigest()[:15], 16) % SEED_CEILING


def _config_hash(
    *,
    canvas_width: int,
    canvas_height: int,
    ref_longer_side: int,
    neutral_rgb_int: int,
    seed: int,
    filename_prefix: str,
) -> str:
    return "sha256:" + _sha256_bytes(
        _canonical_json(
            {
                "canvas": [canvas_width, canvas_height],
                "cfg": CFG,
                "filename_prefix": filename_prefix,
                "neutral_rgb_int": neutral_rgb_int,
                "ref_longer_side": ref_longer_side,
                "seed": seed,
                "steps": STEPS,
            }
        )
    )


def content_key_for(fields: dict[str, Any]) -> str:
    """Canonical content key over the identity/view/style/graph-fingerprint fields."""
    return "sha256:" + _sha256_bytes(_canonical_json(fields))


# ── the plan (pure; derived from the durable manifest) ───────────────────────


@dataclass(frozen=True)
class ReferenceAssetPlan:
    """Everything the run needs, recomputed from the durable manifest."""

    workspace_id: str
    character_id: str
    version_id: str
    reference_key: str
    view: str
    role: str
    source_reference_key: str
    source_artifact_id: str
    source_sha256: str
    source_size_bytes: int
    style_version: str | None
    view_prompt: str
    seed: int
    canvas_width: int
    canvas_height: int
    ref_longer_side: int
    neutral_rgb_int: int
    filename_prefix: str
    output_filename: str
    graph_file_sha256: str
    graph_config_hash: str
    graph: dict[str, Any]
    content_key: str
    graph_object: dict[str, Any]
    graph_models: tuple[dict[str, Any], ...]


def build_reference_asset_graph(
    template_graph: dict[str, Any],
    *,
    ref_filename: str,
    prompt: str,
    seed: int,
    filename_prefix: str,
    canvas_width: int = CANVAS_WIDTH,
    canvas_height: int = CANVAS_HEIGHT,
    ref_longer_side: int = REF_LONGER_SIDE,
    neutral_rgb_int: int = NEUTRAL_RGB_INT,
) -> dict[str, Any]:
    """Deep-copy the frozen graph and apply the documented parameter overrides."""
    if not ref_filename or Path(ref_filename).name != ref_filename:
        raise ReferenceAssetJobError(
            ReferenceAssetRefusalCode.REQUEST_INVALID,
            "ref_filename must be a bare file name (no directories)",
            details={"ref_filename": ref_filename},
        )
    if not ref_filename.lower().endswith(".png"):
        raise ReferenceAssetJobError(
            ReferenceAssetRefusalCode.REQUEST_INVALID, "ref_filename must be a PNG file name"
        )
    if not prompt.strip():
        raise ReferenceAssetJobError(
            ReferenceAssetRefusalCode.VIEW_PROMPT_REFUSED, "view prompt must be non-empty"
        )
    if not 0 <= int(seed) < SEED_CEILING:
        raise ReferenceAssetJobError(
            ReferenceAssetRefusalCode.REQUEST_INVALID, "seed must be within [0, 2**63)"
        )
    if canvas_width % 16 or canvas_height % 16 or not (
        16 <= canvas_width <= 16384 and 16 <= canvas_height <= 16384
    ):
        raise ReferenceAssetJobError(
            ReferenceAssetRefusalCode.REQUEST_INVALID,
            "canvas dimensions must be 16..16384 and divisible by 16",
            details={"canvas": [canvas_width, canvas_height]},
        )
    if not 16 <= int(ref_longer_side) <= 4096:
        raise ReferenceAssetJobError(
            ReferenceAssetRefusalCode.REQUEST_INVALID, "ref_longer_side must be within 16..4096"
        )
    if not 0 <= int(neutral_rgb_int) <= 0xFFFFFF:
        raise ReferenceAssetJobError(
            ReferenceAssetRefusalCode.REQUEST_INVALID, "neutral_rgb_int must be within 0..0xFFFFFF"
        )
    graph = json.loads(json.dumps(template_graph))
    overrides: tuple[tuple[str, str, Any], ...] = (
        ("REF_LOAD", "image", ref_filename),
        ("PROMPT", "text", prompt),
        ("REF_RESIZE", "resize_type.longer_size", int(ref_longer_side)),
        ("REF_BG", "color", int(neutral_rgb_int)),
        ("NOISE", "noise_seed", int(seed)),
        ("LATENT", "width", int(canvas_width)),
        ("LATENT", "height", int(canvas_height)),
        ("SIGMAS", "steps", STEPS),
        ("SIGMAS", "width", int(canvas_width)),
        ("SIGMAS", "height", int(canvas_height)),
        ("GUIDER", "cfg", CFG),
        ("SAVE", "filename_prefix", filename_prefix),
    )
    for node_id, input_name, value in overrides:
        node = graph.get(node_id)
        if not isinstance(node, dict) or not isinstance(node.get("inputs"), dict):
            raise ReferenceAssetJobError(
                ReferenceAssetRefusalCode.GRAPH_PIN_MISMATCH,
                "frozen graph is missing a node the parameter table pins",
                details={"node": node_id},
            )
        node["inputs"][input_name] = value
    return graph


def reference_asset_plan(manifest: dict[str, Any]) -> ReferenceAssetPlan:
    """Recompute the plan (and content key) from a durable input manifest.

    Every field is validated here; a manifest whose recomputed content key
    differs from the recorded one refuses (``content_key_mismatch``).
    """
    required = (
        "workspace_id",
        "character_id",
        "version_id",
        "reference_key",
        "source_reference_key",
        "source_artifact_id",
        "source_sha256",
        "source_size_bytes",
        "view_prompt",
    )
    missing = [name for name in required if not str(manifest.get(name) or "").strip()]
    if missing:
        raise ReferenceAssetJobError(
            ReferenceAssetRefusalCode.REQUEST_INVALID,
            "input_manifest is missing required fields",
            details={"missing": missing},
        )
    reference_key = str(manifest["reference_key"])
    source_reference_key = str(manifest["source_reference_key"])
    view, role = parse_target_key(reference_key)
    if source_reference_key == reference_key:
        raise ReferenceAssetJobError(
            ReferenceAssetRefusalCode.REQUEST_INVALID,
            "source and target reference keys are identical",
            details={"reference_key": reference_key},
        )
    prompt = str(manifest["view_prompt"]).strip()
    if view.lower() not in prompt.lower():
        raise ReferenceAssetJobError(
            ReferenceAssetRefusalCode.VIEW_PROMPT_REFUSED,
            "view prompt must name the target view",
            details={"view": view},
        )
    document, _manifest = load_graph_documents()
    graph_file_sha256 = str(
        (_manifest.get("workflow") or {}).get("graph_file_sha256") or ""
    )
    seed = manifest.get("seed")
    if seed is None:
        seed = _seed_for(str(manifest["version_id"]), reference_key, str(manifest["source_sha256"]))
    seed = int(seed)
    canvas_width = int(manifest.get("canvas_width", CANVAS_WIDTH))
    canvas_height = int(manifest.get("canvas_height", CANVAS_HEIGHT))
    ref_longer_side = int(manifest.get("ref_longer_side", REF_LONGER_SIDE))
    neutral_rgb_int = int(manifest.get("neutral_rgb_int", NEUTRAL_RGB_INT))
    filename_prefix = str(
        manifest.get("filename_prefix") or f"mf_reference_asset_v1/{view}_{role}"
    )
    output_filename = str(
        manifest.get("output_filename") or f"end09_{view}_{role}_{str(seed)[:10]}.png"
    )
    staged_filename = f"end09_ref_{str(manifest['source_sha256'])[:16]}.png"
    graph = build_reference_asset_graph(
        document["graph"],
        ref_filename=staged_filename,
        prompt=prompt,
        seed=seed,
        filename_prefix=filename_prefix,
        canvas_width=canvas_width,
        canvas_height=canvas_height,
        ref_longer_side=ref_longer_side,
        neutral_rgb_int=neutral_rgb_int,
    )
    style_version = manifest.get("style_version")
    graph_config_hash = _config_hash(
        canvas_width=canvas_width,
        canvas_height=canvas_height,
        ref_longer_side=ref_longer_side,
        neutral_rgb_int=neutral_rgb_int,
        seed=seed,
        filename_prefix=filename_prefix,
    )
    fields = {
        "schema": RECEIPT_SCHEMA,
        "workspace_id": str(manifest["workspace_id"]),
        "character_id": str(manifest["character_id"]),
        "version_id": str(manifest["version_id"]),
        "reference_key": reference_key,
        "source_reference_key": source_reference_key,
        "source_sha256": str(manifest["source_sha256"]),
        "style_version": None if style_version is None else str(style_version),
        "graph_file_sha256": graph_file_sha256,
        "graph_config_hash": graph_config_hash,
        "view_prompt_sha256": _sha256_bytes(prompt.encode("utf-8")),
    }
    key = reference_asset_content_key(fields)
    recorded = str(manifest.get("content_key") or "")
    if recorded and recorded != key:
        raise ReferenceAssetJobError(
            ReferenceAssetRefusalCode.CONTENT_KEY_MISMATCH,
            "manifest content key does not match the recomputed identity",
            details={"recorded": recorded, "recomputed": key},
        )
    return ReferenceAssetPlan(
        workspace_id=str(manifest["workspace_id"]),
        character_id=str(manifest["character_id"]),
        version_id=str(manifest["version_id"]),
        reference_key=reference_key,
        view=view,
        role=role,
        source_reference_key=source_reference_key,
        source_artifact_id=str(manifest["source_artifact_id"]),
        source_sha256=str(manifest["source_sha256"]),
        source_size_bytes=int(manifest["source_size_bytes"]),
        style_version=None if style_version is None else str(style_version),
        view_prompt=prompt,
        seed=seed,
        canvas_width=canvas_width,
        canvas_height=canvas_height,
        ref_longer_side=ref_longer_side,
        neutral_rgb_int=neutral_rgb_int,
        filename_prefix=filename_prefix,
        output_filename=output_filename,
        graph_file_sha256=graph_file_sha256,
        graph_config_hash=graph_config_hash,
        graph=graph,
        content_key=key,
        graph_object=document,
        graph_models=tuple(
            entry for entry in (_manifest.get("models") or []) if isinstance(entry, dict)
        ),
    )


def reference_asset_content_key(fields: dict[str, Any]) -> str:
    """Canonical content key for the identity/view/style/graph fingerprint."""
    return content_key_for(dict(fields))


# ── receipts (durable, beside the managed artifacts) ─────────────────────────


def receipt_relpath(content_key: str) -> str:
    digest = content_key.split(":", 1)[-1]
    return f"{RECEIPT_DIR}/{digest[:2]}/{digest}.json"


def receipt_path(managed_root: Path, content_key: str) -> Path:
    rel = receipt_relpath(content_key)
    return ManagedRoot(managed_root).resolve(rel)


def read_receipt(managed_root: Path, content_key: str) -> dict[str, Any] | None:
    path = receipt_path(managed_root, content_key)
    if not path.is_file():
        return None
    try:
        payload = parse_json(path.read_text(encoding="utf-8"), None)
    except OSError as exc:
        raise ReferenceAssetJobError(
            ReferenceAssetRefusalCode.RECEIPT_INCOMPLETE,
            f"receipt unreadable: {type(exc).__name__}",
            details={"receipt": receipt_relpath(content_key)},
        ) from exc
    if not isinstance(payload, dict) or payload.get("schema") != RECEIPT_SCHEMA:
        raise ReferenceAssetJobError(
            ReferenceAssetRefusalCode.RECEIPT_INCOMPLETE,
            "receipt does not declare the expected schema",
            details={"receipt": receipt_relpath(content_key)},
        )
    return payload


def write_receipt(managed_root: Path, receipt: dict[str, Any]) -> Path:
    """Atomically write the receipt; never downgrade a completed one."""
    content_key = str(receipt.get("content_key") or "")
    if not content_key:
        raise ReferenceAssetJobError(
            ReferenceAssetRefusalCode.RECEIPT_INCOMPLETE, "receipt carries no content_key"
        )
    payload = dict(receipt)
    payload["schema"] = RECEIPT_SCHEMA
    path = receipt_path(managed_root, content_key)
    existing = read_receipt(managed_root, content_key)
    if (
        existing is not None
        and existing.get("status") == RECEIPT_COMPLETED
        and payload.get("status") != RECEIPT_COMPLETED
    ):
        raise ReferenceAssetJobError(
            ReferenceAssetRefusalCode.RECEIPT_INCOMPLETE,
            "refusing to downgrade a completed receipt",
            details={"receipt": receipt_relpath(content_key)},
        )
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_name(path.name + f".tmp{uuid.uuid4().hex[:8]}")
    tmp.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    os.replace(tmp, path)
    return path


def _update_receipt(
    managed_root: Path, content_key: str, *, status: str, patch: dict[str, Any] | None = None
) -> dict[str, Any]:
    current = read_receipt(managed_root, content_key)
    if current is None:
        raise ReferenceAssetJobError(
            ReferenceAssetRefusalCode.RECEIPT_INCOMPLETE, "receipt is not on disk"
        )
    current["status"] = status
    if patch:
        current.update(patch)
    write_receipt(managed_root, current)
    return current


# ── staged input (managed-root contained) ────────────────────────────────────


def runtime_input_dir(managed_root: Path) -> Path:
    """App-side staged-input directory for the isolated Comfy server (see docstring)."""
    rel = "/".join((*ENGINE_STATE_REL, "runtime", "input"))
    return ManagedRoot(managed_root).resolve(rel)


def stage_reference_input(managed_root: Path, plan: ReferenceAssetPlan, data: bytes) -> Path:
    """Write the identity reference bytes into the staged-input directory."""
    actual = _sha256_bytes(data)
    if actual != plan.source_sha256:
        raise ReferenceAssetJobError(
            ReferenceAssetRefusalCode.SOURCE_HASH_MISMATCH,
            "source reference bytes do not match the manifest sha256",
            details={"expected": plan.source_sha256, "actual": actual},
        )
    target = runtime_input_dir(managed_root) / f"end09_ref_{plan.source_sha256[:16]}.png"
    target.parent.mkdir(parents=True, exist_ok=True)
    tmp = target.with_name(target.name + f".tmp{uuid.uuid4().hex[:8]}")
    tmp.write_bytes(data)
    os.replace(tmp, target)
    return target


# ── engine boundary ──────────────────────────────────────────────────────────


def default_comfy_engine(managed_root: Path) -> Any:
    """Production engine: the pinned MF-END-18 wrapper over the real transport."""
    from app.adapters.media_engine.comfy import ComfyShotEngine  # noqa: PLC0415

    return ComfyShotEngine(managed_root=managed_root, owner="motionforge.reference_asset_jobs")


#: Test seam ONLY: the fake HTTP transport is injected here (process boundary),
#: exactly like MF-END-18's rows.  Production always uses ``default_comfy_engine``.
_ENGINE_FACTORY: Callable[[Path], Any] = default_comfy_engine


def _load_pinning() -> Any:
    import importlib  # noqa: PLC0415

    try:
        return importlib.import_module("mf_comfy.pinning")
    except Exception as exc:  # pragma: no cover - exercised via the negative control
        raise ReferenceAssetJobError(
            ReferenceAssetRefusalCode.ENGINE_REFUSED,
            f"pinned engine dependency unavailable: {type(exc).__name__}",
            details={"engine_code": "engine_unavailable"},
            retryable=True,
        ) from exc


def _engine_model_bindings(graph_models: Any) -> tuple[dict[str, Any], list[Any]]:
    models = list(graph_models or [])
    primary: dict[str, Any] = {}
    auxiliary: list[dict[str, Any]] = []
    for entry in models:
        if not isinstance(entry, dict) or not entry.get("sha256"):
            continue
        binding = {
            "model_id": (
                Path(str(entry.get("file") or "")).stem or str(entry.get("role") or "model")
            ),
            "revision": None,
            "file": {"algorithm": "sha256", "scope": "full_file", "value": str(entry["sha256"])},
            "precision": "not_recorded",
            "size_bytes": int(entry.get("bytes") or 0),
        }
        if str(entry.get("role")) == "diffusion_models" and not primary:
            binding["precision"] = "fp8"
            binding["model_id"] = str(entry.get("file") or "model").replace(".safetensors", "")
            primary = binding
        else:
            auxiliary.append(binding)
    return primary, auxiliary


def build_engine_binding(
    plan: ReferenceAssetPlan,
    *,
    attempt_id: str,
    job_id: str,
    workflow_hash: str,
    references: Any = None,
) -> sr.EngineInputBinding:
    """Frozen DTO example + explicit reference-asset overrides (see docstring).

    ``references`` is the ordered list of the role's DISTINCT identity
    references (the manifest source first — it is the one the engine stages,
    because the wrapper feeds ``references[0]`` to the graph).  The pinned
    capability minima are enforced by the DTO; the caller refuses typed before
    the engine when fewer independent references exist than the pin requires.
    """
    base = json.loads(
        json.dumps(sr.FROZEN_EXAMPLES["execution_record_book_p3b"]["input"])
    )
    primary, auxiliary = _engine_model_bindings(plan.graph_models)
    cast_references = list(references or [
        {
            "key": plan.source_reference_key,
            "artifact_id": plan.source_artifact_id,
            "sha256": plan.source_sha256,
            "size_bytes": plan.source_size_bytes,
        }
    ])
    base["capability"] = sr.ENGINE_CAPABILITY_PINS[0]
    base["identity"] = {
        "workspace_id": plan.workspace_id,
        "project_id": f"library:{plan.character_id}",
        "series_id": plan.version_id,
        "video_id": "library",
        "stage": "reference_asset",
        "attempt_id": attempt_id,
        "job_id": job_id,
    }
    base["source"] = {
        "source_artifact_id": plan.source_artifact_id,
        "source_sha256": plan.source_sha256,
        "span": {"start_frame": 0, "end_frame_exclusive": 1},
        "timebase": {
            "fps_num": 1,
            "fps_den": 1,
            "stream_timebase_num": None,
            "stream_timebase_den": None,
            "pts_start_ticks": 0,
            "pts_end_ticks": 1,
            "decoded_frame_count": 1,
        },
        "decoded_frame_count": 1,
    }
    base["cast"] = [
        {
            "role": plan.role,
            "character_id": plan.character_id,
            "pack_version_id": plan.version_id,
            "references": [
                {
                    "key": str(item["key"]),
                    "artifact": {
                        "artifact_id": str(item["artifact_id"]),
                        "kind": "image",
                        "sha256": str(item["sha256"]),
                        "store_relative_path": str(item["key"]),
                        "size_bytes": int(item["size_bytes"]),
                    },
                }
                for item in cast_references
            ],
            "style_version": plan.style_version,
        }
    ]
    base["anchor"] = None
    base["source_window"] = {
        "artifact_id": plan.source_artifact_id,
        "kind": "image",
        "sha256": plan.source_sha256,
        "store_relative_path": str(plan.source_reference_key),
        "size_bytes": plan.source_size_bytes,
    }
    base["graph"] = {
        "workflow_id": "reference_asset_v1",
        "workflow_version": "v1",
        "workflow_hash": workflow_hash,
        "model": primary,
        "nodes": [],
        "config_hash": plan.graph_config_hash,
        "seed": plan.seed,
    }
    base["auxiliary_models"] = auxiliary
    base["output_contract"] = {
        "width": plan.canvas_width,
        "height": plan.canvas_height,
        "fps_num": 1,
        "fps_den": 1,
        "frame_count": 1,
        "container": "png",
        "video_codec": "png",
        "audio": {"mode": "silent"},
        "stream_timebase_num": None,
        "stream_timebase_den": None,
        "publishable_types": ["output"],
    }
    base["budget"] = {
        "resource_class": "gpu_image",
        "max_wall_seconds": 900.0,
        "max_vram_bytes": 12 * 1024 * 1024 * 1024,
        "max_output_bytes": 64 * 1024 * 1024,
    }
    return sr.EngineInputBinding.model_validate(base)


def _drive_engine(
    plan: ReferenceAssetPlan,
    *,
    attempt_id: str,
    job_id: str,
    managed_root: Path,
    replay: bool,
    references: Any = None,
) -> tuple[Any, dict[str, Any]]:
    """One attempt through the shared engine; replay reuses durable evidence."""
    from app.adapters.media_engine.comfy import ComfyEngineRefusal  # noqa: PLC0415

    pinning = _load_pinning()
    workflow_hash = str(pinning.hash_workflow(plan.graph))
    binding = build_engine_binding(
        plan,
        attempt_id=attempt_id,
        job_id=job_id,
        workflow_hash=workflow_hash,
        references=references,
    )
    engine = _ENGINE_FACTORY(managed_root)
    kwargs: dict[str, Any] = {
        "graph": plan.graph,
        "terminal_outputs": {SAVE_NODE_ID: {"kind": "image", "media_type": "image"}},
        "shot_id": f"reference_asset:{plan.reference_key}",
        "params": None,
        "decoded_facts": sr.EngineDecodedFacts(
            decoded_frames=1, first_pts_ticks=0, timebase="1/1", mapping=None
        ),
    }
    try:
        if replay:
            record, info = engine.replay(binding, **kwargs)
        else:
            record = engine.run_shot(binding, **kwargs)
            info = {"replayed": False}
    except ComfyEngineRefusal as exc:
        raise ReferenceAssetJobError(
            ReferenceAssetRefusalCode.ENGINE_REFUSED,
            f"engine refused the attempt: {exc.code.value}",
            details={"engine": exc.as_dict()},
            retryable=bool(getattr(exc, "retryable", False)),
        ) from exc
    finally:
        with contextlib.suppress(Exception):
            engine.close()
    return record, dict(info)


# ── library state (draft-only) ───────────────────────────────────────────────


@dataclass(frozen=True)
class _LibraryState:
    source_path: Path
    source_bytes: bytes
    target_asset_id: str | None
    identity_refs: tuple[dict[str, Any], ...]


def _assert_library_state(
    ctx: WorkerContext, plan: ReferenceAssetPlan, managed_root: Path, receipt: dict[str, Any] | None
) -> _LibraryState:
    if ctx.session_factory is None:
        raise ReferenceAssetJobError(
            ReferenceAssetRefusalCode.REQUEST_INVALID,
            "the worker context carries no session factory; refusing to run unvalidated",
        )
    with ctx.session_factory() as session:
        repo = CharacterRepository(session, storage_root=managed_root)
        try:
            version = repo.get_pack_version(plan.version_id, plan.workspace_id)
        except PackVersionNotFoundError as exc:
            raise ReferenceAssetJobError(
                ReferenceAssetRefusalCode.VERSION_NOT_FOUND,
                "pack version not found in this workspace",
                details={"version_id": plan.version_id},
            ) from exc
        if str(version.status) != "draft":
            raise ReferenceAssetJobError(
                ReferenceAssetRefusalCode.VERSION_NOT_DRAFT,
                "the pack version is not a draft; published versions are immutable",
                details={"status": str(version.status)},
            )
        owned_asset_id = str(((receipt or {}).get("asset") or {}).get("asset_id") or "")
        target_asset_id: str | None = None
        source_asset = None
        present_keys: list[str] = []
        role_refs: list[dict[str, Any]] = []
        for asset in version.assets:
            present_keys.append(str(asset.pose_slot))
            if str(asset.pose_slot) == plan.reference_key:
                if owned_asset_id and str(asset.id) == owned_asset_id:
                    target_asset_id = str(asset.id)
                else:
                    raise ReferenceAssetJobError(
                        ReferenceAssetRefusalCode.TARGET_KEY_PRESENT,
                        "the target reference key already carries an asset",
                        details={"reference_key": plan.reference_key},
                    )
            if str(asset.pose_slot) == plan.source_reference_key:
                source_asset = asset
            view_part, role_part = str(asset.pose_slot).split("@", 1)
            del view_part
            if role_part != plan.role:
                continue
            from app.persistence.models import Artifact  # noqa: PLC0415

            row = session.get(Artifact, str(asset.artifact_id))
            role_refs.append(
                {
                    "key": str(asset.pose_slot),
                    "artifact_id": str(asset.artifact_id),
                    "sha256": str(getattr(row, "sha256", "") or ""),
                    "size_bytes": int(getattr(row, "size_bytes", 0) or 0),
                }
            )
        distinct: list[dict[str, Any]] = []
        seen: set[str] = set()
        for item in sorted(role_refs, key=lambda entry: (entry["key"] != plan.source_reference_key,
                                                         entry["key"])):
            if item["sha256"] and item["sha256"] not in seen:
                seen.add(item["sha256"])
                distinct.append(item)
        refs_min = sr.ENGINE_REFERENCE_MINIMA_PIN[sr.ENGINE_CAPABILITY_PINS[0]][1]
        if len(distinct) < refs_min:
            raise ReferenceAssetJobError(
                ReferenceAssetRefusalCode.REFERENCE_SET_INSUFFICIENT,
                f"capability {sr.ENGINE_CAPABILITY_PINS[0]} requires {refs_min} independent "
                f"reference artifacts for role {plan.role!r}; got {len(distinct)}",
                details={"reference_keys": sorted(present_keys), "distinct": len(distinct)},
            )
        if source_asset is None:
            raise ReferenceAssetJobError(
                ReferenceAssetRefusalCode.SOURCE_REFERENCE_MISSING,
                "the source identity reference is not attached to the version",
                details={
                    "source_reference_key": plan.source_reference_key,
                    "present": present_keys,
                },
            )
        try:
            _asset, path, _mime = repo.resolve_asset_content(
                character_id=plan.character_id,
                version_id=plan.version_id,
                asset_id=str(source_asset.id),
                workspace_id=plan.workspace_id,
            )
        except Exception as exc:  # typed refusals from the repository
            raise ReferenceAssetJobError(
                ReferenceAssetRefusalCode.SOURCE_REFERENCE_MISSING,
                f"source reference bytes are not serviceable: {type(exc).__name__}",
                details={"source_reference_key": plan.source_reference_key},
            ) from exc
        data = Path(path).read_bytes()
    actual = _sha256_bytes(data)
    if actual != plan.source_sha256:
        raise ReferenceAssetJobError(
            ReferenceAssetRefusalCode.SOURCE_HASH_MISMATCH,
            "source reference bytes changed after the intent was registered",
            details={"expected": plan.source_sha256, "actual": actual},
        )
    return _LibraryState(
        source_path=Path(path),
        source_bytes=data,
        target_asset_id=target_asset_id,
        identity_refs=tuple(distinct),
    )


def _ingest_generated_asset(
    ctx: WorkerContext, plan: ReferenceAssetPlan, managed_root: Path, artifact_path: Path
) -> Any:
    """Save the generated bytes through the MF-END-03 managed ingest (draft only)."""
    from app.config import AppConfig  # noqa: PLC0415

    caps = AppConfig()
    written: list[str] = []
    with ctx.session_factory() as session:  # type: ignore[misc]
        repo = CharacterRepository(session, storage_root=managed_root)
        try:
            version = repo.get_pack_version(plan.version_id, plan.workspace_id)
        except PackVersionNotFoundError as exc:
            raise ReferenceAssetJobError(
                ReferenceAssetRefusalCode.VERSION_NOT_FOUND, "pack version vanished mid-run"
            ) from exc
        if str(version.status) != "draft":
            raise ReferenceAssetJobError(
                ReferenceAssetRefusalCode.VERSION_NOT_DRAFT,
                "the pack version became immutable before the asset could be saved",
                details={"status": str(version.status)},
            )
        try:
            with open(artifact_path, "rb") as fh:
                result = character_reference_ingest.ingest_reference_artwork(
                    session=session,
                    storage_root=managed_root,
                    workspace_id=plan.workspace_id,
                    version_id=plan.version_id,
                    reference_key=plan.reference_key,
                    filename=plan.output_filename,
                    stream=fh,
                    max_bytes=caps.max_image_upload_bytes,
                    max_dimension=caps.max_image_dimension,
                    max_pixels=caps.max_image_pixels,
                    purpose="artwork",
                    written=written,
                )
            session.commit()
        except PackVersionImmutableError as exc:
            session.rollback()
            character_reference_ingest.discard_written_files(managed_root, written)
            raise ReferenceAssetJobError(
                ReferenceAssetRefusalCode.VERSION_NOT_DRAFT,
                "the pack version is immutable; the generated asset was discarded",
            ) from exc
        except BaseException as exc:
            session.rollback()
            character_reference_ingest.discard_written_files(managed_root, written)
            if isinstance(exc, ReferenceAssetJobError):
                raise
            raise ReferenceAssetJobError(
                ReferenceAssetRefusalCode.INGEST_REFUSED,
                f"managed ingest refused the generated artwork: {type(exc).__name__}",
                details={"message": str(exc)[:400]},
            ) from exc
    return result


def _image_artifact(record: Any) -> Any:
    for artifact in record.output.artifacts:
        if str(getattr(artifact, "kind", "")) == "image":
            return artifact
    raise ReferenceAssetJobError(
        ReferenceAssetRefusalCode.ARTIFACT_MISSING,
        "the engine completed without an image artifact",
        details={"artifacts": [str(getattr(a, "kind", "")) for a in record.output.artifacts]},
    )


def _verify_artifact(managed_root: Path, artifact: Any) -> Path:
    rel = str(artifact.store_relative_path)
    path = ManagedRoot(managed_root).resolve(rel)
    if not path.is_file():
        raise ReferenceAssetJobError(
            ReferenceAssetRefusalCode.ARTIFACT_MISSING,
            "staged engine artifact is not on disk",
            details={"path": rel},
        )
    actual = hash_file(path)
    if actual != str(artifact.sha256):
        raise ReferenceAssetJobError(
            ReferenceAssetRefusalCode.ARTIFACT_HASH_MISMATCH,
            "staged engine artifact sha256 differs from the receipt",
            details={"path": rel, "expected": str(artifact.sha256), "actual": actual},
        )
    return path


def _result_payload(
    plan: ReferenceAssetPlan,
    *,
    receipt: dict[str, Any],
    generated: bool,
    replayed: bool,
) -> dict[str, Any]:
    asset = dict(receipt.get("asset") or {})
    engine = dict(receipt.get("engine") or {})
    return {
        "content_key": plan.content_key,
        "reference_key": plan.reference_key,
        "view": plan.view,
        "role": plan.role,
        "generated": generated,
        "replayed": replayed,
        "prompt_id": engine.get("prompt_id"),
        "asset_id": asset.get("asset_id"),
        "artifact_id": asset.get("artifact_id"),
        "sha256": asset.get("sha256"),
        "size_bytes": asset.get("size_bytes"),
        "status": str(receipt.get("status")),
        "receipt": receipt_relpath(plan.content_key),
    }


def _finalise(
    ctx: WorkerContext,
    plan: ReferenceAssetPlan,
    managed_root: Path,
    receipt: dict[str, Any],
    artifact: Any,
    *,
    generated: bool,
) -> dict[str, Any]:
    artifact_path = _verify_artifact(managed_root, artifact)
    ctx.progress(70.0, "saving generated artwork into the library")
    if ctx.is_cancelled():
        _update_receipt(managed_root, plan.content_key, status=RECEIPT_CANCELLED)
        return {"cancelled": True, "content_key": plan.content_key, "status": RECEIPT_CANCELLED}
    ingest = _ingest_generated_asset(ctx, plan, managed_root, artifact_path)
    receipt = _update_receipt(
        managed_root,
        plan.content_key,
        status=RECEIPT_COMPLETED,
        patch={
            "engine": {
                "prompt_id": str(receipt.get("engine", {}).get("prompt_id") or ""),
                "workflow_hash": receipt.get("engine", {}).get("workflow_hash"),
                "artifact_store_relative_path": str(artifact.store_relative_path),
                "artifact_sha256": str(artifact.sha256),
                "artifact_size_bytes": int(artifact.size_bytes),
            },
            "asset": {
                "asset_id": str(ingest.asset_id),
                "artifact_id": str(ingest.artifact_id),
                "sha256": str(ingest.sha256),
                "size_bytes": int(ingest.size_bytes),
                "mime_type": str(ingest.mime_type),
                "store_path": str(ingest.asset_id),
            },
        },
    )
    ctx.progress(100.0, "reference asset saved to the library")
    return _result_payload(plan, receipt=receipt, generated=generated, replayed=not generated)


def _generate_fresh(
    ctx: WorkerContext, plan: ReferenceAssetPlan, managed_root: Path, state: _LibraryState
) -> dict[str, Any]:
    ctx.progress(8.0, "staging the identity reference for the engine input dir")
    stage_reference_input(managed_root, plan, state.source_bytes)
    attempt_id = f"{ctx.job_id}:{ctx.attempt}"
    receipt: dict[str, Any] = {
        "content_key": plan.content_key,
        "status": RECEIPT_SUBMITTED,
        "attempt_id": attempt_id,
        "job_id": ctx.job_id,
        "attempt": int(ctx.attempt),
        "reference_key": plan.reference_key,
        "view": plan.view,
        "role": plan.role,
        "version_id": plan.version_id,
        "character_id": plan.character_id,
        "workspace_id": plan.workspace_id,
        "source_sha256": plan.source_sha256,
        "graph_file_sha256": plan.graph_file_sha256,
        "graph_config_hash": plan.graph_config_hash,
        "engine": {},
        "asset": {},
    }
    write_receipt(managed_root, receipt)
    if ctx.is_cancelled():
        _update_receipt(managed_root, plan.content_key, status=RECEIPT_CANCELLED)
        return {"cancelled": True, "content_key": plan.content_key, "status": RECEIPT_CANCELLED}
    ctx.progress(20.0, "submitting the reference-asset graph to the pinned engine")
    record, info = _drive_engine(
        plan,
        attempt_id=attempt_id,
        job_id=ctx.job_id,
        managed_root=managed_root,
        replay=False,
        references=state.identity_refs,
    )
    if str(getattr(record, "outcome", "")) != "completed":
        error = getattr(record, "error", None)
        _update_receipt(
            managed_root,
            plan.content_key,
            status=RECEIPT_FAILED,
            patch={"engine": {"prompt_id": None, "error": str(error)[:400] if error else None}},
        )
        raise ReferenceAssetJobError(
            ReferenceAssetRefusalCode.ENGINE_REFUSED,
            "the engine returned a failed attempt record",
            details={"outcome": str(getattr(record, "outcome", "")), "info": info},
        )
    artifact = _image_artifact(record)
    receipt = read_receipt(managed_root, plan.content_key) or receipt
    receipt["engine"] = {
        "prompt_id": str(record.output.prompt_id),
        "workflow_hash": str(record.output.graph_sha256_server),
        "attempt_id": attempt_id,
    }
    write_receipt(managed_root, receipt)
    return _finalise(ctx, plan, managed_root, receipt, artifact, generated=True)


def _replay_completed(
    ctx: WorkerContext,
    plan: ReferenceAssetPlan,
    managed_root: Path,
    receipt: dict[str, Any],
    state: _LibraryState,
) -> dict[str, Any]:
    """A terminal receipt: reuse the staged artifact, never re-generate."""
    if str(receipt.get("graph_config_hash") or "") != plan.graph_config_hash:
        raise ReferenceAssetJobError(
            ReferenceAssetRefusalCode.CONTENT_KEY_MISMATCH,
            "receipt was produced by a different graph configuration",
        )
    engine = dict(receipt.get("engine") or {})
    rel = str(engine.get("artifact_store_relative_path") or "")
    sha = str(engine.get("artifact_sha256") or "")
    if not rel or not sha:
        raise ReferenceAssetJobError(
            ReferenceAssetRefusalCode.RECEIPT_INCOMPLETE,
            "completed receipt lacks engine artifact facts",
        )
    path = ManagedRoot(managed_root).resolve(rel)
    if not path.is_file():
        raise ReferenceAssetJobError(
            ReferenceAssetRefusalCode.ARTIFACT_MISSING,
            "the staged artifact of the completed receipt is gone",
            details={"path": rel},
        )
    if hash_file(path) != sha:
        raise ReferenceAssetJobError(
            ReferenceAssetRefusalCode.ARTIFACT_HASH_MISMATCH,
            "the staged artifact of the completed receipt no longer matches its sha256",
            details={"path": rel},
        )
    if state.target_asset_id:
        replay = dict(receipt.get("replay") or {})
        replay["count"] = int(replay.get("count") or 0) + 1
        replay["last_job_id"] = ctx.job_id
        receipt = _update_receipt(
            managed_root, plan.content_key, status=RECEIPT_COMPLETED, patch={"replay": replay}
        )
        ctx.progress(100.0, "receipt replay: asset already in the library")
        return _result_payload(plan, receipt=receipt, generated=False, replayed=True)
    # Engine bytes exist but the library row is missing (crash between run and
    # ingest): re-run ONLY the managed ingest — still zero engine POSTs.
    ingest = _ingest_generated_asset(ctx, plan, managed_root, path)
    receipt = _update_receipt(
        managed_root,
        plan.content_key,
        status=RECEIPT_COMPLETED,
        patch={
            "asset": {
                "asset_id": str(ingest.asset_id),
                "artifact_id": str(ingest.artifact_id),
                "sha256": str(ingest.sha256),
                "size_bytes": int(ingest.size_bytes),
                "mime_type": str(ingest.mime_type),
                "store_path": str(ingest.asset_id),
            }
        },
    )
    return _result_payload(plan, receipt=receipt, generated=False, replayed=True)


def _recover_in_doubt(
    ctx: WorkerContext,
    plan: ReferenceAssetPlan,
    managed_root: Path,
    receipt: dict[str, Any],
    state: _LibraryState,
) -> dict[str, Any]:
    """A non-terminal receipt: replay the RECORDED attempt; never a blind POST."""
    recorded_attempt = str(receipt.get("attempt_id") or "")
    if not recorded_attempt:
        raise ReferenceAssetJobError(
            ReferenceAssetRefusalCode.RECEIPT_INCOMPLETE,
            "non-terminal receipt carries no attempt identity",
        )
    try:
        record, info = _drive_engine(
            plan,
            attempt_id=recorded_attempt,
            job_id=str(receipt.get("job_id") or ctx.job_id),
            managed_root=managed_root,
            replay=True,
            references=state.identity_refs,
        )
    except ReferenceAssetJobError as exc:
        raise ReferenceAssetJobError(
            ReferenceAssetRefusalCode.RECEIPT_IN_DOUBT,
            "the previous attempt is not provably terminal; refusing a second submit",
            details={"previous_attempt": recorded_attempt, "engine": exc.as_dict()},
        ) from exc
    if str(getattr(record, "outcome", "")) != "completed":
        raise ReferenceAssetJobError(
            ReferenceAssetRefusalCode.RECEIPT_IN_DOUBT,
            "the replayed attempt is not completed",
            details={"outcome": str(getattr(record, "outcome", "")), "info": info},
        )
    artifact = _image_artifact(record)
    receipt["engine"] = {
        "prompt_id": str(record.output.prompt_id),
        "workflow_hash": str(record.output.graph_sha256_server),
        "attempt_id": recorded_attempt,
        "replayed": True,
    }
    write_receipt(managed_root, receipt)
    return _finalise(ctx, plan, managed_root, receipt, artifact, generated=False)


def run_reference_asset_job(ctx: WorkerContext) -> dict[str, Any]:
    """Durable step handler: generate ONE missing view and save it to the library."""
    manifest = dict(ctx.input_manifest)
    managed_root = _manifest_managed_root(manifest)
    plan = reference_asset_plan(manifest)
    ctx.progress(2.0, "reference-asset plan resolved from the durable manifest")
    receipt = read_receipt(managed_root, plan.content_key)
    state = _assert_library_state(ctx, plan, managed_root, receipt)
    if receipt is None:
        return _generate_fresh(ctx, plan, managed_root, state)
    status = str(receipt.get("status") or "")
    if status == RECEIPT_COMPLETED:
        return _replay_completed(ctx, plan, managed_root, receipt, state)
    if status == RECEIPT_CANCELLED:
        _update_receipt(managed_root, plan.content_key, status=RECEIPT_SUBMITTED)
        return _recover_in_doubt(ctx, plan, managed_root, receipt, state)
    return _recover_in_doubt(ctx, plan, managed_root, receipt, state)


def validate_reference_asset_outputs(
    ctx: WorkerContext, result: dict[str, Any], staging_dir: Path
) -> dict[str, Any]:
    """Register-time fail-closed gate: receipt + library asset must be on disk."""
    del staging_dir  # the job publishes under the managed root, not the staging dir
    if result.get("cancelled"):
        return {"cancelled": True}
    content_key = str(result.get("content_key") or "")
    if not content_key:
        raise JobError("reference-asset result carries no content key")
    managed_root = _manifest_managed_root(dict(ctx.input_manifest))
    receipt = read_receipt(managed_root, content_key)
    if receipt is None or str(receipt.get("status")) != RECEIPT_COMPLETED:
        raise JobError(f"reference-asset receipt for {content_key} is not completed")
    engine = dict(receipt.get("engine") or {})
    rel = str(engine.get("artifact_store_relative_path") or "")
    sha = str(engine.get("artifact_sha256") or "")
    path = ManagedRoot(managed_root).resolve(rel)
    if not path.is_file() or hash_file(path) != sha:
        raise JobError(f"reference-asset artifact {rel} is missing or has drifted")
    return {
        "receipt": {"relative_path": receipt_relpath(content_key), "sha256": hash_file(
            receipt_path(managed_root, content_key)
        )},
        "engine_artifact": {"relative_path": rel, "sha256": sha},
        "asset_id": (receipt.get("asset") or {}).get("asset_id"),
    }


# ── wiring: worker registration, submit/retry services ──────────────────────


def register_reference_asset_handler(worker: Any) -> None:
    """Register the durable handler + fail-closed output validator."""
    worker.register_handler(
        JOB_TYPE_REFERENCE_ASSET,
        run_reference_asset_job,
        declared_outputs=None,
        output_validator=validate_reference_asset_outputs,
        resource_class="gpu",
    )


@dataclass(frozen=True)
class ReferenceAssetSubmitResult:
    """Outcome of an intent registration (no engine work happened yet)."""

    job: Any
    content_key: str
    reference_key: str
    view: str
    role: str
    duplicate: bool


def _build_manifest(
    *,
    workspace_id: str,
    character_id: str,
    version_id: str,
    reference_key: str,
    view_prompt: str,
    source_reference_key: str,
    source_artifact_id: str,
    source_sha256: str,
    source_size_bytes: int,
    style_version: str | None,
    seed: int | None,
    graph_file_sha256: str,
) -> dict[str, Any]:
    manifest: dict[str, Any] = {
        "schema_version": 1,
        "intent": "reference_asset",
        "workspace_id": workspace_id,
        "character_id": character_id,
        "version_id": version_id,
        "reference_key": reference_key,
        "source_reference_key": source_reference_key,
        "source_artifact_id": source_artifact_id,
        "source_sha256": source_sha256,
        "source_size_bytes": int(source_size_bytes),
        "view_prompt": view_prompt,
        "style_version": style_version,
        "graph_file_sha256": graph_file_sha256,
        "purpose": "artwork",
    }
    if seed is not None:
        manifest["seed"] = int(seed)
    return manifest


def submit_reference_asset_job(
    *,
    job_service: Any,
    workspace_id: str,
    character_id: str,
    version_id: str,
    reference_key: str,
    view_prompt: str,
    source_reference_key: str | None = None,
    style_version: str | None = None,
    seed: int | None = None,
    idempotency_key: str | None = None,
    input_generation: str | None = None,
) -> ReferenceAssetSubmitResult:
    """Validate the live draft pack and register ONE durable job intent.

    No engine work, no library writes: the returned Job is queued and the
    worker performs the run.
    """
    session_factory = getattr(job_service, "session_factory", None)
    if session_factory is None:
        raise ReferenceAssetJobError(
            ReferenceAssetRefusalCode.REQUEST_INVALID, "job service exposes no session factory"
        )
    managed_root = Path(job_service.managed_root)
    view, role = parse_target_key(reference_key)
    source_key = source_reference_key or DEFAULT_SOURCE_REFERENCE_KEY
    if source_key == reference_key:
        raise ReferenceAssetJobError(
            ReferenceAssetRefusalCode.REQUEST_INVALID,
            "source and target reference keys are identical",
        )
    with session_factory() as session:
        repo = CharacterRepository(session, storage_root=managed_root)
        try:
            version = repo.get_pack_version(version_id, workspace_id)
        except PackVersionNotFoundError as exc:
            raise ReferenceAssetJobError(
                ReferenceAssetRefusalCode.VERSION_NOT_FOUND,
                "pack version not found in this workspace",
                details={"version_id": version_id},
            ) from exc
        if str(version.status) != "draft":
            raise ReferenceAssetJobError(
                ReferenceAssetRefusalCode.VERSION_NOT_DRAFT,
                "the pack version is not a draft; published versions are immutable",
                details={"status": str(version.status)},
            )
        present = {str(a.pose_slot) for a in version.assets}
        if reference_key in present:
            raise ReferenceAssetJobError(
                ReferenceAssetRefusalCode.TARGET_KEY_PRESENT,
                "the target reference key already carries an asset",
                details={"reference_key": reference_key, "present": sorted(present)},
            )
        source_asset = next(
            (a for a in version.assets if str(a.pose_slot) == source_key), None
        )
        if source_asset is None:
            raise ReferenceAssetJobError(
                ReferenceAssetRefusalCode.SOURCE_REFERENCE_MISSING,
                "the source identity reference is not attached to the version",
                details={"source_reference_key": source_key, "present": sorted(present)},
            )
        try:
            _asset, path, _mime = repo.resolve_asset_content(
                character_id=character_id,
                version_id=version_id,
                asset_id=str(source_asset.id),
                workspace_id=workspace_id,
            )
        except Exception as exc:
            raise ReferenceAssetJobError(
                ReferenceAssetRefusalCode.SOURCE_REFERENCE_MISSING,
                f"source reference bytes are not serviceable: {type(exc).__name__}",
                details={"source_reference_key": source_key},
            ) from exc
        data = Path(path).read_bytes()
    source_sha256 = _sha256_bytes(data)
    _document, graph_manifest = load_graph_documents()
    graph_file_sha256 = str((graph_manifest.get("workflow") or {}).get("graph_file_sha256") or "")
    manifest = _build_manifest(
        workspace_id=workspace_id,
        character_id=character_id,
        version_id=version_id,
        reference_key=reference_key,
        view_prompt=view_prompt,
        source_reference_key=source_key,
        source_artifact_id=str(source_asset.id),
        source_sha256=source_sha256,
        source_size_bytes=len(data),
        style_version=style_version,
        seed=seed,
        graph_file_sha256=graph_file_sha256,
    )
    plan = reference_asset_plan(manifest)
    manifest["content_key"] = plan.content_key
    digest = plan.content_key.split(":", 1)[-1][:40]
    key = idempotency_key or f"reference_asset:{version_id}:{digest}"
    duplicate = False
    try:
        info = job_service.create_job(
            JOB_TYPE_REFERENCE_ASSET,
            manifest,
            workspace_id=workspace_id,
            owner_type="character",
            owner_id=character_id,
            idempotency_key=key,
            input_generation=input_generation,
            max_attempts=DEFAULT_MAX_ATTEMPTS,
        )
    except IdempotencyKeyInUse as exc:
        existing = job_service.get_job(str(exc.job_id or ""))
        if existing is None:
            raise ReferenceAssetJobError(
                ReferenceAssetRefusalCode.IDEMPOTENCY_CONFLICT,
                "an active job already holds this intent but is not readable",
                details={"job_id": exc.job_id},
            ) from exc
        info = existing
        duplicate = True
    return ReferenceAssetSubmitResult(
        job=info,
        content_key=plan.content_key,
        reference_key=reference_key,
        view=view,
        role=role,
        duplicate=duplicate,
    )


def resubmit_reference_asset_job(
    *, job_service: Any, job_id: str, input_generation: str | None = None
) -> ReferenceAssetSubmitResult:
    """Retry a terminal reference-asset job as a NEW generation (receipt replayed)."""
    session_factory = getattr(job_service, "session_factory", None)
    if session_factory is None:
        raise ReferenceAssetJobError(
            ReferenceAssetRefusalCode.REQUEST_INVALID, "job service exposes no session factory"
        )
    with session_factory() as session:
        row = session.get(Job, job_id)
        if row is None:
            raise ReferenceAssetJobError(
                ReferenceAssetRefusalCode.JOB_NOT_FOUND,
                f"no job {job_id}",
                details={"job_id": job_id},
            )
        if str(row.job_type) != JOB_TYPE_REFERENCE_ASSET:
            raise ReferenceAssetJobError(
                ReferenceAssetRefusalCode.REQUEST_INVALID,
                "the job is not a reference-asset job",
                details={"job_type": str(row.job_type)},
            )
        if str(row.state) not in TERMINAL_STATES:
            raise ReferenceAssetJobError(
                ReferenceAssetRefusalCode.JOB_NOT_RETRYABLE,
                "only a terminal reference-asset job can be retried",
                details={"state": str(row.state)},
            )
        raw_manifest = row.input_manifest_json
        manifest = raw_manifest if isinstance(raw_manifest, dict) else parse_json(raw_manifest, {})
        workspace_id = str(row.workspace_id)
        owner_type = str(row.owner_type)
        owner_id = str(row.owner_id)
        key = str(row.idempotency_key or "")
    if not isinstance(manifest, dict) or not manifest:
        raise ReferenceAssetJobError(
            ReferenceAssetRefusalCode.RECEIPT_INCOMPLETE, "the job carries no durable manifest"
        )
    generation = input_generation or f"retry-{uuid.uuid4().hex[:8]}"
    # A terminal predecessor keeps its idempotency key under the partial unique
    # index, so a fresh logical run gets a NEW key that carries the generation.
    retry_key = f"{key}:{generation}" if key else None
    info = job_service.create_job(
        JOB_TYPE_REFERENCE_ASSET,
        manifest,
        workspace_id=workspace_id,
        owner_type=owner_type,
        owner_id=owner_id,
        idempotency_key=retry_key,
        input_generation=generation,
        max_attempts=DEFAULT_MAX_ATTEMPTS,
    )
    plan = reference_asset_plan(manifest)
    return ReferenceAssetSubmitResult(
        job=info,
        content_key=plan.content_key,
        reference_key=plan.reference_key,
        view=plan.view,
        role=plan.role,
        duplicate=False,
    )
