"use client";

import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { AlertCircle, Plus, Radio, RefreshCw, X } from "lucide-react";
import { api } from "@/lib/api";
import { ContextInspector } from "@/components/layout/ContextInspector";

const date = (value: string) => new Intl.DateTimeFormat("vi-VN", { dateStyle: "medium" }).format(new Date(value));
export default function ChannelsPage() {
  const queryClient = useQueryClient();
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [showForm, setShowForm] = useState(false);
  const [name, setName] = useState("");
  const [language, setLanguage] = useState("vi");
  const [validation, setValidation] = useState("");
  const query = useQuery({ queryKey: ["channels"], queryFn: () => api.listChannels() });
  const create = useMutation({ mutationFn: () => api.createChannel(name.trim(), language), onSuccess: async () => { await queryClient.invalidateQueries({ queryKey: ["channels"] }); setName(""); setShowForm(false); } });
  const selected = query.data?.find((channel) => channel.channel_id === selectedId);
  const submit = (event: React.FormEvent) => { event.preventDefault(); if (!name.trim()) { setValidation("Vui lòng nhập tên kênh."); return; } setValidation(""); create.mutate(); };
  const sections = selected ? [{ title: "Thông tin kênh", rows: [{ label: "Tên", value: selected.name }, { label: "Mã kênh", value: <span className="font-mono">{selected.channel_id}</span> }, { label: "Ngôn ngữ", value: selected.target_lang }, { label: "Ngày tạo", value: date(selected.created_at) }] }, { title: "Ghi chú", rows: [{ label: "Vai trò", value: "Nhóm video nguồn và các phiên bản đầu ra của cùng một chuỗi nội dung." }] }] : [];

  return <div className="flex min-h-[calc(100vh-4rem)]"><div className="min-w-0 flex-1 p-6 lg:p-8">
    <div className="mb-6 flex items-start justify-between gap-4"><div><h2 className="font-display text-2xl font-semibold">Kênh</h2><p className="mt-1 text-sm text-[var(--text-muted)]">Quản lý kênh nguồn và kênh sản xuất.</p></div><button onClick={() => setShowForm(true)} className="flex min-h-10 items-center gap-2 rounded-lg bg-[var(--primary-700)] px-4 text-sm font-semibold text-white hover:bg-[var(--primary-600)]"><Plus size={17} />Tạo kênh</button></div>
    {showForm && <form onSubmit={submit} className="mb-6 rounded-xl border border-[var(--surface-700)] bg-[var(--surface-900)] p-4"><div className="mb-4 flex items-center justify-between"><h3 className="font-display font-semibold">Kênh mới</h3><button type="button" aria-label="Đóng biểu mẫu" onClick={() => setShowForm(false)} className="grid size-8 place-items-center rounded-lg hover:bg-[var(--surface-800)]"><X size={17} /></button></div><div className="grid gap-4 sm:grid-cols-[1fr_10rem_auto]"><label className="text-sm text-[var(--text-secondary)]">Tên kênh<input value={name} onChange={(e) => setName(e.target.value)} className="mt-1 min-h-10 w-full rounded-lg border border-[var(--surface-700)] bg-[var(--surface-950)] px-3 text-[var(--text-primary)]" /></label><label className="text-sm text-[var(--text-secondary)]">Ngôn ngữ<select value={language} onChange={(e) => setLanguage(e.target.value)} className="mt-1 min-h-10 w-full rounded-lg border border-[var(--surface-700)] bg-[var(--surface-950)] px-3"><option value="vi">Tiếng Việt</option><option value="en">Tiếng Anh</option></select></label><button disabled={create.isPending} className="min-h-10 self-end rounded-lg bg-[var(--primary-700)] px-4 text-sm font-semibold text-white disabled:opacity-60">{create.isPending ? "Đang tạo..." : "Lưu kênh"}</button></div>{validation && <p className="mt-2 text-sm text-[var(--danger)]">{validation}</p>}{create.error && <p className="mt-2 text-sm text-[var(--danger)]">Không thể tạo kênh. Vui lòng thử lại.</p>}</form>}
    {query.isLoading && <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{[1,2,3].map((n) => <div key={n} className="h-44 animate-pulse rounded-xl bg-[var(--surface-850)]" />)}</div>}
    {query.isError && <div className="rounded-xl border border-[var(--danger)] bg-[var(--surface-900)] p-6 text-center"><AlertCircle className="mx-auto text-[var(--danger)]" /><p className="mt-3 text-[var(--text-secondary)]">Không thể tải danh sách kênh.</p><button onClick={() => query.refetch()} className="mx-auto mt-4 flex min-h-10 items-center gap-2 rounded-lg bg-[var(--surface-800)] px-4 text-sm"><RefreshCw size={16} />Thử lại</button></div>}
    {query.data?.length === 0 && <div className="rounded-xl border border-dashed border-[var(--surface-700)] bg-[var(--surface-900)] p-10 text-center"><Radio className="mx-auto text-[var(--accent-300)]" size={32} /><h3 className="mt-4 font-display text-lg font-semibold">Chưa có kênh nào</h3><p className="mx-auto mt-2 max-w-lg text-sm text-[var(--text-muted)]">Kênh dùng để nhóm video nguồn và phiên bản đầu ra cho từng chuỗi nội dung.</p><button onClick={() => setShowForm(true)} className="mt-5 min-h-10 rounded-lg bg-[var(--primary-700)] px-4 text-sm font-semibold text-white">Tạo kênh</button></div>}
    {query.data && query.data.length > 0 && <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{query.data.map((channel) => <button key={channel.channel_id} type="button" aria-pressed={selectedId === channel.channel_id} onClick={() => setSelectedId(channel.channel_id)} className={`min-h-40 rounded-xl border bg-[var(--surface-900)] p-5 text-left transition-colors hover:bg-[var(--surface-850)] ${selectedId === channel.channel_id ? "border-[var(--primary-400)]" : "border-[var(--surface-800)]"}`}><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-lg bg-[var(--surface-800)] text-[var(--accent-300)]"><Radio size={20} /></span><div className="min-w-0"><h3 className="truncate font-display font-semibold">{channel.name}</h3><p className="truncate font-mono text-xs text-[var(--text-muted)]">{channel.channel_id}</p></div></div><div className="mt-4 flex flex-wrap gap-2 text-xs text-[var(--text-secondary)]"><span className="rounded-full bg-[var(--surface-800)] px-2.5 py-1">Ngôn ngữ: {channel.target_lang}</span>{channel.default_preset_id && <span className="rounded-full bg-[var(--surface-800)] px-2.5 py-1">Preset: {channel.default_preset_id}</span>}</div><p className="mt-3 text-xs text-[var(--text-muted)]">Tạo ngày {date(channel.created_at)}</p></button>)}</div>}
  </div><ContextInspector title={selected?.name ?? "Chi tiết kênh"} sections={sections} /></div>;
}
