"""S05-C01 — Orchestration tests for the approved T02→T03→T04 API chain.

Proves the S05-C01 outcome through the REAL UI-facing API surface on real
synthetic media (CFR + VFR fixtures generated by ffmpeg under ``tmp_path``,
never mock data):

1. ``test_one_submission_drives_t02_t03_t04_in_order`` — ONE
   ``POST /api/projects/{id}/analyze`` creates the ``ANALYZE_MEDIA`` import
   Job; the backend chain-state endpoint materializes ``GENERATE_PROXY``
   (T03) and ``ANALYZE_MEDIA`` scene_detect (T04) as each predecessor
   durably completes; every step's durable Job row is created/completed in
   order and the UI-facing chain state reflects the real rows.
2. ``test_cfr_chain_completes_through_api`` + ``test_vfr_chain_completes_through_api`` —
   CFR and genuinely-VFR sources both complete through the orchestration
   API with the canonical scene/time contracts.
3. ``test_proxy_sha_size_containment_through_chain`` — the proxy artifact's
   SHA-256/size match the file on disk; paths contained under the managed
   root; exactly one source + one proxy effect set.
4. ``test_successor_retry_after_failure_via_api`` — a failed scene step is
   retried via ``POST /api/projects/{id}/analyze/retry`` which creates a
   successor Job (§8.5); the retry succeeds (no 500 IdempotencyKeyInUse);
   duplicate retry reuses the successor.
5. ``test_stable_scene_ids_across_successor_retry`` — rows committed then
   permanent failure; the successor retry reuses the committed rows —
   identical Scene IDs, revision 1, predecessor immutable.
6. ``test_successor_retry_after_cancel_via_api`` — HTTP cancel mid-run
   drains to terminal ``cancelled``; retry creates a successor that
   completes with exactly one effect set.
7. ``test_cancel_during_active_cleans_staging_and_committed_survive`` —
   cancel during active processing cleans the attempt's own staging; the
   committed source artifact survives (sha/size); no later step Job is
   created (no orphans).
8. ``test_restart_resume_no_duplicate_publication`` — a fresh engine +
   brand-new worker on the same database resumes the chain; no duplicate
   publication (exactly one source + one proxy artifact, one attempt each,
   sha/size verified, stable Scene IDs).
9. ``test_orphan_cleanup_no_stray_jobs_or_files`` — after a cancel, no
   stray chain Jobs or files exist anywhere outside the managed artifacts.
10. ``test_idempotent_resubmission_reuses_chain`` — repeated submissions
    reuse the existing chain (never a duplicate Job).
11. ``test_retry_and_submit_validation`` — 404 unknown project, 400 when no
    source is uploaded, 400 retry on a completed chain.

Every test uses a temporary Alembic-migrated SQLite DB + temporary managed
root; the API client fixture points ``app.api.deps`` at the same DB and
managed root and restores the previous deps state afterwards.  Tests skip
gracefully when ffmpeg is not available (mirroring test_s05_golden_integration).
"""

from __future__ import annotations

import hashlib
import shutil
import subprocess
from collections.abc import Iterator
from datetime import UTC, datetime, timedelta
from pathlib import Path

import pytest
from alembic import command
from alembic.config import Config
from sqlalchemy import select
from sqlalchemy.orm import Session

from app.persistence import (
    JobRepository,
    create_engine_for_path,
    create_session_factory,
)
from app.persistence.models import (
    Artifact,
    ArtifactOwner,
    Job,
    Scene,
    VideoItem,
)
from app.services import scene_detector, video_import, video_proxy
from app.services.scene_detector import (
    CODE_PUBLICATION_FAILED,
    CODE_SCENE_DETECT_FAILED,
    register_scene_detection_handler,
)
from app.services.timebase import CanonicalTimebase
from app.services.video_proxy import ARTIFACT_PURPOSE_PROXY, register_generate_proxy_handler
from app.workflow.analyze_orchestrator import (
    AnalyzeChainOrchestrator,
    get_analyze_orchestrator,
)
from app.workflow.durable_worker import DurableWorker, WorkerConfig

PROJECT_ROOT = Path(__file__).resolve().parent.parent
ALEMBIC_INI = PROJECT_ROOT / "alembic.ini"


# ── Deterministic clock/sleeper (mirror test_s05_golden_integration) ────────


class FakeClock:
    def __init__(self, start: datetime | None = None) -> None:
        self.now = start or datetime(2026, 8, 5, 12, 0, 0, tzinfo=UTC)

    def __call__(self) -> datetime:
        return self.now

    def advance(self, seconds: float) -> None:
        self.now += timedelta(seconds=seconds)


class FakeSleeper:
    def __init__(self) -> None:
        self.calls: list[float] = []

    def __call__(self, seconds: float) -> None:
        self.calls.append(seconds)


# ── DB fixtures ──────────────────────────────────────────────────────────────


def _alembic_config(database_path: Path) -> Config:
    cfg = Config(str(ALEMBIC_INI))
    cfg.set_main_option("script_location", str(PROJECT_ROOT / "migrations"))
    cfg.set_main_option("sqlalchemy.url", f"sqlite:///{database_path.as_posix()}")
    return cfg


def _upgrade(database_path: Path) -> None:
    command.upgrade(_alembic_config(database_path), "head")


@pytest.fixture()
def db_path(tmp_path: Path) -> Path:
    return tmp_path / "orchestration.db"


@pytest.fixture()
def session_factory(db_path: Path):
    _upgrade(db_path)
    return create_session_factory(create_engine_for_path(db_path))


@pytest.fixture()
def session(session_factory) -> Iterator[Session]:
    with session_factory() as s:
        yield s


@pytest.fixture()
def managed_root(tmp_path: Path) -> Path:
    root = tmp_path / "managed"
    root.mkdir(exist_ok=True)
    return root


@pytest.fixture()
def clock() -> FakeClock:
    return FakeClock()


@pytest.fixture()
def sleeper() -> FakeSleeper:
    return FakeSleeper()


@pytest.fixture()
def worker(
    session_factory,
    managed_root: Path,
    clock: FakeClock,
    sleeper: FakeSleeper,
) -> DurableWorker:
    """A worker with fake clock/sleeper and the full S05 handler set."""
    w = DurableWorker(
        session_factory,
        config=WorkerConfig(
            worker_id="orchestration-worker",
            lease_ttl=60,
            heartbeat_interval=15,
            poll_interval=0.01,
            max_attempts=3,
            staging_root=managed_root,
        ),
        clock=clock,
        sleeper=sleeper,
    )
    register_generate_proxy_handler(w)
    register_scene_detection_handler(w)
    return w


@pytest.fixture()
def api_client(session_factory, managed_root: Path, db_path: Path):
    """TestClient over the real FastAPI app with deps pointed at the same
    database + managed root — the exact UI-facing surface
    (``POST/GET /api/projects/{id}/analyze``, ``POST .../analyze/retry``,
    ``POST /api/jobs/{id}/cancel``)."""
    from fastapi.testclient import TestClient

    from app.api import deps
    from app.api.app import app
    from app.config import AppConfig
    from app.workflow.job_service import JobService
    from app.workflow.project_workflow import ProjectWorkflowService

    cfg = AppConfig(
        project_root=db_path.parent / "proj",
        models_dir=db_path.parent / "proj" / "models",
        output_dir=db_path.parent / "proj" / "output",
    )
    saved = (
        getattr(deps, "_config", None),
        getattr(deps, "_project_wf", None),
        getattr(deps, "_job_service", None),
        getattr(deps, "_lifecycle_db", None),
    )
    deps._config = cfg
    deps._project_wf = ProjectWorkflowService(cfg)
    deps._job_service = JobService(session_factory, managed_root=managed_root)
    deps._lifecycle_db = db_path
    client = TestClient(app, raise_server_exceptions=True)
    yield client
    (
        deps._config,
        deps._project_wf,
        deps._job_service,
        deps._lifecycle_db,
    ) = saved


# ── Synthetic media fixtures (real ffmpeg → tmp_path) ───────────────────────


def _ffmpeg_available() -> bool:
    try:
        from app.services.ffmpeg_utils import find_ffprobe

        find_ffprobe()
        return shutil.which("ffmpeg") is not None
    except Exception:
        return False


def _make_cut_video(path: Path, *, fps: int = 30, rate: str | None = None) -> Path | None:
    """A 2s/60-frame clip with ONE hard cut at frame ``round(1s * fps)``:
    blue (1s) → red (1s), scene score ~1.0, zero motion noise."""
    ffmpeg = shutil.which("ffmpeg") or "ffmpeg"
    path.parent.mkdir(parents=True, exist_ok=True)
    rate_arg = rate or str(fps)
    cmd = [
        ffmpeg,
        "-y",
        "-f",
        "lavfi",
        "-i",
        f"color=c=blue:duration=1.0:size=320x240:rate={rate_arg}",
        "-f",
        "lavfi",
        "-i",
        f"color=c=red:duration=1.0:size=320x240:rate={rate_arg}",
        "-filter_complex",
        "[0:v][1:v]concat=n=2:v=1:a=0[v]",
        "-map",
        "[v]",
        "-c:v",
        "libx264",
        "-preset",
        "ultrafast",
        "-crf",
        "28",
        "-pix_fmt",
        "yuv420p",
        str(path),
    ]
    result = subprocess.run(cmd, capture_output=True, text=True, timeout=60)
    if result.returncode != 0:
        return None
    return path


def _make_video(
    path: Path,
    *,
    duration: float = 1.0,
    fps: int = 30,
    color: str = "blue",
) -> Path | None:
    """Create a CFR synthetic MP4/H.264 clip (static color)."""
    ffmpeg = shutil.which("ffmpeg") or "ffmpeg"
    path.parent.mkdir(parents=True, exist_ok=True)
    cmd = [
        ffmpeg,
        "-y",
        "-f",
        "lavfi",
        "-i",
        f"color=c={color}:duration={duration}:size=320x240:rate={fps}",
        "-c:v",
        "libx264",
        "-preset",
        "ultrafast",
        "-crf",
        "28",
        "-pix_fmt",
        "yuv420p",
        str(path),
    ]
    result = subprocess.run(cmd, capture_output=True, text=True, timeout=60)
    if result.returncode != 0:
        return None
    return path


def _make_vfr_cut_video(tmp_path: Path, name: str = "vfr.mp4") -> Path | None:
    """A real VFR MP4 with one hard cut: a 30fps blue segment + a 25fps red
    segment concatenated with ``-c copy`` → ``r_frame_rate != avg_frame_rate``."""
    ffmpeg = shutil.which("ffmpeg") or "ffmpeg"
    seg1 = tmp_path / "seg30.mp4"
    seg2 = tmp_path / "seg25.mp4"
    for seg, fps, color in ((seg1, 30, "blue"), (seg2, 25, "red")):
        made = _make_video(seg, duration=1.0, fps=fps, color=color)
        assert made is not None, "ffmpeg failed to create a VFR segment"
    lst = tmp_path / "concat.txt"
    lst.write_text(f"file '{seg1.as_posix()}'\nfile '{seg2.as_posix()}'\n", encoding="utf-8")
    out = tmp_path / name
    result = subprocess.run(
        [
            ffmpeg,
            "-y",
            "-f",
            "concat",
            "-safe",
            "0",
            "-i",
            str(lst),
            "-c",
            "copy",
            "-movflags",
            "+faststart",
            str(out),
        ],
        capture_output=True,
        text=True,
        timeout=60,
    )
    if result.returncode != 0:
        pytest.skip("ffmpeg concat failed to create the VFR fixture")
    probe = video_import.probe_source(out)
    video = probe["video_stream"]
    if video["r_frame_rate"] == video["avg_frame_rate"]:
        pytest.skip("concat output is not genuinely VFR on this ffmpeg build")
    return out


@pytest.fixture()
def cfr_cut_video(tmp_path: Path) -> Path:
    if not _ffmpeg_available():
        pytest.skip("ffmpeg/ffprobe not available")
    out = _make_cut_video(tmp_path / "cfr_cut.mp4", fps=30)
    assert out is not None, "ffmpeg failed to create the CFR cut fixture"
    return out


@pytest.fixture()
def vfr_cut_video(tmp_path: Path) -> Path:
    if not _ffmpeg_available():
        pytest.skip("ffmpeg/ffprobe not available")
    out = _make_vfr_cut_video(tmp_path)
    assert out is not None, "ffmpeg failed to create the VFR cut fixture"
    return out


# ── API chain helpers ────────────────────────────────────────────────────────


def _create_project(api_client, name: str) -> str:
    resp = api_client.post("/api/projects", json={"name": name})
    assert resp.status_code == 201, resp.text
    return resp.json()["project_id"]


def _upload_video(api_client, project_id: str, source: Path) -> None:
    with source.open("rb") as handle:
        resp = api_client.post(
            f"/api/projects/{project_id}/video",
            files={"file": (source.name, handle, "video/mp4")},
        )
    assert resp.status_code == 200, resp.text


def _submit_chain(api_client, project_id: str, title: str | None = None) -> dict:
    resp = api_client.post(
        f"/api/projects/{project_id}/analyze",
        json={"generation": "1", "title": title},
    )
    assert resp.status_code == 200, resp.text
    return resp.json()


def _get_chain(api_client, project_id: str) -> dict:
    resp = api_client.get(f"/api/projects/{project_id}/analyze")
    assert resp.status_code == 200, resp.text
    return resp.json()


def _run_job(worker: DurableWorker) -> None:
    worker.run_once()


def _managed_root_of(api_client) -> Path:
    """The managed root bound to the API job service (test helper)."""
    from app.api import deps

    return Path(str(deps._job_service._managed_root))  # noqa: SLF001


def _step_checkpoint(session_factory, job_id: str) -> dict:
    import json

    from app.persistence.models import JobStep

    with session_factory() as s:
        step_row = s.scalars(
            select(JobStep).where(JobStep.job_id == job_id).order_by(JobStep.position)
        ).first()
        assert step_row is not None
        return json.loads(step_row.checkpoint_json or "{}")


def _job_state(session_factory, job_id: str) -> str:
    with session_factory() as s:
        return JobRepository(s).get_job(job_id).state


def _scene_rows(session_factory, video_item_id: str) -> list[Scene]:
    with session_factory() as s:
        return list(
            s.scalars(
                select(Scene).where(Scene.video_item_id == video_item_id).order_by(Scene.position)
            ).all()
        )


def _staging_files(managed_root: Path) -> list[Path]:
    staging = managed_root / "staging"
    if not staging.is_dir():
        return []
    return [p for p in staging.rglob("*") if p.is_file()]


def _ready_video_artifacts(session_factory, workspace_id: str) -> list[Artifact]:
    with session_factory() as s:
        return list(
            s.scalars(
                select(Artifact)
                .where(
                    Artifact.workspace_id == workspace_id,
                    Artifact.kind == "video",
                    Artifact.state == "ready",
                )
                .order_by(Artifact.relative_path)
            ).all()
        )


def _artifact_sha_size(path: Path) -> tuple[str, int]:
    return hashlib.sha256(path.read_bytes()).hexdigest(), path.stat().st_size


def _owner_purposes(session_factory, artifact_id: str) -> set[str]:
    with session_factory() as s:
        return set(
            s.scalars(
                select(ArtifactOwner.purpose).where(ArtifactOwner.artifact_id == artifact_id)
            ).all()
        )


def _advance() -> None:
    """ONE backend-owned chain progression pass (the durable orchestrator).

    S05-C02: GET /analyze is strictly read-only — the chain advances under
    the orchestration service, never via a read endpoint.
    """
    get_analyze_orchestrator().advance_once()


def _drive_chain(worker, api_client, project_id: str, max_rounds: int = 10) -> dict:
    """Alternate worker execution and orchestrator advancement (the backend
    ownership model) until the chain is terminal.  GET is used ONLY to read
    the honest chain state."""
    chain: dict = {}
    for _ in range(max_rounds):
        _run_job(worker)
        _advance()
        chain = _get_chain(api_client, project_id)
        if chain["chain_status"] in ("completed", "failed", "cancelled"):
            return chain
    return chain


# ── AC1: ONE submission drives T02→T03→T04 in order ─────────────────────────


def test_one_submission_drives_t02_t03_t04_in_order(
    worker, session_factory, api_client, cfr_cut_video
) -> None:
    pid = _create_project(api_client, "S05C01 one submission")
    _upload_video(api_client, pid, cfr_cut_video)

    # ONE submission → the import Job exists immediately; nothing else yet.
    chain = _submit_chain(api_client, pid, cfr_cut_video.name)
    assert chain["chain_status"] == "running"
    assert chain["steps"]["import"]["status"] in ("queued", "pending")
    assert chain["steps"]["import"]["job_id"] is not None
    import_job_id = chain["steps"]["import"]["job_id"]
    assert chain["steps"]["proxy"]["status"] == "not_created"
    assert chain["steps"]["scene_detect"]["status"] == "not_created"
    assert _job_state(session_factory, import_job_id) in ("queued", "pending")
    with session_factory() as s:
        import_job = JobRepository(s).get_job(import_job_id)
        assert import_job.job_type == video_import.JOB_TYPE_ANALYZE_MEDIA
        assert import_job.owner_type == "video_item"

    # T02 completes → the chain state materializes T03 GENERATE_PROXY.
    _run_job(worker)
    assert _job_state(session_factory, import_job_id) == "completed"
    _advance()
    chain = _get_chain(api_client, pid)
    assert chain["steps"]["import"]["status"] == "completed"
    assert chain["steps"]["import"]["progress"] == 100.0
    assert chain["steps"]["proxy"]["status"] in ("queued", "pending")
    proxy_job_id = chain["steps"]["proxy"]["job_id"]
    with session_factory() as s:
        proxy_job = JobRepository(s).get_job(proxy_job_id)
        assert proxy_job.job_type == video_proxy.JOB_TYPE_GENERATE_PROXY
    assert chain["steps"]["scene_detect"]["status"] == "not_created"

    # T03 completes → T04 ANALYZE_MEDIA scene_detect is materialized.
    _run_job(worker)
    assert _job_state(session_factory, proxy_job_id) == "completed"
    _advance()
    chain = _get_chain(api_client, pid)
    assert chain["steps"]["proxy"]["status"] == "completed"
    assert chain["steps"]["proxy"]["progress"] == 100.0
    assert chain["steps"]["scene_detect"]["status"] in ("queued", "pending")
    scene_job_id = chain["steps"]["scene_detect"]["job_id"]
    with session_factory() as s:
        scene_job = JobRepository(s).get_job(scene_job_id)
        assert scene_job.job_type == video_import.JOB_TYPE_ANALYZE_MEDIA
        steps = JobRepository(s).list_steps(scene_job_id)
        assert [st.step_code for st in steps] == ["scene_detect"]

    # T04 completes → the chain is terminal-completed with real state.
    chain = _drive_chain(worker, api_client, pid, max_rounds=2)
    assert chain["chain_status"] == "completed"
    assert chain["active_step"] is None
    assert chain["steps"]["import"]["status"] == "completed"
    assert chain["steps"]["proxy"]["status"] == "completed"
    assert chain["steps"]["scene_detect"]["status"] == "completed"
    assert chain["steps"]["scene_detect"]["progress"] == 100.0
    assert chain["scenes_count"] == 2
    assert chain["source_artifact_id"] is not None
    assert chain["proxy_artifact_id"] is not None
    assert _job_state(session_factory, scene_job_id) == "completed"


# ── CFR + VFR completion through the orchestration API ───────────────────────


def test_cfr_chain_completes_through_api(
    worker, session_factory, api_client, cfr_cut_video
) -> None:
    pid = _create_project(api_client, "S05C01 CFR")
    _upload_video(api_client, pid, cfr_cut_video)
    _submit_chain(api_client, pid, cfr_cut_video.name)
    chain = _drive_chain(worker, api_client, pid)
    assert chain["chain_status"] == "completed"
    assert chain["scenes_count"] == 2

    with session_factory() as s:
        item = s.scalar(
            select(VideoItem).where(VideoItem.project_id == pid).limit(1)
        )
        assert item is not None
        assert item.duration_ms == 2000
        assert item.width == 320
        assert item.height == 240
        assert (item.fps_num, item.fps_den) == (30, 1)
        assert item.source_artifact_id is not None

    rows = _scene_rows(session_factory, chain["video_item_id"])
    assert [(r.position, r.start_frame, r.end_frame) for r in rows] == [
        (0, 0, 29),
        (1, 30, 59),
    ]
    assert [(r.start_time_ms, r.end_time_ms) for r in rows] == [(0, 999), (1000, 1999)]
    assert all(r.status == "pending" for r in rows)
    assert all(r.revision == 1 for r in rows)
    assert all(r.legacy_scene_id is None for r in rows)
    assert _staging_files(_managed_root_of(api_client)) == []


def test_vfr_chain_completes_through_api(
    worker, session_factory, api_client, vfr_cut_video
) -> None:
    pid = _create_project(api_client, "S05C01 VFR")
    _upload_video(api_client, pid, vfr_cut_video)
    _submit_chain(api_client, pid, vfr_cut_video.name)
    chain = _drive_chain(worker, api_client, pid)
    assert chain["chain_status"] == "completed"
    assert chain["scenes_count"] >= 2

    # The import checkpoint recorded the REAL VFR classification.
    import_cp = _step_checkpoint(session_factory, chain["steps"]["import"]["job_id"])
    src_video = import_cp["probe"]["video_stream"]
    assert src_video["fps_classification"] == "VFR"
    assert src_video["r_frame_rate"] != src_video["avg_frame_rate"]
    avg_num = int(src_video["avg_frame_rate"]["num"])
    avg_den = int(src_video["avg_frame_rate"]["den"])
    assert avg_num > 0 and avg_den > 0

    # The proxy resampled onto the canonical avg_frame_rate grid.
    proxy_cp = _step_checkpoint(session_factory, chain["steps"]["proxy"]["job_id"])
    timebase = CanonicalTimebase.from_json(proxy_cp["timebase"])
    assert (timebase.fps_num, timebase.fps_den) == (avg_num, avg_den)

    # Every scene row recomputes exactly from the persisted rational grid.
    scene_cp = _step_checkpoint(
        session_factory, chain["steps"]["scene_detect"]["job_id"]
    )
    scene_tb = CanonicalTimebase.from_json(scene_cp["detection"]["timebase"])
    assert (scene_tb.fps_num, scene_tb.fps_den) == (avg_num, avg_den)
    rows = _scene_rows(session_factory, chain["video_item_id"])
    positions = [r.position for r in rows]
    assert len(set(positions)) == len(positions)
    for row in rows:
        assert 0 <= row.start_frame <= row.end_frame < (scene_tb.nb_frames or 0)
    assert _staging_files(_managed_root_of(api_client)) == []


# ── AC4: proxy SHA/size/containment through the chain ───────────────────────


def test_proxy_sha_size_containment_through_chain(
    worker, session_factory, api_client, cfr_cut_video
) -> None:
    pid = _create_project(api_client, "S05C01 sha/size")
    _upload_video(api_client, pid, cfr_cut_video)
    _submit_chain(api_client, pid, cfr_cut_video.name)
    chain = _drive_chain(worker, api_client, pid)
    assert chain["chain_status"] == "completed"

    root = _managed_root_of(api_client).resolve()
    arts = _ready_video_artifacts(session_factory, "default")
    assert len(arts) == 2  # exactly one source + one proxy
    purposes_seen: set[str] = set()
    for art in arts:
        sha, size = _artifact_sha_size(root / art.relative_path)
        assert art.sha256 == sha
        assert art.size_bytes == size
        resolved = (root / art.relative_path).resolve()
        assert resolved.is_relative_to(root)
        assert art.relative_path.startswith("artifacts/")
        assert ".." not in art.relative_path.split("/")
        purposes_seen.update(_owner_purposes(session_factory, art.id))
    assert purposes_seen == {
        video_import.ARTIFACT_PURPOSE_SOURCE,
        ARTIFACT_PURPOSE_PROXY,
    }
    # The proxy artifact is the one exposed by the chain state.
    proxy_art = next(
        a for a in arts if _owner_purposes(session_factory, a.id) == {ARTIFACT_PURPOSE_PROXY}
    )
    assert proxy_art.id == chain["proxy_artifact_id"]
    assert _staging_files(root) == []
    all_files = [p for p in root.rglob("*") if p.is_file()]
    for f in all_files:
        assert f.is_relative_to(root / "artifacts"), f"file outside artifacts/: {f}"


# ── AC3: successor retry (failed + cancelled), stable Scene IDs ─────────────


def test_successor_retry_after_failure_via_api(
    worker, session_factory, api_client, cfr_cut_video, monkeypatch
) -> None:
    pid = _create_project(api_client, "S05C01 retry failed")
    _upload_video(api_client, pid, cfr_cut_video)
    _submit_chain(api_client, pid, cfr_cut_video.name)

    # Import + proxy complete; the scene step fails permanently.
    _run_job(worker)  # import
    _advance()
    chain = _get_chain(api_client, pid)
    _run_job(worker)  # proxy
    _advance()
    chain = _get_chain(api_client, pid)
    scene_job_id = chain["steps"]["scene_detect"]["job_id"]

    def fail_detect(ctx, input_path, profile, timebase):
        raise scene_detector.SceneDetectorError(
            CODE_SCENE_DETECT_FAILED, "injected detection failure"
        )

    monkeypatch.setattr(scene_detector, "_run_scene_detect", fail_detect)
    _run_job(worker)
    monkeypatch.undo()

    _advance()
    chain = _get_chain(api_client, pid)
    assert chain["chain_status"] == "failed"
    assert chain["steps"]["scene_detect"]["status"] == "failed"
    assert chain["steps"]["scene_detect"]["error_code"] == CODE_SCENE_DETECT_FAILED
    assert _job_state(session_factory, scene_job_id) == "failed"
    assert _scene_rows(session_factory, chain["video_item_id"]) == []
    assert _staging_files(_managed_root_of(api_client)) == []

    # Retry via the UI-facing endpoint → successor Job (§8.5), NOT a 500.
    resp = api_client.post(f"/api/projects/{pid}/analyze/retry")
    assert resp.status_code == 200, resp.text
    chain = resp.json()
    successor_id = chain["steps"]["scene_detect"]["job_id"]
    assert successor_id != scene_job_id
    assert chain["steps"]["scene_detect"]["predecessor_job_id"] == scene_job_id
    assert _job_state(session_factory, scene_job_id) == "failed"  # predecessor immutable

    # Duplicate retry is idempotent (contract §8.5): the already-created
    # successor is reused — 200 with the same job, never a 409/500.
    resp = api_client.post(f"/api/projects/{pid}/analyze/retry")
    assert resp.status_code == 200, resp.text
    assert resp.json()["steps"]["scene_detect"]["job_id"] == successor_id
    resp = api_client.post(f"/api/projects/{pid}/analyze/retry")
    assert resp.status_code == 200, resp.text
    assert resp.json()["steps"]["scene_detect"]["job_id"] == successor_id

    # The successor actually succeeds — retry-after-failure works.
    chain = _drive_chain(worker, api_client, pid, max_rounds=2)
    assert chain["chain_status"] == "completed"
    assert _job_state(session_factory, successor_id) == "completed"
    rows = _scene_rows(session_factory, chain["video_item_id"])
    assert len(rows) == 2

    # A completed logical run is never retried (contract §8.1): the retry
    # endpoint refuses with a clear 400 — never a fake new job.
    resp = api_client.post(f"/api/projects/{pid}/analyze/retry")
    assert resp.status_code == 400
    assert "No failed or cancelled job to retry" in resp.json()["detail"]


def test_stable_scene_ids_across_successor_retry(
    worker, session_factory, api_client, cfr_cut_video, monkeypatch
) -> None:
    pid = _create_project(api_client, "S05C01 stable ids")
    _upload_video(api_client, pid, cfr_cut_video)
    _submit_chain(api_client, pid, cfr_cut_video.name)
    _run_job(worker)
    _advance()
    chain = _get_chain(api_client, pid)
    _run_job(worker)
    _advance()
    chain = _get_chain(api_client, pid)

    # Rows committed then permanent failure (contract §5.4 replay window
    # closed by the successor's evidence-based reuse).
    real_commit = scene_detector._commit_scene_rows

    def commit_then_permanent_fail(ctx, det_ev):
        real_commit(ctx, det_ev)
        raise scene_detector.SceneDetectorError(
            CODE_PUBLICATION_FAILED, "injected permanent failure after commit"
        )

    monkeypatch.setattr(scene_detector, "_commit_scene_rows", commit_then_permanent_fail)
    _run_job(worker)
    monkeypatch.undo()
    _advance()
    chain = _get_chain(api_client, pid)
    assert chain["chain_status"] == "failed"
    committed_ids = [r.id for r in _scene_rows(session_factory, chain["video_item_id"])]
    assert len(committed_ids) == 2

    # Successor retry reuses the committed rows: identical Scene IDs.
    resp = api_client.post(f"/api/projects/{pid}/analyze/retry")
    assert resp.status_code == 200, resp.text
    chain = _drive_chain(worker, api_client, pid, max_rounds=2)
    assert chain["chain_status"] == "completed"
    rows = _scene_rows(session_factory, chain["video_item_id"])
    assert [r.id for r in rows] == committed_ids
    assert all(r.revision == 1 for r in rows)


def test_successor_retry_after_cancel_via_api(
    worker, session_factory, api_client, cfr_cut_video, monkeypatch
) -> None:
    pid = _create_project(api_client, "S05C01 retry cancelled")
    _upload_video(api_client, pid, cfr_cut_video)
    _submit_chain(api_client, pid, cfr_cut_video.name)
    _run_job(worker)
    _advance()
    chain = _get_chain(api_client, pid)
    _run_job(worker)
    _advance()
    chain = _get_chain(api_client, pid)
    scene_job_id = chain["steps"]["scene_detect"]["job_id"]

    # HTTP cancel mid-detect → terminal cancelled (cooperative drain).
    real_detect = scene_detector._run_scene_detect

    def detect_then_http_cancel(ctx, input_path, profile, timebase):
        resp = api_client.post(f"/api/jobs/{scene_job_id}/cancel")
        assert resp.status_code == 200
        return real_detect(ctx, input_path, profile, timebase)

    monkeypatch.setattr(scene_detector, "_run_scene_detect", detect_then_http_cancel)
    _run_job(worker)
    monkeypatch.undo()

    _advance()
    chain = _get_chain(api_client, pid)
    assert chain["chain_status"] == "cancelled"
    assert chain["steps"]["scene_detect"]["status"] == "cancelled"
    assert _scene_rows(session_factory, chain["video_item_id"]) == []
    assert _staging_files(_managed_root_of(api_client)) == []

    # Retry after cancel → successor completes with exactly one effect set.
    resp = api_client.post(f"/api/projects/{pid}/analyze/retry")
    assert resp.status_code == 200, resp.text
    successor_id = resp.json()["steps"]["scene_detect"]["job_id"]
    assert successor_id != scene_job_id
    chain = _drive_chain(worker, api_client, pid, max_rounds=2)
    assert chain["chain_status"] == "completed"
    assert _job_state(session_factory, successor_id) == "completed"
    rows = _scene_rows(session_factory, chain["video_item_id"])
    assert len(rows) == 2
    with session_factory() as s:
        successor = JobRepository(s).get_job(successor_id)
        assert successor.predecessor_job_id == scene_job_id  # chain link intact
        assert successor.idempotency_key is not None
        pred = JobRepository(s).get_job(scene_job_id)
        assert pred.state == "cancelled"  # terminal predecessor immutable


# ── AC3/AC7: cancel-during-active cleanup + orphan prevention ────────────────


def test_cancel_during_active_cleans_staging_and_committed_survive(
    worker, session_factory, api_client, cfr_cut_video, monkeypatch
) -> None:
    pid = _create_project(api_client, "S05C01 cancel active")
    _upload_video(api_client, pid, cfr_cut_video)
    _submit_chain(api_client, pid, cfr_cut_video.name)
    _run_job(worker)  # import completes → committed source artifact
    _advance()
    chain = _get_chain(api_client, pid)
    source_artifact_id = chain["source_artifact_id"]
    assert source_artifact_id is not None
    proxy_job_id = chain["steps"]["proxy"]["job_id"]

    # Cancel the PROXY step while it is actively encoding (cooperative).
    real_ffmpeg = video_proxy._run_ffmpeg

    def encode_then_http_cancel(ctx, cmd, *, timeout_seconds, staged_path):
        resp = api_client.post(f"/api/jobs/{proxy_job_id}/cancel")
        assert resp.status_code == 200
        return real_ffmpeg(ctx, cmd, timeout_seconds=timeout_seconds, staged_path=staged_path)

    monkeypatch.setattr(video_proxy, "_run_ffmpeg", encode_then_http_cancel)
    _run_job(worker)
    monkeypatch.undo()

    _advance()
    chain = _get_chain(api_client, pid)
    assert chain["chain_status"] == "cancelled"
    assert chain["steps"]["proxy"]["status"] == "cancelled"
    # The scene step was never created (no orphan jobs).
    assert chain["steps"]["scene_detect"]["status"] == "not_created"
    assert chain["steps"]["scene_detect"]["job_id"] is None

    # The committed source artifact survives cancel byte-identical.
    with session_factory() as s:
        src = s.get(Artifact, source_artifact_id)
        assert src is not None and src.state == "ready"
        sha, size = _artifact_sha_size(
            _managed_root_of(api_client) / src.relative_path
        )
        assert (src.sha256, src.size_bytes) == (sha, size)

    # No staging leftovers, no false-ready proxy.
    assert _staging_files(_managed_root_of(api_client)) == []
    proxy_rows = [
        a
        for a in _ready_video_artifacts(session_factory, "default")
        if _owner_purposes(session_factory, a.id) == {ARTIFACT_PURPOSE_PROXY}
    ]
    assert proxy_rows == []


def test_orphan_cleanup_no_stray_jobs_or_files(
    worker, session_factory, api_client, cfr_cut_video, monkeypatch
) -> None:
    pid = _create_project(api_client, "S05C01 orphan cleanup")
    _upload_video(api_client, pid, cfr_cut_video)
    _submit_chain(api_client, pid, cfr_cut_video.name)
    _run_job(worker)
    _advance()
    chain = _get_chain(api_client, pid)
    proxy_job_id = chain["steps"]["proxy"]["job_id"]

    real_ffmpeg = video_proxy._run_ffmpeg

    def encode_then_http_cancel(ctx, cmd, *, timeout_seconds, staged_path):
        resp = api_client.post(f"/api/jobs/{proxy_job_id}/cancel")
        assert resp.status_code == 200
        return real_ffmpeg(ctx, cmd, timeout_seconds=timeout_seconds, staged_path=staged_path)

    monkeypatch.setattr(video_proxy, "_run_ffmpeg", encode_then_http_cancel)
    _run_job(worker)
    monkeypatch.undo()

    _advance()
    chain = _get_chain(api_client, pid)
    assert chain["chain_status"] == "cancelled"

    # Only the chain's own jobs exist for the video item: import + proxy.
    with session_factory() as s:
        chain_jobs = s.scalars(
            select(Job).where(
                Job.owner_type == "video_item",
                Job.owner_id == chain["video_item_id"],
            )
        ).all()
        assert len(chain_jobs) == 2
        assert {j.state for j in chain_jobs} == {"completed", "cancelled"}

    # No files outside the managed artifacts tree; staging empty.
    root = _managed_root_of(api_client).resolve()
    assert _staging_files(root) == []
    all_files = [p for p in root.rglob("*") if p.is_file()]
    for f in all_files:
        assert f.is_relative_to(root / "artifacts"), f"stray file: {f}"


# ── AC5: restart/resume without duplicate publication ───────────────────────


def test_restart_resume_no_duplicate_publication(
    worker, session_factory, db_path, api_client, cfr_cut_video
) -> None:
    pid = _create_project(api_client, "S05C01 restart")
    _upload_video(api_client, pid, cfr_cut_video)
    _submit_chain(api_client, pid, cfr_cut_video.name)

    # Phase 1 ("process 1"): import completes; the process is killed before
    # the proxy step is even materialized.
    _run_job(worker)
    _advance()
    chain = _get_chain(api_client, pid)
    assert chain["steps"]["import"]["status"] == "completed"
    assert chain["steps"]["proxy"]["status"] != "not_created"

    # Phase 2 ("restart"): a fresh engine + brand-new worker on the same DB.
    engine2 = create_engine_for_path(db_path)
    factory2 = create_session_factory(engine2)
    w2 = DurableWorker(
        factory2,
        config=WorkerConfig(
            worker_id="orchestration-worker-2",
            lease_ttl=60,
            heartbeat_interval=15,
            poll_interval=0.01,
            max_attempts=3,
            staging_root=_managed_root_of(api_client),
        ),
        clock=FakeClock(),
        sleeper=FakeSleeper(),
    )
    register_generate_proxy_handler(w2)
    register_scene_detection_handler(w2)

    # A brand-new orchestrator (the restarted process's orchestration
    # service) advances the chain against the same DB; the fresh worker
    # executes the new steps.  GET /analyze is used ONLY to read state.
    orch2 = AnalyzeChainOrchestrator(factory2, _managed_root_of(api_client))
    chain = _get_chain(api_client, pid)
    proxy_job_id = chain["steps"]["proxy"]["job_id"]
    assert w2.run_once() == 1
    assert _job_state(factory2, proxy_job_id) == "completed"
    orch2.advance_once()
    chain = _get_chain(api_client, pid)
    scene_job_id = chain["steps"]["scene_detect"]["job_id"]
    assert w2.run_once() == 1
    assert _job_state(factory2, scene_job_id) == "completed"
    orch2.advance_once()
    chain = _get_chain(api_client, pid)
    assert chain["chain_status"] == "completed"

    # Exactly one effect set per logical run — no duplicate publication.
    rows = _scene_rows(factory2, chain["video_item_id"])
    assert len(rows) == 2
    arts = _ready_video_artifacts(factory2, "default")
    assert len(arts) == 2  # one source + one proxy
    root = _managed_root_of(api_client).resolve()
    for art in arts:
        sha, size = _artifact_sha_size(root / art.relative_path)
        assert (art.sha256, art.size_bytes) == (sha, size)
    with factory2() as s:
        proxy_attempts = JobRepository(s).list_attempts(proxy_job_id)
        scene_attempts = JobRepository(s).list_attempts(scene_job_id)
    assert len(proxy_attempts) == 1
    assert len(scene_attempts) == 1
    assert _staging_files(root) == []


# ── Idempotent resubmission + validation ────────────────────────────────────


def test_idempotent_resubmission_reuses_chain(
    worker, session_factory, api_client, cfr_cut_video
) -> None:
    pid = _create_project(api_client, "S05C01 idempotent submit")
    _upload_video(api_client, pid, cfr_cut_video)
    first = _submit_chain(api_client, pid, cfr_cut_video.name)
    import_job_id = first["steps"]["import"]["job_id"]

    # Repeated submission reuses the SAME import job (never a duplicate).
    second = _submit_chain(api_client, pid, cfr_cut_video.name)
    assert second["steps"]["import"]["job_id"] == import_job_id
    third = _submit_chain(api_client, pid, cfr_cut_video.name)
    assert third["steps"]["import"]["job_id"] == import_job_id

    # The chain still completes normally after repeated submissions.
    chain = _drive_chain(worker, api_client, pid)
    assert chain["chain_status"] == "completed"
    with session_factory() as s:
        import_jobs = s.scalars(
            select(Job).where(
                Job.owner_type == "video_item",
                Job.owner_id == chain["video_item_id"],
            )
        ).all()
        import_count = sum(1 for j in import_jobs if j.id == import_job_id)
        assert import_count == 1


def test_retry_and_submit_validation(api_client, cfr_cut_video) -> None:
    # 404 for an unknown project.
    resp = api_client.post("/api/projects/nope/analyze", json={"generation": "1"})
    assert resp.status_code == 404
    resp = api_client.get("/api/projects/nope/analyze")
    assert resp.status_code == 404
    resp = api_client.post("/api/projects/nope/analyze/retry")
    assert resp.status_code == 404

    # 400 when no source video was uploaded.
    pid = _create_project(api_client, "S05C01 no video")
    resp = api_client.post(f"/api/projects/{pid}/analyze", json={"generation": "1"})
    assert resp.status_code == 400
    assert "Video file not found" in resp.json()["detail"]

    # 400 retry on a chain that has nothing to retry (idle/completed).
    resp = api_client.post(f"/api/projects/{pid}/analyze/retry")
    assert resp.status_code == 400

    # A completed chain rejects retry with a clear 400 (no successor for
    # completed logical runs, contract §8.1).
    _upload_video(api_client, pid, cfr_cut_video)
    # (chain is not driven here — the idle-state 400 above is the assertion;
    # driving requires the worker fixture, covered by other tests)
