"""S05-C02 — Durable chain progression correction (Codex CHANGES_REQUESTED).

Independent adversarial tests proving the correction contract through the
REAL UI-facing API surface and the REAL durable services on real synthetic
media (CFR + VFR fixtures generated by ffmpeg under ``tmp_path``; never mock
data):

1. ``test_post_once_no_get_chain_completes_under_orchestrator`` — exactly
   one ``POST /api/projects/{id}/analyze``; NO ``GET /analyze`` polling at
   all; the backend orchestration loop + durable worker complete
   T02→T03→T04 under backend ownership.
2. ``test_api_restart_after_import_and_after_proxy_chain_completes`` — the
   API process restarts (fresh engines/factories/workers/orchestrators over
   the same database file) after import and after proxy; the chain
   completes with exactly one effect set.
3. ``test_get_repeated_and_concurrent_zero_db_mutations`` — repeated and
   concurrent GETs cause ZERO database mutations (job rows, artifacts,
   scene rows, events, attempts, leases, files).
4. ``test_replace_source_video_stale_chain_not_reused`` — replacing the
   project source with a different video (same project, same default
   generation) binds a NEW chain identity (source SHA-256 + generation);
   the stale chain's jobs/artifacts are never silently reused.
5. ``test_concurrent_advancement_exactly_one_successor_per_step`` —
   concurrent advancement creates exactly one successor per step
   (lease/fencing + idempotency keys respected).
6. ``test_failure_successor_retry_idempotent`` +
   ``test_cancel_successor_retry_idempotent`` — failure/cancel successor
   retry stays idempotent (duplicate retry reuses the successor).
7. ``test_cfr_chain_containment_sha_size_scene_ids_orphan_cleanup`` —
   CFR completes through the chain; containment, SHA/size, stable Scene
   IDs and orphan-cleanup regressions.

Every test reads chain state through the READ-ONLY ``GET /analyze`` (used
only for assertions) or directly from durable rows — advancement is always
owned by the orchestrator (``advance_once`` / its background loop), never
by a read endpoint.
"""

from __future__ import annotations

import hashlib
import shutil
import subprocess
import threading
import time
from collections.abc import Iterator
from datetime import UTC, datetime, timedelta
from pathlib import Path

import pytest
from alembic import command
from alembic.config import Config
from sqlalchemy import select
from sqlalchemy.orm import Session

from app.persistence import (
    JobRepository,
    create_engine_for_path,
    create_session_factory,
)
from app.persistence.models import (
    Artifact,
    ArtifactOwner,
    Job,
    JobAttempt,
    JobEvent,
    JobLease,
    JobStep,
    Project,
    Scene,
    VideoItem,
    Workspace,
)
from app.services import scene_detector, video_import, video_proxy
from app.services.scene_detector import (
    CODE_SCENE_DETECT_FAILED,
    register_scene_detection_handler,
)
from app.services.video_proxy import (
    register_generate_proxy_handler,
)
from app.workflow import analyze_orchestrator as ao_module
from app.workflow.analyze_orchestrator import AnalyzeChainOrchestrator
from app.workflow.durable_worker import DurableWorker, WorkerConfig

PROJECT_ROOT = Path(__file__).resolve().parent.parent
ALEMBIC_INI = PROJECT_ROOT / "alembic.ini"


# ── Deterministic clock/sleeper (mirror test_s05_orchestration) ─────────────


class FakeClock:
    def __init__(self, start: datetime | None = None) -> None:
        self.now = start or datetime(2026, 8, 5, 12, 0, 0, tzinfo=UTC)

    def __call__(self) -> datetime:
        return self.now

    def advance(self, seconds: float) -> None:
        self.now += timedelta(seconds=seconds)


class FakeSleeper:
    def __init__(self) -> None:
        self.calls: list[float] = []

    def __call__(self, seconds: float) -> None:
        self.calls.append(seconds)


# ── DB fixtures ──────────────────────────────────────────────────────────────


def _alembic_config(database_path: Path) -> Config:
    cfg = Config(str(ALEMBIC_INI))
    cfg.set_main_option("script_location", str(PROJECT_ROOT / "migrations"))
    cfg.set_main_option("sqlalchemy.url", f"sqlite:///{database_path.as_posix()}")
    return cfg


def _upgrade(database_path: Path) -> None:
    command.upgrade(_alembic_config(database_path), "head")


@pytest.fixture()
def db_path(tmp_path: Path) -> Path:
    return tmp_path / "chain_progression.db"


@pytest.fixture()
def session_factory(db_path: Path):
    _upgrade(db_path)
    return create_session_factory(create_engine_for_path(db_path))


@pytest.fixture()
def session(session_factory) -> Iterator[Session]:
    with session_factory() as s:
        yield s


@pytest.fixture()
def managed_root(tmp_path: Path) -> Path:
    root = tmp_path / "managed"
    root.mkdir(exist_ok=True)
    return root


@pytest.fixture()
def worker(session_factory, managed_root: Path) -> DurableWorker:
    """A worker with fake clock/sleeper and the full S05 handler set."""
    w = DurableWorker(
        session_factory,
        config=WorkerConfig(
            worker_id="chain-progression-worker",
            lease_ttl=60,
            heartbeat_interval=15,
            poll_interval=0.01,
            max_attempts=3,
            staging_root=managed_root,
        ),
        clock=FakeClock(),
        sleeper=FakeSleeper(),
    )
    register_generate_proxy_handler(w)
    register_scene_detection_handler(w)
    return w


@pytest.fixture()
def api_client(session_factory, managed_root: Path, db_path: Path):
    """TestClient over the real FastAPI app with deps pointed at the same
    database + managed root — the exact UI-facing surface."""
    from fastapi.testclient import TestClient

    from app.api import deps
    from app.api.app import app
    from app.config import AppConfig
    from app.workflow.job_service import JobService
    from app.workflow.project_workflow import ProjectWorkflowService

    cfg = AppConfig(
        project_root=db_path.parent / "proj",
        models_dir=db_path.parent / "proj" / "models",
        output_dir=db_path.parent / "proj" / "output",
    )
    saved = (
        getattr(deps, "_config", None),
        getattr(deps, "_project_wf", None),
        getattr(deps, "_job_service", None),
        getattr(deps, "_lifecycle_db", None),
    )
    deps._config = cfg
    deps._project_wf = ProjectWorkflowService(cfg)
    deps._job_service = JobService(session_factory, managed_root=managed_root)
    deps._lifecycle_db = db_path
    client = TestClient(app, raise_server_exceptions=True)
    yield client
    (
        deps._config,
        deps._project_wf,
        deps._job_service,
        deps._lifecycle_db,
    ) = saved
    ao_module.reset_analyze_orchestrator()


# ── Synthetic media fixtures (real ffmpeg → tmp_path) ───────────────────────


def _ffmpeg_available() -> bool:
    try:
        from app.services.ffmpeg_utils import find_ffprobe

        find_ffprobe()
        return shutil.which("ffmpeg") is not None
    except Exception:
        return False


def _make_cut_video(
    path: Path, *, fps: int = 30, rate: str | None = None, crf: int = 28
) -> Path | None:
    """A 2s/60-frame clip with ONE hard cut: blue (1s) → red (1s)."""
    ffmpeg = shutil.which("ffmpeg") or "ffmpeg"
    path.parent.mkdir(parents=True, exist_ok=True)
    rate_arg = rate or str(fps)
    cmd = [
        ffmpeg,
        "-y",
        "-f",
        "lavfi",
        "-i",
        f"color=c=blue:duration=1.0:size=320x240:rate={rate_arg}",
        "-f",
        "lavfi",
        "-i",
        f"color=c=red:duration=1.0:size=320x240:rate={rate_arg}",
        "-filter_complex",
        "[0:v][1:v]concat=n=2:v=1:a=0[v]",
        "-map",
        "[v]",
        "-c:v",
        "libx264",
        "-preset",
        "ultrafast",
        "-crf",
        str(crf),
        "-pix_fmt",
        "yuv420p",
        str(path),
    ]
    result = subprocess.run(cmd, capture_output=True, text=True, timeout=60)
    if result.returncode != 0:
        return None
    return path


def _make_video(
    path: Path,
    *,
    duration: float = 1.0,
    fps: int = 30,
    color: str = "blue",
) -> Path | None:
    """Create a CFR synthetic MP4/H.264 clip (static color)."""
    ffmpeg = shutil.which("ffmpeg") or "ffmpeg"
    path.parent.mkdir(parents=True, exist_ok=True)
    cmd = [
        ffmpeg,
        "-y",
        "-f",
        "lavfi",
        "-i",
        f"color=c={color}:duration={duration}:size=320x240:rate={fps}",
        "-c:v",
        "libx264",
        "-preset",
        "ultrafast",
        "-crf",
        "28",
        "-pix_fmt",
        "yuv420p",
        str(path),
    ]
    result = subprocess.run(cmd, capture_output=True, text=True, timeout=60)
    if result.returncode != 0:
        return None
    return path


def _make_vfr_cut_video(tmp_path: Path, name: str = "vfr.mp4") -> Path | None:
    """A real VFR MP4 with one hard cut (30fps blue + 25fps red, -c copy)."""
    ffmpeg = shutil.which("ffmpeg") or "ffmpeg"
    seg1 = tmp_path / "seg30.mp4"
    seg2 = tmp_path / "seg25.mp4"
    for seg, fps, color in ((seg1, 30, "blue"), (seg2, 25, "red")):
        made = _make_video(seg, duration=1.0, fps=fps, color=color)
        assert made is not None, "ffmpeg failed to create a VFR segment"
    lst = tmp_path / "concat.txt"
    lst.write_text(f"file '{seg1.as_posix()}'\nfile '{seg2.as_posix()}'\n", encoding="utf-8")
    out = tmp_path / name
    result = subprocess.run(
        [
            ffmpeg,
            "-y",
            "-f",
            "concat",
            "-safe",
            "0",
            "-i",
            str(lst),
            "-c",
            "copy",
            "-movflags",
            "+faststart",
            str(out),
        ],
        capture_output=True,
        text=True,
        timeout=60,
    )
    if result.returncode != 0:
        pytest.skip("ffmpeg concat failed to create the VFR fixture")
    probe = video_import.probe_source(out)
    video = probe["video_stream"]
    if video["r_frame_rate"] == video["avg_frame_rate"]:
        pytest.skip("concat output is not genuinely VFR on this ffmpeg build")
    return out


@pytest.fixture()
def cfr_cut_video(tmp_path: Path) -> Path:
    if not _ffmpeg_available():
        pytest.skip("ffmpeg/ffprobe not available")
    out = _make_cut_video(tmp_path / "cfr_cut.mp4", fps=30)
    assert out is not None, "ffmpeg failed to create the CFR cut fixture"
    return out


@pytest.fixture()
def vfr_cut_video(tmp_path: Path) -> Path:
    if not _ffmpeg_available():
        pytest.skip("ffmpeg/ffprobe not available")
    out = _make_vfr_cut_video(tmp_path)
    assert out is not None, "ffmpeg failed to create the VFR cut fixture"
    return out


# ── API / orchestrator helpers ──────────────────────────────────────────────


def _create_project(api_client, name: str) -> str:
    resp = api_client.post("/api/projects", json={"name": name})
    assert resp.status_code == 201, resp.text
    return resp.json()["project_id"]


def _upload_video(api_client, project_id: str, source: Path) -> None:
    with source.open("rb") as handle:
        resp = api_client.post(
            f"/api/projects/{project_id}/video",
            files={"file": (source.name, handle, "video/mp4")},
        )
    assert resp.status_code == 200, resp.text


def _submit_chain(api_client, project_id: str, title: str | None = None) -> dict:
    resp = api_client.post(
        f"/api/projects/{project_id}/analyze",
        json={"generation": "1", "title": title},
    )
    assert resp.status_code == 200, resp.text
    return resp.json()


def _get_chain(api_client, project_id: str) -> dict:
    resp = api_client.get(f"/api/projects/{project_id}/analyze")
    assert resp.status_code == 200, resp.text
    return resp.json()


def _run_job(worker: DurableWorker) -> None:
    worker.run_once()


def _job_state(session_factory, job_id: str) -> str:
    with session_factory() as s:
        return JobRepository(s).get_job(job_id).state


def _chain_jobs(session_factory, video_item_id: str) -> list[Job]:
    with session_factory() as s:
        return list(
            s.scalars(
                select(Job)
                .where(
                    Job.owner_type == "video_item",
                    Job.owner_id == video_item_id,
                )
                .order_by(Job.created_at)
            ).all()
        )


def _scene_rows(session_factory, video_item_id: str) -> list[Scene]:
    with session_factory() as s:
        return list(
            s.scalars(
                select(Scene)
                .where(Scene.video_item_id == video_item_id)
                .order_by(Scene.position)
            ).all()
        )


def _staging_files(managed_root: Path) -> list[Path]:
    staging = managed_root / "staging"
    if not staging.is_dir():
        return []
    return [p for p in staging.rglob("*") if p.is_file()]


def _ready_video_artifacts(session_factory, workspace_id: str) -> list[Artifact]:
    with session_factory() as s:
        return list(
            s.scalars(
                select(Artifact)
                .where(
                    Artifact.workspace_id == workspace_id,
                    Artifact.kind == "video",
                    Artifact.state == "ready",
                )
                .order_by(Artifact.relative_path)
            ).all()
        )


def _artifact_sha_size(path: Path) -> tuple[str, int]:
    return hashlib.sha256(path.read_bytes()).hexdigest(), path.stat().st_size


def _owner_purposes(session_factory, artifact_id: str) -> set[str]:
    with session_factory() as s:
        return set(
            s.scalars(
                select(ArtifactOwner.purpose).where(ArtifactOwner.artifact_id == artifact_id)
            ).all()
        )


def _fast_orchestrator(
    session_factory, managed_root: Path, monkeypatch
) -> AnalyzeChainOrchestrator:
    """A fast-polling orchestrator injected as the route's accessor."""
    orch = AnalyzeChainOrchestrator(
        session_factory,
        managed_root,
        poll_interval=0.01,
    )
    monkeypatch.setattr(ao_module, "get_analyze_orchestrator", lambda: orch)
    return orch


def _drive_to_terminal(worker, session_factory, video_item_id: str, max_rounds: int = 20) -> None:
    """Worker + explicit orchestrator advancement (backend ownership) until
    the chain's scene job is terminal — repository reads only."""
    for _ in range(max_rounds):
        _run_job(worker)
        ao_module.get_analyze_orchestrator().advance_once()
        jobs = _chain_jobs(session_factory, video_item_id)
        if len(jobs) >= 3 and jobs[-1].state in ("completed", "failed", "cancelled"):
            return
    raise AssertionError("chain did not reach a terminal scene state")


def _db_snapshot(session_factory, managed_root: Path) -> dict:
    """Every durable row (as plain tuples) + every managed file path."""
    tables: dict[str, list] = {}
    models = (
        Job,
        JobStep,
        JobAttempt,
        JobEvent,
        JobLease,
        Artifact,
        ArtifactOwner,
        Scene,
        VideoItem,
        Project,
        Workspace,
    )
    with session_factory() as s:
        for model in models:
            rows = s.execute(select(model)).scalars().all()
            cols = list(model.__table__.columns.keys())
            tables[model.__name__] = sorted(tuple(getattr(r, c) for c in cols) for r in rows)
    files = sorted(str(p.relative_to(managed_root)) for p in managed_root.rglob("*") if p.is_file())
    return {"tables": tables, "files": files}


# ── AC: POST once, NO GET — chain completes under orchestrator+worker ───────


def test_post_once_no_get_chain_completes_under_orchestrator(
    worker, session_factory, managed_root, api_client, cfr_cut_video, monkeypatch
) -> None:
    """Exactly ONE POST /analyze; NO GET /analyze at all; the backend
    orchestration loop + durable worker complete T02→T03→T04."""
    pid = _create_project(api_client, "S05C02 no-get")
    _upload_video(api_client, pid, cfr_cut_video)

    orch = _fast_orchestrator(session_factory, managed_root, monkeypatch)
    try:
        resp = api_client.post(
            f"/api/projects/{pid}/analyze",
            json={"generation": "1", "title": "no-get"},
        )
        assert resp.status_code == 200, resp.text
        state = resp.json()
        import_job_id = state["steps"]["import"]["job_id"]
        assert import_job_id is not None
        assert state["steps"]["proxy"]["status"] == "not_created"
        assert state["steps"]["scene_detect"]["status"] == "not_created"
        assert state["source_sha256"] == hashlib.sha256(cfr_cut_video.read_bytes()).hexdigest()

        # NO GET /analyze from here on.  The orchestrator's background loop
        # (started by the POST) advances the chain; the worker executes.
        deadline = time.monotonic() + 90
        while time.monotonic() < deadline:
            _run_job(worker)
            with session_factory() as s:
                jobs = list(
                    s.scalars(
                        select(Job)
                        .where(Job.owner_type == "video_item")
                        .order_by(Job.created_at)
                    ).all()
                )
            if len(jobs) >= 3:
                last = jobs[-1]
                if last.state in ("completed", "failed", "cancelled"):
                    break
            time.sleep(0.02)
        else:
            raise AssertionError("chain did not complete under the orchestrator loop")

        jobs = _chain_jobs(session_factory, state["video_item_id"])
        assert [j.job_type for j in jobs] == [
            video_import.JOB_TYPE_ANALYZE_MEDIA,
            video_proxy.JOB_TYPE_GENERATE_PROXY,
            video_import.JOB_TYPE_ANALYZE_MEDIA,
        ]
        assert [j.state for j in jobs] == ["completed", "completed", "completed"]
        assert _scene_rows(session_factory, state["video_item_id"]) != []
        assert _staging_files(managed_root) == []
    finally:
        orch.stop(timeout=2.0)


# ── AC: API process restart after import and after proxy ────────────────────


def test_api_restart_after_import_and_after_proxy_chain_completes(
    worker, session_factory, db_path, managed_root, api_client, cfr_cut_video, monkeypatch
) -> None:
    """The API process restarts after import and after proxy (fresh
    engines, workers AND orchestrators over the same database file); the
    chain completes with exactly one effect set per step."""
    pid = _create_project(api_client, "S05C02 restart")
    _upload_video(api_client, pid, cfr_cut_video)
    orch1 = _fast_orchestrator(session_factory, managed_root, monkeypatch)

    state = _submit_chain(api_client, pid, cfr_cut_video.name)
    import_job_id = state["steps"]["import"]["job_id"]
    orch1.stop(timeout=2.0)  # deterministic explicit advancement from here

    # Process 1: import completes.
    _run_job(worker)
    assert _job_state(session_factory, import_job_id) == "completed"
    orch1.advance_once()
    jobs = _chain_jobs(session_factory, state["video_item_id"])
    assert len(jobs) == 2
    proxy_job_id = jobs[1].id

    # "API process restart" after import: fresh engine + worker +
    # orchestrator on the same DB file.
    factory2 = create_session_factory(create_engine_for_path(db_path))
    w2 = DurableWorker(
        factory2,
        config=WorkerConfig(
            worker_id="chain-progression-worker-2",
            lease_ttl=60,
            heartbeat_interval=15,
            poll_interval=0.01,
            max_attempts=3,
            staging_root=managed_root,
        ),
        clock=FakeClock(),
        sleeper=FakeSleeper(),
    )
    register_generate_proxy_handler(w2)
    register_scene_detection_handler(w2)
    orch2 = AnalyzeChainOrchestrator(factory2, managed_root)

    assert w2.run_once() == 1  # claims the queued proxy job
    assert _job_state(factory2, proxy_job_id) == "completed"
    orch2.advance_once()
    jobs = _chain_jobs(factory2, state["video_item_id"])
    assert len(jobs) == 3
    scene_job_id = jobs[2].id

    # "API process restart" after proxy: yet another fresh process.
    factory3 = create_session_factory(create_engine_for_path(db_path))
    w3 = DurableWorker(
        factory3,
        config=WorkerConfig(
            worker_id="chain-progression-worker-3",
            lease_ttl=60,
            heartbeat_interval=15,
            poll_interval=0.01,
            max_attempts=3,
            staging_root=managed_root,
        ),
        clock=FakeClock(),
        sleeper=FakeSleeper(),
    )
    register_scene_detection_handler(w3)
    orch3 = AnalyzeChainOrchestrator(factory3, managed_root)

    assert w3.run_once() == 1  # claims the queued scene job
    assert _job_state(factory3, scene_job_id) == "completed"
    orch3.advance_once()

    # Terminal: every chain job completed, exactly one effect set.
    assert [_job_state(factory3, j.id) for j in _chain_jobs(factory3, state["video_item_id"])] == [
        "completed",
        "completed",
        "completed",
    ]
    rows = _scene_rows(factory3, state["video_item_id"])
    assert len(rows) == 2
    arts = _ready_video_artifacts(factory3, "default")
    assert len(arts) == 2  # exactly one source + one proxy
    root = managed_root.resolve()
    for art in arts:
        sha, size = _artifact_sha_size(root / art.relative_path)
        assert (art.sha256, art.size_bytes) == (sha, size)
    with factory3() as s:
        assert len(JobRepository(s).list_attempts(proxy_job_id)) == 1
        assert len(JobRepository(s).list_attempts(scene_job_id)) == 1
    assert _staging_files(root) == []


# ── AC: GET repeated/concurrent → ZERO DB mutations ─────────────────────────


def test_get_repeated_and_concurrent_zero_db_mutations(
    worker, session_factory, managed_root, api_client, cfr_cut_video, monkeypatch
) -> None:
    """Repeated AND concurrent GET /analyze cause zero database mutations
    (job rows, steps, attempts, events, leases, artifacts, owners, scenes,
    video items, projects, managed files)."""
    pid = _create_project(api_client, "S05C02 get readonly")
    _upload_video(api_client, pid, cfr_cut_video)
    orch = _fast_orchestrator(session_factory, managed_root, monkeypatch)
    _submit_chain(api_client, pid, cfr_cut_video.name)
    orch.stop(timeout=2.0)
    with session_factory() as s:
        item_id = s.scalar(select(VideoItem.id).where(VideoItem.project_id == pid))
    assert item_id is not None
    _drive_to_terminal(worker, session_factory, item_id)

    before = _db_snapshot(session_factory, managed_root)
    assert _job_state(session_factory, _chain_jobs(session_factory, item_id)[0].id) == "completed"

    # Repeated GETs: 200 + byte-identical chain JSON every time.
    first_json = None
    for _ in range(25):
        resp = api_client.get(f"/api/projects/{pid}/analyze")
        assert resp.status_code == 200, resp.text
        payload = resp.json()
        if first_json is None:
            first_json = payload
        else:
            assert payload == first_json
    assert first_json["chain_status"] == "completed"

    # Concurrent GETs: 6 threads, barrier-synchronized.
    errors: list[Exception] = []
    results: list[dict] = []

    def hammer() -> None:
        barrier.wait(timeout=10)
        try:
            resp = api_client.get(f"/api/projects/{pid}/analyze")
            assert resp.status_code == 200, resp.text
            results.append(resp.json())
        except Exception as exc:  # noqa: BLE001 - collected
            errors.append(exc)

    barrier = threading.Barrier(6)
    threads = [threading.Thread(target=hammer) for _ in range(6)]
    for t in threads:
        t.start()
    for t in threads:
        t.join(timeout=30)
    assert errors == []
    assert len(results) == 6
    for payload in results:
        assert payload == first_json

    after = _db_snapshot(session_factory, managed_root)
    assert after == before

    # GET on a NEVER-submitted project creates nothing (no durable shell).
    pid2 = _create_project(api_client, "S05C02 idle get")
    before2 = _db_snapshot(session_factory, managed_root)
    for _ in range(5):
        resp = api_client.get(f"/api/projects/{pid2}/analyze")
        assert resp.status_code == 200
        assert resp.json()["chain_status"] == "idle"
    assert _db_snapshot(session_factory, managed_root) == before2


# ── AC: source replacement → stale chain NOT reused ─────────────────────────


def test_replace_source_video_stale_chain_not_reused(
    worker, session_factory, managed_root, api_client, cfr_cut_video, monkeypatch
) -> None:
    """Replacing the project source with a different video (same project,
    same default generation) performs an explicit VideoItem/version
    supersession (S05-C03): the old VideoItem is ARCHIVED with its
    jobs/artifacts/scenes immutable; the new source gets a DISTINCT
    VideoItem identity and outputs; the NEW chain reaches completed; chain
    state exposes only the current source.  The stale chain's jobs and
    artifacts are never silently reused."""
    pid = _create_project(api_client, "S05C02 replace source")
    _upload_video(api_client, pid, cfr_cut_video)
    orch = _fast_orchestrator(session_factory, managed_root, monkeypatch)

    first = _submit_chain(api_client, pid, cfr_cut_video.name)
    orch.stop(timeout=2.0)
    item_a = first["video_item_id"]
    _drive_to_terminal(worker, session_factory, item_a)

    jobs_a = _chain_jobs(session_factory, item_a)
    import_a, proxy_a, scene_a = jobs_a
    assert [j.state for j in jobs_a] == ["completed", "completed", "completed"]
    proxy_artifact_a = _get_chain(api_client, pid)["proxy_artifact_id"]
    scene_ids_a = [r.id for r in _scene_rows(session_factory, item_a)]
    sha_a = _get_chain(api_client, pid)["source_sha256"]
    assert sha_a == hashlib.sha256(cfr_cut_video.read_bytes()).hexdigest()

    # ── (a) Replacement with DIFFERENT evidence (24fps green clip): the
    # supersession archives the old VideoItem (rows immutable) and creates
    # a NEW VideoItem; the new chain COMPLETES on fresh rows — never a
    # silent reuse of the completed import/proxy/scene of the old source.
    replacement = _make_video(
        managed_root.parent / "replacement.mp4",
        duration=1.0,
        fps=24,
        color="green",
    )
    assert replacement is not None, "ffmpeg failed to create the replacement fixture"
    assert replacement.read_bytes() != cfr_cut_video.read_bytes()
    _upload_video(api_client, pid, replacement)

    second = _submit_chain(api_client, pid, "replacement")
    orch.stop(timeout=2.0)
    sha_b = hashlib.sha256(replacement.read_bytes()).hexdigest()
    item_b = second["video_item_id"]
    assert item_b != item_a  # DISTINCT VideoItem identity
    assert second["source_sha256"] == sha_b
    assert second["source_sha256"] != sha_a

    # Old VideoItem archived; old rows terminal and immutable.
    with session_factory() as s:
        old = s.get(VideoItem, item_a)
        assert old is not None and old.status == "archived"
        assert old.archived_at is not None
    assert _job_state(session_factory, import_a.id) == "completed"
    assert _job_state(session_factory, proxy_a.id) == "completed"
    assert _job_state(session_factory, scene_a.id) == "completed"
    assert [r.id for r in _scene_rows(session_factory, item_a)] == scene_ids_a

    # The NEW chain completes with new jobs and new outputs.
    _drive_to_terminal(worker, session_factory, item_b)
    jobs_b = _chain_jobs(session_factory, item_b)
    assert len(jobs_b) == 3
    new_import_b, new_proxy_b, new_scene_b = jobs_b
    assert new_import_b.id != import_a.id
    assert new_proxy_b.id != proxy_a.id
    assert new_scene_b.id != scene_a.id
    assert [j.state for j in jobs_b] == ["completed", "completed", "completed"]
    rows_b = _scene_rows(session_factory, item_b)
    assert rows_b != []  # fresh scene evidence on the NEW item
    assert [r.id for r in rows_b] != scene_ids_a  # never the old scene rows

    mid = _get_chain(api_client, pid)
    assert mid["video_item_id"] == item_b  # only the CURRENT source
    assert mid["source_sha256"] == sha_b
    assert mid["proxy_artifact_id"] != proxy_artifact_a  # never the stale artifact
    assert mid["proxy_artifact_id"] is not None
    assert mid["scenes_count"] == len(rows_b)

    # The archived chain is frozen — no successor jobs after supersession.
    assert len(_chain_jobs(session_factory, item_a)) == 3
    assert _staging_files(managed_root) == []

    # ── (b) Replacement with IDENTICAL evidence (same 30fps cut grid,
    # different bytes → different SHA): a THIRD superseding VideoItem; the
    # new chain completes; rows are never reused across identities.
    reencoded = _make_cut_video(managed_root.parent / "reencoded.mp4", fps=30, crf=30)
    assert reencoded is not None, "ffmpeg failed to create the re-encoded fixture"
    _upload_video(api_client, pid, reencoded)
    third = _submit_chain(api_client, pid, "reencoded")
    orch.stop(timeout=2.0)
    sha_c = hashlib.sha256(reencoded.read_bytes()).hexdigest()
    item_c = third["video_item_id"]
    assert item_c not in (item_a, item_b)  # another DISTINCT identity
    assert third["source_sha256"] == sha_c
    assert sha_c != sha_a
    _drive_to_terminal(worker, session_factory, item_c)

    jobs_c = _chain_jobs(session_factory, item_c)
    assert len(jobs_c) == 3
    new_import_c, new_proxy_c, new_scene_c = jobs_c
    assert new_import_c.id not in (import_a.id, new_import_b.id)
    assert new_proxy_c.id not in (proxy_a.id, new_proxy_b.id)
    assert new_scene_c.id not in (scene_a.id, new_scene_b.id)
    assert [j.state for j in jobs_c] == ["completed", "completed", "completed"]
    final = _get_chain(api_client, pid)
    assert final["video_item_id"] == item_c  # only the CURRENT source
    assert final["source_sha256"] == sha_c
    assert final["proxy_artifact_id"] != proxy_artifact_a
    assert final["proxy_artifact_id"] != mid["proxy_artifact_id"]
    assert final["scenes_count"] == len(_scene_rows(session_factory, item_c))

    # Everything before stays immutable and frozen.
    assert len(_chain_jobs(session_factory, item_a)) == 3
    assert len(_chain_jobs(session_factory, item_b)) == 3
    assert [r.id for r in _scene_rows(session_factory, item_a)] == scene_ids_a
    assert [r.id for r in _scene_rows(session_factory, item_b)] == [
        r.id for r in rows_b
    ]
    assert _staging_files(managed_root) == []


# ── AC: concurrent advancement → exactly one successor per step ─────────────


def test_concurrent_advancement_exactly_one_successor_per_step(
    worker, session_factory, managed_root, api_client, cfr_cut_video, monkeypatch
) -> None:
    """Concurrent advancement creates exactly one successor per step —
    the repository's idempotency keys + guarded creation decide the race."""
    pid = _create_project(api_client, "S05C02 concurrent advance")
    _upload_video(api_client, pid, cfr_cut_video)
    orch = _fast_orchestrator(session_factory, managed_root, monkeypatch)
    state = _submit_chain(api_client, pid, cfr_cut_video.name)
    orch.stop(timeout=2.0)  # only the explicit concurrent passes may advance
    item_id = state["video_item_id"]

    _run_job(worker)  # import completes
    assert _job_state(session_factory, state["steps"]["import"]["job_id"]) == "completed"

    barrier = threading.Barrier(8)
    reports: list[object] = []

    def hammer() -> None:
        barrier.wait(timeout=10)
        reports.append(ao_module.get_analyze_orchestrator().advance_once())

    threads = [threading.Thread(target=hammer) for _ in range(8)]
    for t in threads:
        t.start()
    for t in threads:
        t.join(timeout=30)

    with session_factory() as s:
        from sqlalchemy import func

        proxy_count = s.scalar(
            select(func.count())
            .select_from(Job)
            .where(
                Job.owner_type == "video_item",
                Job.owner_id == item_id,
                Job.idempotency_key.like("GENERATE_PROXY:%"),
            )
        )
        assert proxy_count == 1  # exactly one proxy successor
        proxy_job_id = s.scalar(
            select(Job.id).where(
                Job.owner_type == "video_item",
                Job.owner_id == item_id,
                Job.idempotency_key.like("GENERATE_PROXY:%"),
            )
        )

    _run_job(worker)  # proxy completes
    assert _job_state(session_factory, proxy_job_id) == "completed"

    barrier = threading.Barrier(8)
    reports = []

    def hammer2() -> None:
        barrier.wait(timeout=10)
        reports.append(ao_module.get_analyze_orchestrator().advance_once())

    threads = [threading.Thread(target=hammer2) for _ in range(8)]
    for t in threads:
        t.start()
    for t in threads:
        t.join(timeout=30)

    with session_factory() as s:
        from sqlalchemy import func

        scene_count = s.scalar(
            select(func.count())
            .select_from(Job)
            .where(
                Job.owner_type == "video_item",
                Job.owner_id == item_id,
                Job.idempotency_key.like("ANALYZE_MEDIA:scene_detect:%"),
            )
        )
        assert scene_count == 1  # exactly one scene successor

    # The surviving successors complete normally.
    _run_job(worker)
    jobs = _chain_jobs(session_factory, item_id)
    assert len(jobs) == 3
    assert [j.state for j in jobs] == ["completed", "completed", "completed"]
    assert len(_scene_rows(session_factory, item_id)) == 2


# ── AC: failure/cancel successor retry stays idempotent ─────────────────────


def test_failure_successor_retry_idempotent(
    worker, session_factory, managed_root, api_client, cfr_cut_video, monkeypatch
) -> None:
    """A failed scene step is retried via the orchestrator's successor
    path; duplicate retries reuse the same successor (contract §8.5)."""
    pid = _create_project(api_client, "S05C02 retry failed")
    _upload_video(api_client, pid, cfr_cut_video)
    orch = _fast_orchestrator(session_factory, managed_root, monkeypatch)
    state = _submit_chain(api_client, pid, cfr_cut_video.name)
    orch.stop(timeout=2.0)
    item_id = state["video_item_id"]

    _run_job(worker)  # import
    orch.advance_once()
    _run_job(worker)  # proxy
    orch.advance_once()
    jobs = _chain_jobs(session_factory, item_id)
    scene_job_id = jobs[2].id

    def fail_detect(ctx, input_path, profile, timebase):
        raise scene_detector.SceneDetectorError(
            CODE_SCENE_DETECT_FAILED, "injected detection failure"
        )

    monkeypatch.setattr(scene_detector, "_run_scene_detect", fail_detect)
    _run_job(worker)
    monkeypatch.undo()
    assert _job_state(session_factory, scene_job_id) == "failed"

    # Successor retry via the orchestrator (the retry endpoint's surface).
    retry1 = ao_module.get_analyze_orchestrator().retry_chain(pid)
    assert retry1 is not None
    successor_id = retry1["steps"]["scene_detect"]["job_id"]
    assert successor_id != scene_job_id
    assert retry1["steps"]["scene_detect"]["predecessor_job_id"] == scene_job_id
    assert _job_state(session_factory, scene_job_id) == "failed"  # immutable

    # Duplicate retries reuse the successor — never a 409/500.
    retry2 = ao_module.get_analyze_orchestrator().retry_chain(pid)
    assert retry2 is not None
    assert retry2["steps"]["scene_detect"]["job_id"] == successor_id
    retry3 = ao_module.get_analyze_orchestrator().retry_chain(pid)
    assert retry3 is not None
    assert retry3["steps"]["scene_detect"]["job_id"] == successor_id

    # The successor completes with exactly one effect set.
    _run_job(worker)
    assert _job_state(session_factory, successor_id) == "completed"
    rows = _scene_rows(session_factory, item_id)
    assert len(rows) == 2
    assert all(r.revision == 1 for r in rows)
    assert _staging_files(managed_root) == []


def test_cancel_successor_retry_idempotent(
    worker, session_factory, managed_root, api_client, cfr_cut_video, monkeypatch
) -> None:
    """A cancelled step is retried via a successor that completes; the
    predecessor stays terminal-cancelled and nothing is duplicated."""
    pid = _create_project(api_client, "S05C02 retry cancelled")
    _upload_video(api_client, pid, cfr_cut_video)
    orch = _fast_orchestrator(session_factory, managed_root, monkeypatch)
    state = _submit_chain(api_client, pid, cfr_cut_video.name)
    orch.stop(timeout=2.0)
    item_id = state["video_item_id"]

    _run_job(worker)  # import
    orch.advance_once()
    _run_job(worker)  # proxy
    orch.advance_once()
    jobs = _chain_jobs(session_factory, item_id)
    scene_job_id = jobs[2].id

    real_detect = scene_detector._run_scene_detect

    def detect_then_cancel(ctx, input_path, profile, timebase):
        resp = api_client.post(f"/api/jobs/{scene_job_id}/cancel")
        assert resp.status_code == 200
        return real_detect(ctx, input_path, profile, timebase)

    monkeypatch.setattr(scene_detector, "_run_scene_detect", detect_then_cancel)
    _run_job(worker)
    monkeypatch.undo()
    assert _job_state(session_factory, scene_job_id) == "cancelled"
    assert _scene_rows(session_factory, item_id) == []
    assert _staging_files(managed_root) == []

    retry1 = ao_module.get_analyze_orchestrator().retry_chain(pid)
    assert retry1 is not None
    successor_id = retry1["steps"]["scene_detect"]["job_id"]
    assert successor_id != scene_job_id
    retry2 = ao_module.get_analyze_orchestrator().retry_chain(pid)
    assert retry2 is not None
    assert retry2["steps"]["scene_detect"]["job_id"] == successor_id

    _run_job(worker)
    assert _job_state(session_factory, successor_id) == "completed"
    rows = _scene_rows(session_factory, item_id)
    assert len(rows) == 2
    with session_factory() as s:
        pred = JobRepository(s).get_job(scene_job_id)
        succ = JobRepository(s).get_job(successor_id)
        assert pred.state == "cancelled"  # terminal predecessor immutable
        assert succ.predecessor_job_id == scene_job_id
        assert succ.idempotency_key == pred.idempotency_key  # same logical key
    assert _staging_files(managed_root) == []


# ── AC: CFR + VFR, containment, SHA/size, Scene IDs, orphan cleanup ─────────


def test_cfr_chain_containment_sha_size_scene_ids_orphan_cleanup(
    worker, session_factory, managed_root, api_client, cfr_cut_video, monkeypatch
) -> None:
    """CFR completes through the chain with containment, SHA/size, stable
    Scene IDs and orphan-cleanup guarantees."""
    pid = _create_project(api_client, "S05C02 cfr regressions")
    _upload_video(api_client, pid, cfr_cut_video)
    orch = _fast_orchestrator(session_factory, managed_root, monkeypatch)
    state = _submit_chain(api_client, pid, cfr_cut_video.name)
    orch.stop(timeout=2.0)
    item_id = state["video_item_id"]
    _drive_to_terminal(worker, session_factory, item_id)

    chain = _get_chain(api_client, pid)
    assert chain["chain_status"] == "completed"
    assert chain["scenes_count"] == 2

    # Containment: every managed file lives under artifacts/; staging empty.
    root = managed_root.resolve()
    assert _staging_files(root) == []
    for f in [p for p in root.rglob("*") if p.is_file()]:
        assert f.is_relative_to(root / "artifacts"), f"file outside artifacts/: {f}"

    # SHA-256/size of every ready artifact match the bytes on disk.
    arts = _ready_video_artifacts(session_factory, "default")
    assert len(arts) == 2
    for art in arts:
        sha, size = _artifact_sha_size(root / art.relative_path)
        assert (art.sha256, art.size_bytes) == (sha, size)
        assert ".." not in art.relative_path.split("/")

    # Canonical Scene rows: exact CFR grid, revision 1.
    rows = _scene_rows(session_factory, item_id)
    assert [(r.position, r.start_frame, r.end_frame) for r in rows] == [
        (0, 0, 29),
        (1, 30, 59),
    ]
    assert [(r.start_time_ms, r.end_time_ms) for r in rows] == [(0, 999), (1000, 1999)]
    assert all(r.status == "pending" for r in rows)
    assert all(r.revision == 1 for r in rows)
    assert all(r.legacy_scene_id is None for r in rows)

    # Stable Scene IDs across a successor retry (rows committed, then the
    # step permanently fails; the successor reuses the committed rows).
    pid2 = _create_project(api_client, "S05C02 stable scene ids")
    _upload_video(api_client, pid2, cfr_cut_video)
    state2 = _submit_chain(api_client, pid2, "stable ids")
    orch.stop(timeout=2.0)
    item2 = state2["video_item_id"]
    _run_job(worker)  # import
    orch.advance_once()
    _run_job(worker)  # proxy
    orch.advance_once()
    jobs2 = _chain_jobs(session_factory, item2)
    assert len(jobs2) == 3
    scene_job2 = jobs2[2].id

    real_commit = scene_detector._commit_scene_rows

    def commit_then_fail(ctx, det_ev):
        real_commit(ctx, det_ev)
        raise scene_detector.SceneDetectorError(
            "PUBLICATION_FAILED", "injected permanent failure after commit"
        )

    monkeypatch.setattr(scene_detector, "_commit_scene_rows", commit_then_fail)
    _run_job(worker)
    monkeypatch.undo()
    assert _job_state(session_factory, scene_job2) == "failed"
    committed_ids = [r.id for r in _scene_rows(session_factory, item2)]
    assert len(committed_ids) == 2

    retry = ao_module.get_analyze_orchestrator().retry_chain(pid2)
    assert retry is not None
    _run_job(worker)
    rows_after = _scene_rows(session_factory, item2)
    assert [r.id for r in rows_after] == committed_ids
    assert all(r.revision == 1 for r in rows_after)
    assert _staging_files(root) == []

    # Orphan cleanup: a cancel of the proxy step never materializes the
    # scene step and leaves zero staging leftovers.
    pid3 = _create_project(api_client, "S05C02 orphan cleanup")
    _upload_video(api_client, pid3, cfr_cut_video)
    state3 = _submit_chain(api_client, pid3, "orphan")
    orch.stop(timeout=2.0)
    _run_job(worker)
    orch.advance_once()
    jobs3 = _chain_jobs(session_factory, state3["video_item_id"])
    proxy_job3 = jobs3[1].id

    real_ffmpeg = video_proxy._run_ffmpeg

    def encode_then_cancel(ctx, cmd, *, timeout_seconds, staged_path):
        resp = api_client.post(f"/api/jobs/{proxy_job3}/cancel")
        assert resp.status_code == 200
        return real_ffmpeg(ctx, cmd, timeout_seconds=timeout_seconds, staged_path=staged_path)

    monkeypatch.setattr(video_proxy, "_run_ffmpeg", encode_then_cancel)
    _run_job(worker)
    monkeypatch.undo()
    assert _job_state(session_factory, proxy_job3) == "cancelled"
    assert len(_chain_jobs(session_factory, state3["video_item_id"])) == 2  # no orphan scene job
    assert _staging_files(root) == []
    with session_factory() as s:
        assert s.scalar(
            select(Job).where(
                Job.owner_type == "video_item",
                Job.owner_id == state3["video_item_id"],
                Job.idempotency_key.like("ANALYZE_MEDIA:scene_detect:%"),
            )
        ) is None


def test_vfr_chain_completes_through_orchestrator(
    worker, session_factory, managed_root, api_client, vfr_cut_video, monkeypatch
) -> None:
    """A genuinely-VFR source completes through the same chain with the
    canonical avg_frame_rate grid (regression: VFR is accepted and mapped
    exactly, VIDEO_PREFLIGHT_CONTRACT §3.1)."""
    pid = _create_project(api_client, "S05C02 vfr")
    _upload_video(api_client, pid, vfr_cut_video)
    orch = _fast_orchestrator(session_factory, managed_root, monkeypatch)
    state = _submit_chain(api_client, pid, vfr_cut_video.name)
    orch.stop(timeout=2.0)
    item_id = state["video_item_id"]
    _drive_to_terminal(worker, session_factory, item_id)

    chain = _get_chain(api_client, pid)
    assert chain["chain_status"] == "completed"
    assert chain["scenes_count"] >= 2

    # The IMPORT checkpoint recorded the REAL VFR classification
    # (VIDEO_PREFLIGHT_CONTRACT §3.1 — VFR is accepted and classified).
    with session_factory() as s:
        import_job = s.scalar(
            select(Job)
            .where(
                Job.owner_type == "video_item",
                Job.owner_id == item_id,
                Job.idempotency_key.like("ANALYZE_MEDIA:video_item:%"),
            )
            .order_by(Job.created_at.desc())
        )
        assert import_job is not None
        import_step = s.scalars(
            select(JobStep)
            .where(JobStep.job_id == import_job.id)
            .order_by(JobStep.position)
        ).first()
        import_cp = json_loads(import_step.checkpoint_json or "{}")
        src_video = import_cp["probe"]["video_stream"]
        assert src_video["fps_classification"] == "VFR"
        assert src_video["r_frame_rate"] != src_video["avg_frame_rate"]
        avg_num = int(src_video["avg_frame_rate"]["num"])
        avg_den = int(src_video["avg_frame_rate"]["den"])
        assert avg_num > 0 and avg_den > 0

        # The scene step consumed the canonical grid of the proxy (CFR-
        # resampled onto the exact avg_frame_rate rational of the source).
        scene_job = s.scalar(
            select(Job)
            .where(
                Job.owner_type == "video_item",
                Job.owner_id == item_id,
                Job.idempotency_key.like("ANALYZE_MEDIA:scene_detect:%"),
            )
            .order_by(Job.created_at.desc())
        )
        assert scene_job is not None
        scene_step = s.scalars(
            select(JobStep)
            .where(JobStep.job_id == scene_job.id)
            .order_by(JobStep.position)
        ).first()
        scene_cp = json_loads(scene_step.checkpoint_json or "{}")

    timebase = scene_cp["detection"]["timebase"]
    assert timebase["schema_version"] == 1
    assert (timebase["fps_num"], timebase["fps_den"]) == (avg_num, avg_den)
    assert _staging_files(managed_root) == []


def json_loads(raw: str) -> dict:
    import json

    payload = json.loads(raw)
    assert isinstance(payload, dict)
    return payload
